### ISSUE TITLE
Bug: cog. aliases s.v. 'sew'

### ISSUE THREAD

**Issue by m-scarborough** [lingdb/CoBL#104]
I was doing some cognacy on 'sew' and I noticed that the cognate aliases ( A, B, C, etc.) appear to have disappeared. See http://134.76.24.144/meaning/sew/cognateclasslist/.  I'm not sure what happened, since they still appear to be listed in other meaning sets, but I'm not sure if there's a bug that has also made them disappear elsewhere.

**Comment by m-scarborough** [comment]
Update: I've noticed that the cognate aliases disappear in this way when updating information in the tables from the 1 meaning all-cog sets view.  Before the update, the cognate aliases are present, after the update, they've disappeared from the table.  It just happened when I put in some root and language information in http://134.76.24.144/meaning/small/cognateclasslist/

**Comment by m-scarborough** [comment]
The cognate aliases themselves are evidently not getting deleted, since they're still viewable in the 1 meaning all languages tables so there's no loss of data.  But once they disappear from the 1 meaning all cognate sets it makes the tables a bit more difficult to navigate when going back and forth between individual cognate sets in a particular meaning.

**Comment by runjak** [comment]
Thanks for the detailed information on this.
I see that something is not right, but will need to investigate further to figure out what exactly causes the problem.

**Comment by runjak** [comment]
I've just deployed the fix for this.
The aliases for Cognate Classes should be back in place everywhere.
