### ISSUE TITLE
Add branch colour boxes to the 1 meaning--all cognate sets table

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#112]
This was first mentioned in an additional request made by Cormac within issue #92.
The branch colours should also be added to the 1 meaning/ all cognate sets table beside each individual cognate set, representing in a bar, languages from what family are associated to that cognate set.
What is needed here is something like this:  
![screenshot - 14_03_2016 13_05_08](https://cloud.githubusercontent.com/assets/8819910/13744005/84ae6bc8-e9e5-11e5-90b6-74365043d14e.png)
Each cognate set entry row should include (to the left) a colour bar showing which branches use this cognate set.  That is, if that cognate set is the one referenced by the Swadesh (i.e. not excluded!) term in _any_ language in that branch (e.g. any language with the corresponding branch codes), then show that colour, if not leave it blank.  The result, for three different cognate sets would look as in the above image, if the first cognate set were used in at least some Italic, Baltic, Slavic, and Greek languages;  if the second cognate set were used only in some Baltic and some Greek, the third only in Indic and Iranic, and so on.
This too would be really helpful as soon as possible, but I'm a bit concerned that it will end up slowing pages down as much as issue #92.  Any idea, Jakob?

-----

Updated todo from comments below:
- [x]  A little bit of space between the last box (Goidelic) and the ID number.  (Ideally, the ID number should be right justified anyway.)
- [x]  If it's not too much hassle, colour blocks just a little smaller might be a bit easier on the eye, and not taking up the whole space, but squares with a thin bit of space around them at least. But if you're using a background colour system, then I presume this may be more hassle than it's worth for now, and not worth spending hours on if that's what it would take.

**Comment by runjak** [comment]
I'll look into this and the connected performance once the other higher priority issues are out of the way. In general I think that it is possible to increase the site performance if I cannot get it to work with the current performance. This would mean that I will eventually address #84. So either before or after #84 I should be able to realize this.

Also: I enjoy the new time label :smile:

**Comment by runjak** [comment]
* With some code from [stackoverflow](http://stackoverflow.com/a/7085003/448591) it was possible for me to get the vertical rotation of text to work as expected.
* I've also figured out a way to get the colors into the columns.

The next step will now be to let the color depend on the cognate classes correctly.
![screenshot_2016-06-08_14-10-56](https://cloud.githubusercontent.com/assets/5417642/15893890/e201bb3c-2d82-11e6-99cb-a5483444d7ee.png)

**Comment by runjak** [comment]
Enjoying the colors:
![screenshot_2016-06-08_14-30-59](https://cloud.githubusercontent.com/assets/5417642/15894337/ac0f3484-2d85-11e6-9434-f4248ce10e64.png)
It appears that from the perspective of response time all things are still fine.
I'll see how/if this changes with leaving the according fields white.

**Comment by PaulHeggarty** [comment]
I see you have showing in this example both Italic (9-0-0-0) and Roman (9-1-0-0).  We might actually want both of these (Cormac?), although more generally there should be an urgent clarification here:  we do not want *all* clades to be shown here.  Only the ones formerly shown as filter buttons, which now aren’t showing any more (while you fix this, I presume).
The ones we need to see in this page, and also have filter buttons for, are only:
1-0-0-0
2-0-0-0
3-0-0-0
4-0-0-0
5-0-0-0
6-1-0-0
6-2-0-0
6-3-0-0
7-1-0-0
7-2-0-0
8-0-0-0
9-0-0-0
10-0-0-0
I think we formerly had a convention to show as filter buttons only those clades which had been given a Filt Abbr.  But in fact values have been filled in for all of those now.  We could go back and delete the Filt Abbr values for any clades we don’t want to use as filters, if that's easier for you.  I don’t think they’re used anywhere else, are they?
Finally, remember that there should also be a (grey) 'Rfc' filter button for the set of all languages that have their Ref. value (in the Languages Reference table) set to true.  This does not appear as a block on the cognate set view, however.

**Comment by PaulHeggarty** [comment]
Having seen that you have it working already with all clades, I think simplest would be to use the system we had previously proposed.  Ignore my numbers above, but do switch off any filters that don’t have a Filt Abbr entry.  That way we can actually swith individual ones back on if we really want.  (I’m not sure whether Cormac or others would perhaps actually value separate filters for Goidelic and Brythonic, rather than just an overall Celtic.)
In any case, this looks great already...

**Comment by PaulHeggarty** [comment]
Perhaps the time label on this issue might be reduced somewhat now?  ;)

**Comment by runjak** [comment]
I did not realize that you'd like an Rfc column in this case, too.
Thanks for specifying it now.
Introducing the `Rfc` case will mean doing some duplicate work as it's not specified in the Clades talbe, but instead is an inferred property of the data.
I'm wondering how I'll best implement this.

**Comment by PaulHeggarty** [comment]
No!  The  'Rfc' is needed only as _filter button_ , i.e. only on the `1 Meaning all Languages` form.  Not on the `1 Cognate All Languages` Form.  That's what I meant above with:  "This does not appear as a block on the cognate set view, however."

**Comment by runjak** [comment]
Ah - OK - I just didn't expect the `Rfc` button to be brought up at all if it isn't necessary for this view.

**Comment by runjak** [comment]
By leaving out the clades that don't are not connected to any of the currently viewed cognate classes I can get a smaller table:
![screenshot_2016-06-08_16-19-53](https://cloud.githubusercontent.com/assets/5417642/15897634/8d8f3cc4-2d95-11e6-9dbd-4a0952e81f27.png)

I will now implement displaying only the clades that have a `Filt Abbr` set to narrow this down further. Is it ok to hide clades that have no colored box, or would you rather see them as well?

**Comment by PaulHeggarty** [comment]
I would rather see them as well, because it's a bug check device.  In theory there should not be any clades that don’t have at least one box coloured for at least one cognate set, because all languages should have a cognate specified for every meaning.  I wonder what has happened to the Celtic entries for the cry word you show in the screenshot...  Or is this a bug with your system?
I will now delete the `Filt Abbr` entries that we don’t want, so that the that new approach works!

**Comment by PaulHeggarty** [comment]
OK, I’ve checked the data for `cry` and I presume that it's a new Jena list word, which is why it's not entered for all languages yet.  So your system does seem to work, but incidentally, `cry` is not a good example to test with.  Best try another meaning, I think `ash` or `black` would be safer.

**Comment by runjak** [comment]
Well - I'm just testing weather I get connections where they should be from the data.
In general I'm oftentimes messing with my copy of the data to test things out that I would never do to the database at cobl.info. For my use case `cry` worked perfectly fine ;)

**Comment by runjak** [comment]
I've made the comparison with `ash` again - it has a lot more entries like you expected.
Also for my test case I removed the abbreviations on 3 Italic clades which no longer appear.
![screenshot_2016-06-08_17-03-06](https://cloud.githubusercontent.com/assets/5417642/15899133/082b9b6c-2d9b-11e6-9202-b96ace3d2813.png)

**Comment by PaulHeggarty** [comment]
This is looking fantastic, by the way, I can’t wait to see this up and running.  Instantly provides great visual patterning:  note how Iranic (but not Indic or Nuristani) shares something with Slavic here, a curious pattern I’d instantly want to click on to see the detail.  Linguists are going to love this feature, and I will be putting it into talks and demos from now on!

A couple of minor formatting tweaks I’d suggest, though:
- [ ]  A little bit of space between the last box (Goidelic) and the ID number.  (Ideally, the ID number should be right justified anyway.)
- [ ]  If it's not too much hassle, colour blocks just a little smaller might be a bit easier on the eye, and not taking up the whole space, but squares with a thin bit of space around them at least. But if you're using a background colour system, then I presume this may be more hassle than it's worth for now, and not worth spending hours on if that's what it would take.

**Comment by runjak** [comment]
Ok, I'll see to these after deployment.
Deployment may close this issue automagically - in that case I'll make sure to reopen it.

**Comment by runjak** [comment]
Reopening for style adjustments…

**Comment by runjak** [comment]
* It may be necessary to do a force refresh to get the old css out of the browsers cache.
You will see the need for this by the vertical text parts possibly being displayed broken.
* I've just discovered that the layout of the 1 meaning all cognate classes table is broken for users that aren't logged in. In this situation the cells have a stronger variety for sizes rendering the coloring less helpful.

**Comment by PaulHeggarty** [comment]
But the colour block system now opens up a lot of opportunities, such as for #172 on a new way of ordering entries in the cognate sets form.

**Comment by PaulHeggarty** [comment]
Big question:  what happens if a lexeme is marked as not Swadesh?  Does it still find its way into the calculations for this system?   Or are the 'present in this clade or not?' values calculated only from true Swadesh lexemes, with the excluded ones already excluded?  That's how it should be, but I thought I'd better check.  Cormac, you could even construct an artificial test for this.

**Comment by runjak** [comment]
Lexemes marked as not swadesh should currently be excluded from this calculation.

**Comment by CasFre** [comment]
Very nice and helpful indeed!

Would it be possible to have EITHER the sub-branches OR the 1st-level branches, in such a way that the 1st-level branches such as e.g. Indo-Iranic only show up if all the sub-branches are represented, and otherwise the respective sub-branch(es) only?
In the screenshot above with ID 1105 which @PaulHeggarty mentioned as an interesting example this would e.g. not show Indo-Iranian but Iranian only.
Or maybe the user can decide whether he wants to see 1st-level branches only or 2nd-level branches as well/instead?
@nitsnatsnok, what would you say?

Also, isn't it imbalanced after all the discussions we had to have subgroupings for Germanic and Italic and even Baltic, but not for Slavic?

And: Are these colours the same as for the thin side-lines that we have in the one mean - all lang lists? It would be good to be consistent in that respect.

**Comment by CasFre** [comment]
Okay, on my first point: The double view that I criticized may on the other hand be helpful as well in recognizing which branches show which cognate classes (e.g. by the double marking one nevertheless can easily perceive at a glance all the cognate classes where Indo-Iranian is involved).
But in any case it seems that it is not working properly yet:
![colorboxes_cogcl](https://cloud.githubusercontent.com/assets/17431124/15925253/ad066860-2e36-11e6-88bf-d449aaf640c3.jpg)
While in 694 we have all the Indo-Iranian branches represented by at least one language in the cognate class, the 1st-level branch Indo-Iranian does not show up as a separate colour box, whereas with cognate 205 we have only West Germanic lexemes, but it is only Germanic that has a colour box and not West Germanic as well.

**Comment by PaulHeggarty** [comment]
This is *not* a programming issue for Jakob, however.  He has already got this dead right.  It's just a choice about what it's useful to see, and thanks to Jakob's programming, we can actually still choose which levels we want to see.  If you want to see the individual Germanic clades, like West Germanic, then all you need to do is go into the clades table and give that clade an abbreviation, and refresh everything.  Then it will appear.  Since this is principally for you to work with now, if you want this detail, you should make alterations accordingly.  That is the beauty of the system that Jakob had programmed.

**Comment by CasFre** [comment]
Thank you for that remark, Paul.
Could you tell me a bit more precisely what I have to change in the clades table? - Because, as you can see from the following screenshot, both Indo-Iranian (which shows in the colorboxes above) as well as the Germanic sub-branches have no entries in the column "Filt abbr".
By the way, is it safe to have everyone fiddling about with the clades table? Because this is not a personalized table yet, is it?
![clades table for colourboxfiltering](https://cloud.githubusercontent.com/assets/17431124/15935831/0833c610-2e69-11e6-9782-37cf6b094b0e.jpg)

**Comment by PaulHeggarty** [comment]
Yes, you need to add aand abbreviation text in the `Filt Abbr` column if you want that clade to show in the cognates table, or delete any text in that column you don’t want that clade to show. 
You should feel free to set it how you want for now, within reason, because it's above all you that this is intended to help at the moment.
In theory yes, not everyone should be fiddling with the table.  But in practice they won’t be.  And perhaps only if they have a certain user rights level.  It should be possible only for full admin users, but that may already be the case for the clades table -- is that so, Jakob?

**Comment by CasFre** [comment]
Okay, thank you again, Paul.

**Comment by PaulHeggarty** [comment]
I can’t resist this wonderful example from the most stable meaning in the entire database:
![screenshot - 10_06_2016 13_59_01](https://cloud.githubusercontent.com/assets/8819910/15963889/9e7d8528-2f15-11e6-9b06-786218bf10a5.png)
http://www.cobl.info/meaning/two/cognateclasslist/
Then click next word and you get the opposite type of pattern:
http://www.cobl.info/meaning/vomit/cognateclasslist/

**Comment by runjak** [comment]
I can make the color blocks a bit smaller by introducing a `border: 2px solid #F9F9F9;` to them. The result looks like this:
![screenshot_2016-06-24_13-25-27](https://cloud.githubusercontent.com/assets/5417642/16336638/39f6ad96-3a0f-11e6-8f10-5bc11a5ad9f4.png)

**Comment by nitsnatsnok** [comment]
These color blocks are beautiful and helpful, but can we nethertheless add a feature to hide them? It takes a lot of space on the left and in some cases moves the actual data out of sight.

**Comment by runjak** [comment]
@nitsnatsnok I think you're essentially asking for something like #94.
So yes we will add this - just the priorities are not fitting at the moment.
