### ISSUE TITLE
Strange interrelations betw. loanword-marking on lexeme page and columns Cog. Alias, loan, excl, Loan Event

### ISSUE THREAD

**Issue by CasFre** [lingdb/CoBL#115]
Look at the Albanian words in this table:
![loanword coding_albanian_fish_4 variants](https://cloud.githubusercontent.com/assets/17431124/13952517/1ca18670-f037-11e5-9645-632e228eb62b.png)

**Comment by m-scarborough** [comment]
That looks to me like some anomalies of how the data was coded with its respective sources at the individual lexical level.  We're encoding the set as a separate loanword event class, but the lexical sources for Albanian Corinth, Gheg, Tosk as they were encoded at an earlier time are stating that they're loanwords from within its own class (and consequently LexDB is excluding them).
<img width="610" alt="screen shot 2016-03-22 at 12 49 16" src="https://cloud.githubusercontent.com/assets/15671787/13952125/87f77a8e-f02c-11e5-90b5-665934db93cf.png">
In the case of a loanword event class like this one, this data source should be set to a reliability level other than 'loanword'.

**Comment by m-scarborough** [comment]
I mean to say, coding them as loanwords within their own class in this case is in all likelihood wrong, but as they are encoded here the database thinks that Albanian Gheg borrowed peshk from Albanian Standard or something, which I would suppose to be almost certainly not the case.

**Comment by CasFre** [comment]
Short background information: These words are loanwords from Latin. The Latin word belongs to cognate class B from PIE *pisk, *peisk which you also see above.
According to our policy of how to treat loanwords, I created a new cognate class J with a loan event from Latin.

The problem is: If a certain lexeme is marked on the individual lexeme page as (1) loanword in a Source of lexical data, (2) loanword in a cognate coding source, (3) loanword in both (4) as none.
Consider the following screenshots in relation to the one above:

Albanian_Standard is coded for neither and shows the results we want in the 1 mean - all lang list:
![loanword coding_albanian_standard_peshk](https://cloud.githubusercontent.com/assets/17431124/13952080/b2ad8040-f034-11e5-8ffe-a928d1f377f4.png)

Albanian_Corinth is marked as a loanword in a Source of lexical data:
![loanword coding_albanian_corinth_peshk](https://cloud.githubusercontent.com/assets/17431124/13952186/514091ca-f035-11e5-8823-f877396b2eda.png)

Albanian_Gheg is marked for both:
![loanword coding_albanian_gheg_peshk](https://cloud.githubusercontent.com/assets/17431124/13952264/bc5a1134-f035-11e5-8372-cf9abe2dd596.png)

So the Gheg example shows that marking a lexeme as a loanword as far as cognacy is concerned overrides its status as "excl" which comes from its being marked as a loanword as far as lexical data are concerned.

**Comment by CasFre** [comment]
Note again that this also affects cognacy judgment under "Cogn. Alias" in the 1 mean - all lang list and the colour coding.

**Comment by CasFre** [comment]
For the moment, the best solution for me as well as the branch specialists is to manually remove loanword judgments on individual lexeme pages from sources of lexical data and from the cognate class sources, as @m-scarborough suggested.
In the longer term, some programming effort might be required (e.g. removing "loanword" as a possible option in these categories), but this is something @cormacanderson, @PaulHeggarty and @runjak should discuss in more detail.

**Comment by cormacanderson** [comment]
This issue is likely also linked to https://github.com/lingdb/CoBL/issues/88 and is relevant for how the export file will be generated in the completed database

**Comment by runjak** [comment]
This issue has been solved by breaking up the counts for loan words and excluded lexemes into ones for cognate judgement and lexical judgement.
