### ISSUE TITLE
Progress Tracker: Web Dictionary Lexeme Links

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#116]
### Languages still to do    [when completed, move down into next comment box]
-------------------------------------------------------------------------------------

**Comment by PaulHeggarty** [comment]
Languages Completed                              Date Completed
-------------------------------------------------------------------------------------
English (OED)                                           2016 02 28  
Old Irish                                                     2016 02 28

**Comment by morenovuleta** [comment]
Languages done:

French
Latin
Greek
Lithuanian
Dutch
