### ISSUE TITLE
Wrong Cognate Class Assignment

### ISSUE THREAD

**Issue by CasFre** [lingdb/CoBL#118]
There is a bug with http://www.cobl.info/cognate/2200/: On the lexeme pages and on the one meaning - all languages list, the Tocharian lexemes are assigned "O" and not "Ai". "O" has however been assigned to http://www.cobl.info/cognate/3772/.

**Comment by cormacanderson** [comment]
To clarify this, there is a mismatch between the cog alias on the 1 meaning/ all cognate sets table, and the cog alias on the 1 meaning/ all languages table, as well as in the individual records. This does not appear to be confined to these particular cognate sets either, but is general. @runjak  Is this what is breaking the export? Does the 1 meaning all cognate sets table generate its own cog aliases?

**Comment by runjak** [comment]
I'm not sure about the export but will see where the cog aliases are generated and how they are saved in the database.
