### ISSUE TITLE
Header bar should remain visible on scroll down in 1 Language view

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#123]
By this I mean the page header that includes the save button.

**Comment by runjak** [comment]
I found an approach that works on the language list and the clades table.
This approach will now need to be expanded to the other tables.
The idea to mimic the behavior of the top menu turned out to be a promising one.

**Comment by runjak** [comment]
Possible problem:
The width of the portion that stays above the table but is different for different tables is currently fixed to the screen width.
While this works well for views that have tables at least in similar width to the screen but likely wider it can look funny for thinner tables:
![screenshot_2016-07-26_12-32-31](https://cloud.githubusercontent.com/assets/5417642/17134917/337463aa-532d-11e6-8a3d-69de176c42dd.png)

**Comment by runjak** [comment]
This issue needs a few adjustments so that the tables still look OK if the client isn't logged in.

**Comment by runjak** [comment]
Code for this issue is deployed now, a cache clear refresh may be necessary.
