### ISSUE TITLE
Add a count of languages in the current list to the header bar for Languages Reference Table

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#125]
Use the normal format for such counts, as used for the count of lexemes in a given language in 1 language view.  I.e. format like this:
![screenshot - 07_04_2016 15_13_12](https://cloud.githubusercontent.com/assets/8819910/14352134/4ced663e-fcd3-11e5-876b-785e15a176dc.png)

**Comment by runjak** [comment]
I've added the requested count and will roll out the change soon.
![screenshot_2016-05-19_12-58-54](https://cloud.githubusercontent.com/assets/5417642/15391446/8425e75c-1dc1-11e6-9f85-ceffab2bf045.png)
