### ISSUE TITLE
Add export csv file of current language reference list data

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#126]
This should be an export icon in the header bar of the of the language reference table.  It should export that list of languages as a csv file, with these fields in this order:
Name
Mean TD
Std Dev.
Lv 0
Lv 1

**Comment by runjak** [comment]
Should the list be limited to only the described fields or should all fields be included but the described fields be in the order listed above?

**Comment by PaulHeggarty** [comment]
The first option:  limited to only the fields described above.  Ignore other fields for now.

**Comment by PaulHeggarty** [comment]
This to be complemented soon by a calibration export file in nexus format, i.e. plain text but with the extension .nex
I've asked Remco to clarify the output syntax we need for this.

**Comment by runjak** [comment]
OK - I think I should be able to deploy this feature today, and will update this issue as usual.

**Comment by runjak** [comment]
I'll deploy this export functionality now.
The header bar should look like this afterwards:
![screenshot_2016-04-08_12-23-01](https://cloud.githubusercontent.com/assets/5417642/14381191/b795d60e-fd84-11e5-8c3c-b9a4bc75df71.png)
Clicking on the download icon will trigger an export of the currently selected language list.

**Comment by PaulHeggarty** [comment]
Just tried this.  The first time, it downloaded the file for the wrong language list, the one I had been viewing before the last time I had changed language list.  I did a force reload, then downloaded again, and that did give me the correct current language list.  So could you implement a force reload whenever the download button is clicked?  And run the download immediately after that reload?  Would that fix the problem?

**Comment by runjak** [comment]
Was this before or after the re-login for #124?
I'll see if and how I can reproduce this problem.

**Comment by PaulHeggarty** [comment]
Right you are.  It was before the re-login.  I've logged out and back in again, and this now works too!
Which all makes me wonder whether every time you do an update, it should automatically log all users out -- but then they’d lose anything they’d been working on.  Any solution?

**Comment by PaulHeggarty** [comment]
This is actually now a sub-issue of the nexus calibration export #161, because the nexus calibration export will replace the csv export.

**Comment by runjak** [comment]
Given that #161 is done now I'll close this issue.
