### ISSUE TITLE
Add a new field/column "Beast name" to languages reference table

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#130]
This should be a text field.  
This should appear immediately after the language name column.  Eventually we will drop this, but only once the calibration export is fully working.  For now it's needed as a consistency check for Remco.

I’ve put this as requiring only a few minutes:  perhaps optimistic, but I really do hope that adding a simple new text field and column is something that should not take an hour.  Can you confirm this?

**Comment by runjak** [comment]
I'm working on this now and will deploy the updated page afterwards.
It should not take an hour to get this done.
