### ISSUE TITLE
Clean up the language branches form: narrower columns

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#132]
The columns are way too wide.  The headers should be shorter, too:
Level 0   (not 'Family Index')
Level 1
Branch Name
Abbreviation
Colour (hex)   (I do like my British spellings!)

**Comment by runjak** [comment]
I've reduced the table and column widths like this:
![screenshot_2016-04-08_14-28-58](https://cloud.githubusercontent.com/assets/5417642/14383569/40fad776-fd96-11e5-8a34-a2a0412bbf87.png)
