### ISSUE TITLE
Fix requested format for language date fields

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#133]
On the languages reference page, no changes will save now, because existing entries in the language time-depth fields are returning 'please match the requested format', wanting numbers fully specified as four explicit digits, 0000.
So 0125 works, but 125 does not.
This was probably my mistake in an instruction, it's not actually 0000 we need, but any integer up to 9999, it does not have to have leading zeros.  125 should be fine.  Maybe the correct format code for that is actually###0 or something.

**Comment by runjak** [comment]
Yes, this is exactly because of the pattern checks for the inputs.
The nice thing is that it's easy enough to fix.

**Comment by PaulHeggarty** [comment]
All four of those date fields should have the same pattern matching.

**Comment by runjak** [comment]
They now have the same pattern matching, which allows precisely these inputs:
* Empty inputs
* Numeric inputs of lengths up to 4

The regex for this is `[0-9]{0,4}`.
