### ISSUE TITLE
Complete and correct phonemic/phonetic transcription entries for Romanian, Italian and French

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#134]
Transcriptions are given in the phonetic column, but they are phoneMic, not (major allophone) phonetic.
So you should use the < > arrows to move them from the phonemic to the phonetic cells.  

Examples:  In Italian, you write: /respi'rare/, not [ɾespiˈɾaːɾe].
= Does not show long vowels in Italian stressed open syllables, a major phonetic allophone.
Those should not be marked in the phoneMic transcription, but should in the phoneTic one.  For now, just move the current transcriptions into the phoneMic cell.

**Comment by PaulHeggarty** [comment]
Also, correct some errors even on the phoneMic level... 

= Use the IPA flap not trill symbol for Italian single <r>.  The default allophone is tap, not trill, so that should be the phonemic symbol too.

= Uses the correct IPA character for stress marking:  it should be ˈ, not apostrophe '.

Please also do a search-replace for the correct IPA stress character in other languages, such as the phonetic transcriptions for Spanish (which are indeed major allophone phonetic, not phonemic, so they should stay in ththe phonetic cell).

**Comment by PaulHeggarty** [comment]
Finally, complete the missing transcriptions in Romanian, French and Italian.

**Comment by morenovuleta** [comment]
Completed and corrected
