### ISSUE TITLE
When using the branch filter buttons, filter is reset when changing word

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#135]
If on 1 meaning all languages for meaning 'ash', you click the toggle button to filter to only Romance languages, for example, and then click the next meaning 'back', the filter drops and all languages are displayed again.  The filter settings should remain from one meaning to the next.

**Comment by runjak** [comment]
This is part of a broader issue where we want the browser to remember the state of filtering/sorting across page loads. The browsers session should remember the last used settings and filter/sort by them again when the user changes the page.

**Comment by runjak** [comment]
I've reimplemented the filter code.
The new clade filter will remember the filter choice for duration of the browser session.
That is if the browser is closed the filter will forget the choice and start not filtering any languages.
This issue will be closed automagically on deployment.
