### ISSUE TITLE
Make page header language or meaning name a filter box

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#138]
- [ ] Make this label a filter box in which to type another language/meaning name, to switch immediately to that page.  Using normal filter/search function by the first few letters typed. I.e. on the meaning page 'head', clicking on 'head' opens a filter box where I can type in foot, then hit enter, and it will go to the page for the meaning foot.
- [x] Correct the placement of the before and after language/meaning names.  They should be displayed as in Sound Comparisons (see screenshot below), as left justified and right justified respectively, with the current language/meaning label as centred.  This improves presentation, and consistency of positioning as one clicks through the words.
![screenshot - 26_05_2016 10_50_33](https://cloud.githubusercontent.com/assets/8819910/15569106/c7477cf8-232f-11e6-8142-c6f3766187f1.png)

**Comment by CasFre** [comment]
I think this is a good idea. But would it be possible to keep the "next/previous" buttons alongside? These are nevertheless quicker for me when browsing through the meanings than the envisaged filter box.

**Comment by runjak** [comment]
Yes, we can keep those buttons as well, of course.

**Comment by runjak** [comment]
I assume it's OK to remove the `―` from the sides of the [currently selected language](http://cobl.info/language/Proto-Indo-European/wordlist/Jena200/) when moving the prev/next links further to the sides?
![screenshot_2016-06-29_13-13-52](https://cloud.githubusercontent.com/assets/5417642/16450115/826c66b6-3dfb-11e6-8428-968e87ab7886.png)

**Comment by runjak** [comment]
I've got an adjustment for the prev/next links to look like this:
![screenshot_2016-06-29_13-31-37](https://cloud.githubusercontent.com/assets/5417642/16450548/deac1186-3dfd-11e6-85fa-cacd7c93cd27.png)

**Comment by runjak** [comment]
I have a patch that makes it possible to use the headlines as filters.
To do this the following steps are necessary:

1. Click on the headline (This will mark the whole headline)
2. Start typing to replace the headline with something different
3. Suggestions will pop up depending on typed input
4. Selection of a suggestion can be done via keyboard or mouse and triggers the browser to lead the corresponding page.

Suggestions look like this:
![screenshot_2016-06-30_16-49-51](https://cloud.githubusercontent.com/assets/5417642/16492776/3b7fd1dc-3ee3-11e6-8859-de679b3bfbf3.png)

This issue will get closed automagically after deployment.
