### ISSUE TITLE
Bug: different cognate aliases relating to same cognate class

### ISSUE THREAD

**Issue by m-scarborough** [lingdb/CoBL#141]
<img width="1160" alt="screen shot 2016-04-13 at 17 11 14" src="https://cloud.githubusercontent.com/assets/15671787/14500676/e6400492-019a-11e6-87f0-c5d7adbb6d0b.png">

In this screenshot, the Greek cognates presented as G and H, should, and actually are, all be in the same cognate class; both links for G and H click through to the same class http://cobl.info/cognate/1536/.  They should be listed as the same alias (either all G or all H), and I don't know why the presentation is splitting them into different aliases.

**Comment by m-scarborough** [comment]
And I just noticed the same thing is also happening for aliases H and F in the meaning 'skin' as well.

<img width="1069" alt="screen shot 2016-04-13 at 17 19 49" src="https://cloud.githubusercontent.com/assets/15671787/14500983/1c2abace-019c-11e6-8a8d-7eafde2dd6cb.png">

**Comment by runjak** [comment]
This is probably related to #118.
I'll investigate where this comes from.
