### ISSUE TITLE
Nexus export needs to be done in two versions each time

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#143]
The nexus output file contains two sets of lines (the taxa block and the (very long) list of all charstatelabels ) that BEAUti currently can't process, so it won't load our files.  
However, other uses of the nexus files DO need these lines.  
So each export needs to put the same data-set into two versions, both nexus files.
One should be named as now, the other should have BEAUti prefixed to the filename.

Obviously, the calculations should run only once, the same data are being exported!  Presumably as the string for export is being concatenated, 'topped and tailed' by the introduction and closing blocks, you actually do two versions of that export string, and only add the taxa block and charstatelabels to one of them (the normal file, not the BEAUti-friendly file).

The normal file should be as now, with no changes.
The BEAUti-friendly file should follow Remco's instructions, below.  I’ve identified in bold the bits that need to be 'cut' (= not added to that export string in the first place).  
In short:
1) suppress the taxa block altogether, 
2) suppress the (very long) list of all charstatelabels.  Just keep in the first 3 lines 
begin characters;
  dimensions nchar=4987;
  format symbols="01" missing=?;

In detail ...

================================
Instead of exporting 

**begin taxa;
  dimensions ntax=107;
  taxlabels Hittite Luvian Lycian Tocharian_A Tocharian_B Mycenaean_Greek Ancient_Greek NT_Greek Greek Albanian_Standard Classical_Armenian Armenian_Eastern Armenian_Western Avestan Sogdian Parthian Khotanese Old_Persian Middle_Persian Wakhi Baluchi Kurdish Tajik Persian Waziri Pashto Shughni Sarikoli Ossetic_Iron Ossetic_Digor Vedic_Sanskrit Pali Nepali Assamese Oriya Bengali Bihari Hindi Urdu Sindhi Lahnda Gujarati Marathi Kashmiri Sinhalese Old_Church_Slavonic Serbo-Croatian Bulgarian Macedonian Russian Polish Kashubian Polabian Belarusian Ukrainian Slovak Czech Sorbian_Upper Sorbian_Lower Slovenian Old_Prussian Latvian Lithuanian Old_Norse Old_Swedish Icelandic Faroese Norwegian_Riksmal Swedish Danish Old_English English Frisian Dutch Flemish Old_High_German German Luxembourgish Gothic Oscan Umbrian Latin Catalan Portuguese Spanish Sardinian_Cagliari Sardinian_Logudoro Sardinian_Nuoro Walloon French Provencal Ladin Romansh Friulian Italian Romanian Vlach Gaulish Old_Breton Middle_Breton Old_Welsh Middle_Cornish Breton Welsh Old_Irish Irish Scottish_Gaelic;
end;**

begin characters;
  dimensions nchar=4987;
  format symbols="01" missing=?;
**  charstatelabels
    1 ash_group,
    2 ash_cognate_178,**
:
:
;
matrix

simply export

begin characters;
  dimensions ntax=107 nchar=4987;
  format symbols="01" missing=?;
;
matrix

and suppress the taxa block altogether, as well as the charstatelabels entry — none of this info is used, and it is not agreeable to the BEAST NEXUS parser, so I simply edit it out when importing in BEAUti at the moment.

Remco

**Comment by PaulHeggarty** [comment]
More details on why this needs doing from my reply to Remco:  
==========================
Hi Remco,
Thanks for explaining how to get BEAUti to read in the nexus files straight:  
 
— none of this info is used, and it is not agreeable to the BEAST NEXUS parser, so I simply edit it out when importing in BEAUti at the moment.
I think better is actually export in two versions, then.  Because other uses of the nexus export files do need both of these.
*	The rest of us like to open the file in SplitsTree, too, just to get a quick view, and without the taxa block SplitsTree fails to load it.  
*	The charstatelabels are essential for us to be able to dig into the export file to work out which individual cognate sets and lexemes are or are not being successfully excluded or coded right in the export.  The charstatelabels are exactly what we need, and essential, for this sort of diagnosis task.  They were essential to Jakob and me yesterday.

So I propose that the export should do all its computing first, then export the same data-set in two versions:  one the same as now, and another for BEAUti, without the taxa block and charstatelabels.  

By the way, I’ve heard from several people that BEAUti has a bit of a reputation as being a bit of a hassle in trying to get their nexus files to open in it.  Perhaps this might be part of the problem?  So perhaps ultimately it would be worth updating it so that it can at least handle and ignore things like taxa block and charstatelabels?  I’m sure you have a long list of things like that to get round to, though!

**Comment by runjak** [comment]
I've implemented a dedicated BEAUti export in the export procedure.
This issue will be closed on deployment.

**Comment by PaulHeggarty** [comment]
The bi-dialectal export is great, Remco is very happy with the BEAUti version, but we do need one block of text that has been deleted from both dialect versions, but should be kept in the BEAUti one.

This is the 'charset' information block.

This is something that was standardly part of the export, so I hope it has just been commented out and can be reintroduced now.

**Comment by runjak** [comment]
I've adjusted the export procedure. This issue will be closed on deployment.
