### ISSUE TITLE
Nexus export zip tiny name change

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#144]
Tiny request:  nexus exports are zipped in a file named, for example:  2016-04-14.export.zip
For compatibility with other platforms, best not use . dots other than immediately before the extension .zip
So could you change the naming system to use a hyphen - rather than a dot . before 'export', e.g. 2016-04-14-export.zip

**Comment by runjak** [comment]
These file names are only from .zip files that I create on my machine.
I can aim to keep in mind that you don't like this way of naming files,
but I cannot fix anything in the code for this. Therefore I'll close this issue.
