### ISSUE TITLE
Add new fields to Clades table

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#145]
As discussed and started yesterday, 2016-04-14.

Todo added by @runjak:

- [x] Restructure table layout
- [x] Restructure database layout
- [x] Enable distribution selection and data entry
- [x] Implement date tooltips with above code
- [x] Implement rendering current distributions

**Comment by runjak** [comment]
Note for myself:
The calculation of date tooltips is supposed to work like this:
```
if(x < 2000){
  tooltip('AD '+(2000-x));
}else if(x > 2000){
  tooltip((x-2000)+' BC');
}else{
  tooltip('AD 1');
}
```

**Comment by runjak** [comment]
Todo list on this issue:

- [x] Restructure table layout
- [x] Restructure database layout
- [x] Enable distribution selection and data entry
- [ ] Implement date tooltips with above code
- [ ] Implement rendering current distributions

**Comment by PaulHeggarty** [comment]
Priority lowered a bit, since the remaining things here are less urgent than the related issue #153, to focus on first.

**Comment by runjak** [comment]
I'll use the [c3js](http://c3js.org/) library for plotting of distributions.
I'm getting to a point where I've got the parameters gathered in the right place,
and need to calculate points for the distributions so that they can be displayed.

**Comment by runjak** [comment]
@PaulHeggarty can you give me a hint for the expected date range that the distributions will land in? This would be nice to have so that I can:

* See whether they are rendered correctly.
* Figure out which points to calculate for each distribution.

**Comment by PaulHeggarty** [comment]
A bound of 10,000 BP would be enough as the maximum possible time-depth for the whole tree, so all clades will be younger than that.  Probably still worth us seeing the tails back to 10,000 BP, to check that the distribution curlonoun group before 10,000 BP.

For individual languages, the mximum time-depth is about 4500 BP.  In fact, we will need to see distribution curves for some languages too, evidently, but let's not do that for this stage.

**Comment by PaulHeggarty** [comment]
So for now, try a fixed range, for all cases, of 0 to 10,000 years BP.

**Comment by runjak** [comment]
I'm getting to a stage with the distributions where I can display something that starts to look interesting.
![screenshot_2016-08-23_16-35-12](https://cloud.githubusercontent.com/assets/5417642/17896110/aa3871ce-694f-11e6-8182-ade187aa58d3.png)
Of course this is not where we want it yet, but I think it's going in the right direction.
