### ISSUE TITLE
New exclusion system for export 

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#146]
Update on 2016-08-29 at 19h48

I’ve just realised two new boolean settings we would like on this export dialogue:

- [x] Under the selection of the meaning list, a new boolean option `Exclude meanings marked [Not for Export]`.  (Actually, the meanings reference form calls this column 'Exclude?` for now, but as discussed earlier today, it would be much less ambiguous to rename it `Not for Export`, also for consistency with how languages are handled similarly.)  The default should be set to TRUE.  The system currently does indeed currently correctly exclude these meanings, but it would be useful to be able to switch this on and off.

- [x] Likewise, under the selection of the language list, a new boolean option `Exclude languages marked [Not for Export]`.  Again, the default should be set to TRUE.  Again, the system currently does indeed currently correctly exclude these languages, but it would be useful to be able to switch this on and off.

----
Check it is working, and fixed or not by the set union/set intersection fix applied yesterday, 2016-04-14.

**Comment by runjak** [comment]
As far as I understand the current code it should already work the same for loanwords as it does for excluded terms via the `LexmeCitation` and/or `CognateCitation` entries.
Is there an additional place in the database that we added where this could come into play?
I'll make sure to look at the code again tough, just to make sure.

**Comment by runjak** [comment]
Note to myself:
At the moment exclusion of lexemes marked as not swadesh in the lexeme tables are always excluded when exporting. This is fine considering that we've always wanted to exclude them so far, but it should reflect the decision made in the export form.
![screenshot_2016-04-15_11-57-43](https://cloud.githubusercontent.com/assets/5417642/14558194/4c35948a-0301-11e6-842c-027c8d8db719.png)
For this I will need to add a simple if branch to the export procedure.

**Comment by cormacanderson** [comment]
The options for exclusion should work as follows:

Not Swadesh lexemes should be excluded by default, but there should be the option to include them (via checkbox).
* Exclude `Not Swh` - CHECKED by default  

There are three possibilities on the `1 Meaning, all Cog Sets` table which should be considered. These cognate sets should be excluded by default, but with an option to include them (via checkbox).  
* Exclude `Pll. Derivation` - CHECKED by default
* Exclude `Ideophonic` - CHECKED by default
* Exclude `Dubious` - CHECKED by default  

Loanwords should be included by default, but there should be an option to exclude them (via checkbox):  
* Exclude `Loanwords`   

If the `Loanword` checkbox is unchecked, then two further checkboxes should be visible. It should be possible to check only one of these.  
* Exclude `Parallel loan` - CHECKED by default
* Include `Parallel loan` as independent cognate sets

**Comment by CasFre** [comment]
Two short comments only:

1. Why are Pll. Deriv., Ideoph. + Dub. excluded by default, but loanwords aren't? Why isn't it the other way round? - As I take it, loanwords are those that are definitely not inherited and thus give us a different kind of information than the normal cognate sets, while this is only possibly the case with the other three categories (or at least Pll. Deriv. and Dub.).
2. @m-scarborough, @RolandPooth, @ulrichgeupel are wondering whether it might be good to have a "possible loan"-button...
2.

**Comment by cormacanderson** [comment]
Loanwords aren't excluded because we have changed the loanword system. `Loan event` cognate sets are valid sets, just like any other, so are included by default (with, of course, an option to exclude). The other fields signal dubious or possibly unreliable sets, which should be excluded by default (although they can be included if people want to).

**Comment by runjak** [comment]
Please verify that these assumptions are correct:

* Given that the `Loanword` checkbox for loanword event cognate sets is checked, we want the export to exclude all cognate sets that are marked as `Loan Event`.
  * But we should not exclude lexemes on this basis for the chance that they may belong to other cognate sets.
  * In this case we will ignore the `Include/Exclude Pll. loans` checkboxes and have them disabled anyway.
* Given that the `Loanword` checkbox isn't checked: we allow either the `Exlude` or the `Include` Pll. loans checkbox or none of these two to be checked, but not both.
* Iff `Exclude Pll. loans` is checked we will ignore all cognate sets marked as `Pll. Loan`.
* Iff `Include Pll. loans` is checked we will have a feature at one point to have some kind of independent cognate sets.

For completion here is a nice drawing I got:
![20160825_094411](https://cloud.githubusercontent.com/assets/5417642/17968870/6a40817a-6acf-11e6-9a0c-bde11b956591.png)

**Comment by cormacanderson** [comment]
I can verify that those assumptions are correct, except for the line "But we should not exclude lexemes on this basis for the chance that they may belong to other cognate sets". This is so unlikely that I would be surprised if there are any cases in the database. The lexemes in `Loan event` cognate sets should be omitted.

**Comment by runjak** [comment]
Alright - I think I'm nearly done with this on the server side.
Afterwards I'll make sure enabling/disabling inputs works correctly on the client side.

**Comment by runjak** [comment]
This is what my current form looks like:
![screenshot_2016-08-25_16-30-50](https://cloud.githubusercontent.com/assets/5417642/17973078/536ecb16-6ae1-11e6-81bc-d7889bb02500.png)

The style is not very beautiful, but I would need some more time to adjust this, and will rather make sure to get the lexeme handling correct and test the export procedure.

**Comment by PaulHeggarty** [comment]
It looks OK, except that the default for ascertainment bias correction should be set to true (we think we recall!).

**Comment by runjak** [comment]
Except for the `Include Pll. loans` setting I've implemented the other settings.
If I'm not mistaken you should now be able to start exporting data via the `/nexus/` url.

It may be a good idea to double check the exports to ensure that they look sane.

**Comment by PaulHeggarty** [comment]
I’ve tried to do an export with everything just as it was preset, but after 48 minutes it tells me that the server is still computing export 1, also if I refresh.

**Comment by runjak** [comment]
@PaulHeggarty I've fixed this just now - and http://www.cobl.info/nexus/export/ should list the export correctly now.

**Comment by runjak** [comment]
I've got some code for the additional export options that I will deploy after some polishing and testing.
