### ISSUE TITLE
Adapt all source citations into a proper bibliographic reference system, e.g.. Zotero

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#148]

**Comment by runjak** [comment]
Looking at the way the various clld apps store sources, @nitsnatsnok, @khoidt and me found a table definition on [GitHub](https://github.com/clld/clld/blob/master/clld/db/models/source.py).

**Comment by khoidt** [comment]
The data structure and import are ready for now. The issue will be closed as soon as import is implemented.

**Comment by nitsnatsnok** [comment]
@khoidt Is this already implemented? If so, please close this issue.

**Comment by khoidt** [comment]
[Last update](https://github.com/lingdb/CoBL/issues/344#issuecomment-263176509) implements COinS metadata for `Source` (collectable by Zotero, Citavi etc.). I believe that after deployment and testing this issue can be closed.
