### ISSUE TITLE
Branch Filtering - Romani Greece

### ISSUE THREAD

**Issue by m-scarborough** [lingdb/CoBL#156]
Small, easily correctable issue: I just noticed that Romani Greece filters with the Greek languages in the branch filter toggle.  It should filter with the Indic languages.

**Comment by runjak** [comment]
The branch filtering system is currently changing in quite large parts.
Mostly because of #153. I'll have a look at this again once the big changes are over.

**Comment by PaulHeggarty** [comment]
This is not a programme bug, it was just a data error.  Romani Greece was assigned to the wrong branch level (5 not 8).  I’ve just fixed that in the languages table, and it now works.  
Thanks for spotting this, a gross error of attention some time back!
