### ISSUE TITLE
In 1 Lg view, enable filtering lexemes by meaning count

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#159]
It should perhaps be a three-way toggle filter like others currently, although it would have to be a separate button because it's not associated uniquely to any single column/field.  The three states, for a language that has, for the 200 meaning list, six meanings with two entries and three with three entries, would thus give: 
- off, no filtering   212 lexeme entries 
     = (200-6-3) + (6x2) + (3x3)
- filter to only meanings for which this language has more than one lexeme entry 
     = 21 lexeme entries (= (6x2) + (3x3)
- filter to only meanings for which this language has just a single lexeme entry 
     = 191 lexeme entries (= 200-6-3)

-----

Todo for this issue:

- [x] Implement filtering described above
- [x] Add `check` functionality requested by @cormacanderson 
- [x] Add `check` buttons to language reference table.
- [x] Let described filtering depend on "Not Swh" setting
- [x] Build option to sort lexeme entries by the number of occurences of their meanings and alphabetical in that.

**Comment by runjak** [comment]
I've got an implementation for the check button.
Clicking it opens a dialog that lists meanings from the current meaninglist that have a number of lexemes different than 1:
![screenshot_2016-07-04_13-18-06](https://cloud.githubusercontent.com/assets/5417642/16559014/18cc796a-41ea-11e6-91e4-bd221645bc5d.png)

**Comment by cormacanderson** [comment]
That looks great Jakob. Might it be possible to add it as a small button also on the languages references list, to the right of the statisics? Or is that likely to be time-consuming?

**Comment by runjak** [comment]
It shouldn't be too much trouble to add this in the reference table as well.
I'm currently deploying the version without this tweak.
Afterwards I'll add the additional check buttons and look at implementing the requested filter.

**Comment by runjak** [comment]
I've added an implementation of the requested filter:
![screenshot_2016-07-04_15-12-52](https://cloud.githubusercontent.com/assets/5417642/16561592/43b111c6-41fa-11e6-8891-27f82c214034.png)
![screenshot_2016-07-04_15-13-04](https://cloud.githubusercontent.com/assets/5417642/16561593/43b2078e-41fa-11e6-852c-d26413e075bc.png)
![screenshot_2016-07-04_15-13-15](https://cloud.githubusercontent.com/assets/5417642/16561594/43b25702-41fa-11e6-810f-0f99b801f720.png)

The requested check buttons are also available in the language reference table:
![screenshot_2016-07-04_15-17-09](https://cloud.githubusercontent.com/assets/5417642/16561619/649c95b8-41fa-11e6-9714-4db5313d69ad.png)

This issue will be closed automagically after deployment.

**Comment by cormacanderson** [comment]
This works well, but I am going to reopen this issue to request two extensions.
Firstly, the count of meanings does not take into consideration the fact that some meanings may be excluded. If possible, could the meanings total reflect rather the number of meanings that are NOT marked as "Not Swh". This will enable us to see properly whether, and to what extent, this language has a butterfly problem, and for which meanings.
Secondly, would it be possible to sort the meanings not simply alphabetically, but to sort first those with 0, then those with 2, 3, etc.

**Comment by runjak** [comment]
I understand that you want the meanings to be sorted in this order of their number of lexemes only as an option instead of in general. Is that correct?

**Comment by runjak** [comment]
I'll let the new filter consider only the rows that are currently displayed.
That way:
* If "Not Swh" are excluded - they are not considered for the meaning count
* If "Not Swh" is displayed - entries with it will be considered for the meaning count

**Comment by runjak** [comment]
Oh - because it needs clarification:
@cormacanderson are you talking about sorting the lexemes in the table by the occurrence count of their meanings or about the meanings in the report displayed when clicking `check`?

**Comment by cormacanderson** [comment]
Yes, that is perfect re the "Not Swh" - it means we can check either as desired. For the check box in the languages references table it would be useful to have the option of both too, but if that is a problem, then better to have the figures WITHOUT the excluded lexemes (i.e. those marked "Not Swh" - this is, after all, the default).
Re the sorting, I meant in the report displayed when clicking `check`, i.e. that it shows all of the meanings with 0 entries first, then all those with 2 entries, then all those with 3, etc.

**Comment by runjak** [comment]
The `check` report will now be sorted by counts in ascending order and will exclude lexemes that are marked as `Not Swh`. This issue will be closed automagically after deployment.
