### ISSUE TITLE
Implement splitting cognate classes

### ISSUE THREAD

**Issue by runjak** [lingdb/CoBL#162]
When viewing the lexemes in a single cogate class it must be possible to select a subset
of lexemes that shall be split off into a new cognate class.
This issue encompasses these tasks:

- [x]  Implement a way of splitting cognate classes as described.
- [x] Add a `Loan Source Cognate Set Id` column to the cognate class list that allows to specify how cognate sets relate.
- [x] Add `Loan event time depth BP` column to the cognate class list as well.
- [x] Add `Form in loan source language` column to the cognate class list.
- [x] Improve splitting/presentation performance.

**Comment by runjak** [comment]
This relates to #39.

**Comment by runjak** [comment]
The `cognate_report.html` template lists a number of cognate judgments which connect a cognate class with several lexemes. To implement the split functionality, I'll do the following:

* Make it possible to select a set of cognate judgments listed in the cognate report by converting the table into a form that allows this selection.
* When the form is sent to the server and some judgments are checked to be split of:
  * Create a new cognate class
  * Transfer the selected judgements to refer to the new cognate class instead of the old
  * Return to the table view, but report the split-off in a message so that the user can easily find the newly created cc.

**Comment by runjak** [comment]
I have a basic implementation of the splitting functionality now, but it's horribly slow
because it does loads more requests to the database than it needs to.
I'll optimize this to get a sane load time, and will afterwards consider this issue done.

**Comment by runjak** [comment]
It appears that the main problem here is in the [lexicon/models.py:update_cognateclass_list_all(…)](https://github.com/lingdb/CoBL/blob/3c08609693ca49ab3d9bc5a6f9b45e69d9d51a5f/ielex/lexicon/models.py#L1667-L1696) function, which causes something like ~5000 selects and inserts. I think it should be possible for me to reduce the number of queries by fetching related objects as a bunch instead of individually changing them.
![screenshot_2016-05-06_15-36-56](https://cloud.githubusercontent.com/assets/5417642/15074746/e3eb3d34-13a0-11e6-94fa-d3a56f4a6f23.png)

**Comment by runjak** [comment]
@CasFre when viewing a single cognate class like this:
![screenshot_2016-05-09_12-42-49](https://cloud.githubusercontent.com/assets/5417642/15110844/96f29e6a-15e3-11e6-95d6-83f9f9fb04f7.png)
it will now be possible to select entries using the checkboxes in the `split` column that should be put in it's own, separate cognate class. You will be able to save this as usual using the `Save` button to submit your changes. This feature will soon be available on the server (when I've done the next update).

**Comment by m-scarborough** [comment]
Might I just say, this new cognate splitting function is amazing.

Best,

Matthew

On 2016-05-09 11:44, Jakob Runge wrote:
> @CasFre [1] when viewing a single cognate class like this:
>  [2]
>  it will now be possible to select entries using the checkboxes in the
> split column that should be put in it's own, separate cognate class.
> You will be able to save this as usual using the Save button to submit
> your changes. This feature will soon be available on the server (when
> I've done the next update).
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub [3]
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/CasFre
> [2]
> https://cloud.githubusercontent.com/assets/5417642/15110844/96f29e6a-15e3-11e6-95d6-83f9f9fb04f7.png
> [3] https://github.com/lingdb/CoBL/issues/162#issuecomment-217832749

-- 
M. J. C. Scarborough
Ph.D. Candidate, Faculty of Classics
University of Cambridge

Research Associate in Comparative Indo-European Linguistics
Max-Planck-Institut für Menschheitsgeschichte
Abteilung Sprach- und Kulturevolution

Քանի լեզու գիտես, այնքան մարդ ես։
"Soviele Sprachen du sprichst, soviele Menschen du bist."
