### ISSUE TITLE
Statistics for cognate sets

### ISSUE THREAD

**Issue by runjak** [lingdb/CoBL#163]
Part of this will go to the meanings table, part of it to the cognate sets table.
Information that needs to be gathered is:

**For the cognate sets table:**

- [x] Count of entries per cognate set
- [x] How many of these entries are loan words?
- [x] Percentage `loan word entries` / `entries total`
- [x] Let counts be aware of the current language list

**For the meanings table:**

- [x] How many of the cognate sets have a root form?
- [x] How many of the cognate sets have a root language?
- [x] Percentages of above counts over total number of cognate sets.

**Comment by CasFre** [comment]
As our new student assistant will start working these days and will also need these statistics, I upgrade this issue to 0th priority.

**Comment by runjak** [comment]
While I've now written code that displays some of the requested counts, I also found a potential problem with my current approach:
![screenshot_2016-05-12_15-22-52](https://cloud.githubusercontent.com/assets/5417642/15215993/6bc37470-1855-11e6-8de1-b8de90b62291.png)
For the Cognate Class `J` a `Lex Count` of `4` is displayed, but when viewing the report for that single Cognate Class only `3` entries are displayed.
![screenshot_2016-05-12_15-23-26](https://cloud.githubusercontent.com/assets/5417642/15216024/886389f8-1855-11e6-9dc8-33a69ca63fac.png)
I guess that this is because of the view for a single class only displaying entries for the current language list whereas the count considers all lexemes.

**Comment by runjak** [comment]
Filtering the meaning table for the above cognate class yields this list:
![screenshot_2016-05-12_15-25-10](https://cloud.githubusercontent.com/assets/5417642/15216059/c6d76286-1855-11e6-8379-64d9ead56748.png)
I think the issue here is that `Khaskura` is not displayed in the list for a single cognate class, or that it is considered for the count at all while not being relevant to it in the first place.

**Comment by cormacanderson** [comment]
Is that issue not = https://github.com/lingdb/CoBL/issues/62?

**Comment by runjak** [comment]
This is a different table but a similar problem.
It's about the cognate table and the language list
instead of the language table and the meaning list.
That said I think I can infer from #62 what the expected outcome for the statistics would be:
The counts should reflect the current lists and not assume that all data is to be considered. Counts for all entries can still be displayed then by choosing the `all` lists.

**Comment by runjak** [comment]
I've solved making the counts for cognate classes depend on the current language list,
and am confident that I can replicate this solution for the other, similar cases.

**Comment by PaulHeggarty** [comment]
Excellent, because it's one of the main issues outstanding for those other cases, too!  Good stuff.

**Comment by PaulHeggarty** [comment]
Would the code just worked out to get some of these statistics working not also help solve the long-running problem with #112?  Also presumably related to #154 and #180?  A block of priority 0 issues that it might be logical to try to fix together?

**Comment by runjak** [comment]
No, sadly not directly the same thing.

* The clade lookup for #112 is I think possible but a different issue than trying to figure out some counts in a time efficient manner.
* The clade filter for #154 will essentially need to be redone and is a script running in the browser rather than on the server.
* I currently assume the problem in #180 to be due to problems in updating the clades a language belongs to. This isn't easily fixable because the structure of the clades table doesn't help with it but instead makes it hard to do this.

**Comment by runjak** [comment]
I have an implementation for the statistics on the meanings table.
It looks like this:
![screenshot_2016-05-17_15-59-09](https://cloud.githubusercontent.com/assets/5417642/15324831/5ed86594-1c48-11e6-81a2-3701f1052d3b.png)
I'll close this issue once the according portion of code is deployed.

**Comment by runjak** [comment]
The required statistics are now available online.

**Comment by PaulHeggarty** [comment]
The sorting does not work properly.  It seems to be only working on the integer part.  Look at how all the 99.x figures come together, but not ordered correctly by the .x part.  Likewise the 98.x entries, and so on.
![screenshot - 20_05_2016 08_09_33](https://cloud.githubusercontent.com/assets/8819910/15418805/3376401c-1e62-11e6-92aa-3f0c63acf3a1.png)

**Comment by PaulHeggarty** [comment]
This is particularly bad for root form % figures, which in fact seem to be not percentages, but normalised between 1 and 0.  So they need multiplying by 100 in any case, but you can see that the ordering doesn’t work at all other than for grouping all 1s together.  All figures 0.xx are randomly ordered, no sorting because the sorting only works for the integer, nothing after the decimal point. 
![screenshot - 20_05_2016 08_13_23](https://cloud.githubusercontent.com/assets/8819910/15418894/cc83ec0a-1e62-11e6-9627-6c0047b04ae4.png)

**Comment by PaulHeggarty** [comment]
Perhaps this is a general setting that applies to any sorts in any table wherever figures are expressed including decimal points.  Please check this too.  A general fix would be nicer and more efficient, of course!

**Comment by runjak** [comment]
Yes, I think that the issue here is the part of the JavaScript code that parses the number strings into numbers - it currently produces integer values rather than doubles.
Changing this should fix the sorting here and elsewhere.
