### ISSUE TITLE
Search the database for Cormac

### ISSUE THREAD

**Issue by runjak** [lingdb/CoBL#167]
@cormacanderson could use a list of all lexemes that are marked as loanwords in the lexical judgement.

**Comment by runjak** [comment]
Table of lexemes I've found that apparently are marked as loanwords in their lexical judgements:

language | meaning
------------- | ------------
Afrikaans | feather
Albanian | child
Albanian | come
Albanian_Corinth | all
Albanian_Corinth | come
Albanian_Corinth | dog
Albanian_Corinth | dust
Albanian_Corinth | feather
Albanian_Corinth | foot
Albanian_Corinth | liver
Albanian_Corinth | man
Albanian_Corinth | many
Albanian_Corinth | mouth
Albanian_Corinth | narrow
Albanian_Corinth | not
Albanian_Corinth | road
Albanian_Corinth | swim
Albanian_Corinth | think
Albanian | dog
Albanian | far
Albanian | fat
Albanian | feather
Albanian | fly_V
Albanian | foot
Albanian_Gheg | child
Albanian_Gheg | come
Albanian_Gheg | dog
Albanian_Gheg | far
Albanian_Gheg | fat
Albanian_Gheg | feather
Albanian_Gheg | fly_V
Albanian_Gheg | foot
Albanian_Gheg | green
Albanian_Gheg | hair
Albanian_Gheg | hair
Albanian_Gheg | man
Albanian_Gheg | many
Albanian_Gheg | mouth
Albanian_Gheg | road
Albanian_Gheg | sand
Albanian_Gheg | swim
Albanian_Gheg | walk
Albanian | green
Albanian | hair
Albanian | many
Albanian | mouth
Albanian | right
Albanian | road
Albanian | rope
Albanian | sand
Albanian_Sicily | child
Albanian_Sicily | come
Albanian_Sicily | dog
Albanian_Sicily | feather
Albanian_Sicily | fly_V
Albanian_Sicily | foot
Albanian_Sicily | liver
Albanian_Sicily | man
Albanian_Sicily | many
Albanian_Sicily | mouth
Albanian_Sicily | right
Albanian_Sicily | road
Albanian_Sicily | sand
Albanian_Sicily | swim
Albanian_Sicily | think
Albanian_Standard | dirty
Albanian_Standard | stab
Albanian_Standard | thick
Albanian | swim
Albanian_Tosk | child
Albanian_Tosk | come
Albanian_Tosk | dog
Albanian_Tosk | dog
Albanian_Tosk | far
Albanian_Tosk | feather
Albanian_Tosk | fly_V
Albanian_Tosk | foot
Albanian_Tosk | green
Albanian_Tosk | hair
Albanian_Tosk | head
Albanian_Tosk | man
Albanian_Tosk | man
Albanian_Tosk | many
Albanian_Tosk | mouth
Albanian_Tosk | not
Albanian_Tosk | road
Albanian_Tosk | round
Albanian_Tosk | sand
Albanian_Tosk | swim
Albanian_Tosk | true
Albanian_Tosk | walk
Albanian | true
Armenian_Eastern | fat
Armenian_Eastern | fire
Armenian_Eastern | many
Armenian_Eastern | skin
Armenian_Eastern | white
Bengali | road
Bihari | man
Bihari | road
Breton | because
Breton | husband
Breton | ice
Classical_Armenian | fat
Classical_Armenian | fire
Classical_Armenian | many
Classical_Armenian | stick
Classical_Armenian | white
English | count
English | die
English | dig
English | dirty
English | egg
English | fruit
English | lake
English | leg
English | root
English | rotten
English | round
French_Creole_Dominica | float
French | float
Friulian | chest
Gujarati | road
Hindi | man
Hindi | road
Kashmiri | hunt
Ladin | back
Lahnda | man
Latin | stone
Marathi | bird
Marathi | road
Marwari | man
Middle_Breton | because
Middle_Cornish | animal
Old_English | road
Old_Irish | feather
Old_Irish | stick
Oriya | breathe
Parthian | mountain
Persian | man
Persian | person
Portuguese | float
Provencal | bark
Provencal | float
Punjabi | man
Romani_Greece | ash
Romani_Greece | road
Romani_Greece | rotten
Romani_Greece | sky
Romansh | float
Scottish_Gaelic | water
Scottish_Gaelic | worm
Spanish | float
Sranan | know
Sranan | river
Tajik | person
Urdu | man
Urdu | road
Vasi-vari | hair
Vasi-vari | tree
Walloon | float
ZLegacy_Albanian_T | bark
ZLegacy_Albanian_T | chest
ZLegacy_Albanian_T | child
ZLegacy_Albanian_T | come
ZLegacy_Albanian_T | come
ZLegacy_Albanian_T | dog
ZLegacy_Albanian_T | earth
ZLegacy_Albanian_T | far
ZLegacy_Albanian_T | fat
ZLegacy_Albanian_T | feather
ZLegacy_Albanian_T | fish
ZLegacy_Albanian_T | fly_V
ZLegacy_Albanian_T | foot
ZLegacy_Albanian_T | green
ZLegacy_Albanian_T | hair
ZLegacy_Albanian_T | head
ZLegacy_Albanian_T | hear
ZLegacy_Albanian_T | man
ZLegacy_Albanian_T | man
ZLegacy_Albanian_T | many
ZLegacy_Albanian_T | mouth
ZLegacy_Albanian_T | road
ZLegacy_Albanian_T | round
ZLegacy_Albanian_T | sand
ZLegacy_Albanian_T | swim
ZLegacy_Albanian_T | true
ZLegacy_Albanian_T | walk
ZLegacy_Albanian_T | woman
ZLegacy_Albanian_T | yellow
ZLegacy_Breton_Se | belly
ZLegacy_Breton_ST | belly
ZLegacy_French_Creole_C | float
ZLegacy_Serbian | rope
ZLegacy_Serbocroatian | rope

**Comment by runjak** [comment]
Since this issue was essentially about delivering the above list, I'll close it now.

**Comment by cormacanderson** [comment]
Thanks for that @runjak. I have gone through in an attempt to eliminate all of these, but one or two might have slipped through the net. Could you run the search again to see if I got them all?

**Comment by runjak** [comment]
Sure thing - this shouldn't be too hard for me to do :)

**Comment by runjak** [comment]
Ok, this is what I could find:

language | meaning
-------- | -------
Albanian_Standard | stab
Albanian | many
Albanian | road
Albanian | rope
ZLegacy_Albanian_T | fish
ZLegacy_Albanian_T | foot
ZLegacy_Albanian_T | green
ZLegacy_Albanian_T | man
ZLegacy_Albanian_T | yellow

**Comment by cormacanderson** [comment]
Great, thanks. These have now all been eliminated, so we should be clear.
