### ISSUE TITLE
Enter correct Clade level values for all languages, for the new clade system

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#171]
In the languages reference table.
Use the hover tooltips to check assignment is correct.

**Comment by cormacanderson** [comment]
Done, although deciding on the ordering for Indic, Iranic, Romance and Germanic was not straightforward. I generally followed an East to West and South to North orientation. I also did the legacy lists, as we can sort them to the bottom alphabetically already (all being named ZLegacy_...).

**Comment by PaulHeggarty** [comment]
Hi

Thanks for this.  Great to see that the order also already works.  Call me
German, but putting some more order and logic into this is another thing
I've wanted to see ever since I first set eyes on IELex.  Actually, it's not
really German, it's about practicality too, because the more people can
patently see the logic, the more they'll remember where things are, and see
patterns more visibly.  Hopefully another incremental gain in the fight for
efficiency, consistency and quality control.

Next up, I suggest for tomorrow in the car a discussion on tweaking language
names like Old_Cornish:  perhaps a new approach like Cornish: Old?  Maybe a
personal thing, though.  

But we do now have fields for 'user friendly' and 'BEAST-friendly' names, so
we can certainly make some cosmetic and consistency improvements.

Onwards, onwards!

   Paul

 

 

 

 

 

  _____
