### ISSUE TITLE
Mismatch in display of cognacy coding with German 'Kralle'

### ISSUE THREAD

**Issue by CasFre** [lingdb/CoBL#178]
In order to show Konstantin how cognate classes are assigned to individual lexemes, I used German 'Kralle' as a test case, once assigning it to a new cognate class (D), and once to an already existing class (G).
Now, it seems that the field "nCog" does not work correctly either in the 1lang - all mean table, nor in the 1mean - all lang table.
![german_kralle_1lang - all mean](https://cloud.githubusercontent.com/assets/17431124/15211331/efa8094c-183a-11e6-9e5d-c879376d4869.jpg)

![german_kralle_1mean-all lang](https://cloud.githubusercontent.com/assets/17431124/15211338/f8140c0c-183a-11e6-80f0-998466904c8b.jpg)

**Comment by runjak** [comment]
Thanks for reporting this.
I could reproduce this and think that I found the offending portion of code.

The `nCog` field traces back to the [number_cognate_coded](https://github.com/lingdb/CoBL/blob/e1bd001115eb851d7cc9632847ab5ea7e75a4098/ielex/lexicon/models.py#L892) field in the Language model.
In contrast to other statistics this field doesn't appear to be calculated when required but instead to have been updated in the past more or less automagically. It's possible that this automatic was broken at some point, so I'll aim to replace it with on the fly calculations which are more robust but a bit more costly in terms of site loading times.
