### ISSUE TITLE
Individual lexemes pages unavailable

### ISSUE THREAD

**Issue by CasFre** [lingdb/CoBL#181]
I could not access individual lexemes pages from the German language list, neither this morning nor just now. I tried with about ten different lexemes, but always got the "page unavailable" notification.

**Comment by CasFre** [comment]
I also tried now with Ancient Greek, clicking on the magnifier glass next to μέγας for [big] and ἰχθῦς for [fish]; and with Kashmiri SUR for [ash] and SORSHUN for [wash].
@runjak, @nitsnatsnok might that have something to do with the setting that we've changed yesterday for my laptop in order to stop it from showing that script time-out notification?
Do others have that problem as well?

**Comment by CasFre** [comment]
Ha, actually, it can't be related to that, because I used the computer at the Lehrstuhl für Indogermanistik this morning, not my laptop!

**Comment by nitsnatsnok** [comment]
I'm also experiencing this not only for German lexemes, but for all lexemes in all lists in general.

**Comment by m-scarborough** [comment]
Likewise, I'm having the same problem.

**Comment by nitsnatsnok** [comment]
This seems to affect cognate class pages as well!

**Comment by runjak** [comment]
Sorry for the delay in responding to this.
I've been a bit unavailable over the weekend,
but am aiming to get this fixed asap today.

**Comment by runjak** [comment]
I have a fix for this on my machine and will have it deployed soon.
The nature of this problem is similar to #173.

**Comment by runjak** [comment]
OK - pages like http://www.cobl.info/lexeme/23793/ should be working for you again.
Please reopen this issue if the problem appears not to be fixed.
