### ISSUE TITLE
Source citation style

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#183]
http://cobl.info/sources/ lists all cited sources, but as they are given in a single text field, they are very inconsistent in citation styles, the given information and its order, cf.:
- Adams, Douglas Q. 1999. A Dictionary and Thesaurus of Tocharian A. Amsterdam - Atlanta: Rodopi.
- De Blois, François. The Name of the Black Sea, in M. Macuch, M. Maggi, and W. Sundermann (eds.), Iranian Languages and Texts from Iran and Turan: Ronald E. Emmerick Memorial Volume, pp. 1-8. Wiesbaden: Harassowitz.
- Eichner, H. (1985) 'Malwa, eine hieroglyphenluwisch-sidetische Wortgleichung', MSS 45: 5-21.
- Klein , E. (1986) "A Comprehensive Etymological Dictionary of the English Language". Amsterdam: Elsevier.

Is there a citation style which is normally used at MPI? Should I go though the sources list and adapt all of them to this style?

**Comment by cormacanderson** [comment]
We do need to sort this out and set up a proper bibliography which can be picked up by Zotero etc. https://github.com/lingdb/CoBL/issues/148. However, this should go hand in hand with a system for more easily entering references for individual lexemes or cognates https://github.com/lingdb/CoBL/issues/166. It's currently very cumbersome to do this. So, yes we have to standardise, but, no, maybe don't start to amend them by hand, at least not just yet.

**Comment by nitsnatsnok** [comment]
I'd like to discuss the citation styles used in the new bibliography system (see #306) here. There are three different occurences of source entries on the website:

1. in the headline of the citation (which can be empty) itself, these occur on the lexeme as well as on the cognate class pages
1. in a desired short form in the sources list
1. in the complete form after clicking on the short form in the sources list

Until now we never talked about the **first** one directly, which is the most important though: This is the form one will see when browsing the database. I think this should be a short but clear link to the source, preferable understandable even without consulting the sources list – the author/editor-year- or shorthand-style respectively seems very suitable to me, e.g.

short form | stands for
---|---
Matasović 2009, 1|M., Ranko: Etymological Dictionary of Proto-Celtic, 2009, p. 1
Adams 1999a, 1|A., Douglas Q.: Dictionary of Tocharian B, 1999, p. 1
Adams 1999b, 1|some other source from the same author and year
EWA II, 1|Lloyd, Albert L. et al.: Etymologisches Wörterbuch des Althochdeutschen vol. II, 1998, p. 1
LIV², 1|Rix, Helmut: Lexikon der Indogermanischen Verben, 2001

For the **second** one we decided to use the author-year-style. Of course it would be only consistent to have the exact same style used as in the first one.

The **third** one should give the whole bibliographical information of the entry in a common style, e.g. [the Harvard style](https://en.wikipedia.org/wiki/Parenthetical_referencing#How_to_cite). I would prefer having it in a single line of text, which then can be easily copied (in addition to the BibTeX/Zotero export).

What do you think about this?

**Comment by khoidt** [comment]
I'm not sure I could contribute much to the discussion of the citation styles themselves. The system @nitsnatsnok suggests seems to me, however, very reasonable. What is really important on my side is to have the styles as proper `.bst` files.

**Comment by nitsnatsnok** [comment]
Many styles can be found on [CTAN](https://www.ctan.org), the Harvard style mostly preferred should be in [here](https://www.ctan.org/tex-archive/macros/latex/contrib/harvard).

**Comment by nitsnatsnok** [comment]
As the citation system is dealt with in #306 and #344 I'm closing this issue.
