### ISSUE TITLE
Unexpected homepage style

### ISSUE THREAD

**Issue by runjak** [lingdb/CoBL#185]
@PaulHeggarty it appears that the `About page: Home` in the wiki pages was updated to introduce a horizontal rule before the pictures. It appears that the current markdown presentation on the website doesn't pick up on this and interprets it as changing the paragraph above the `-----` into a headline instead.

Here are two screenshots of the situation in both the wiki and on the site:
![screenshot_2016-05-17_11-54-08](https://cloud.githubusercontent.com/assets/5417642/15318468/68eed2ce-1c26-11e6-9418-f30519360019.png)
![screenshot_2016-05-17_11-53-59](https://cloud.githubusercontent.com/assets/5417642/15318469/68f2a304-1c26-11e6-8a39-8e8c4ea552a0.png)

Possible fixes are:

* Removing the `-----` from the wiki page again. This would be easy to do and resolve the problem fast.
* Trying to adjust our markdown interpreter to closer match the one GitHub has or looking into other ways to get the same/similar html structure.

**Comment by runjak** [comment]
I see that this situation has been reverted and am closing this issue to reflect the change.

**Comment by PaulHeggarty** [comment]
Yes, but the aim was to stop the portrait photos appearing immediately after the preceding text without a line break.  At the moment the images mess up the line spacing of the preceding paragraph.  There really does need to be a line break (or two) there, but I can’t work out how to do it.  Please fix this if you know how.

**Comment by runjak** [comment]
This issue is now taken care of in #189.
