### ISSUE TITLE
Language reference data:  editable names and required fields 

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#186]
Todo generated from below discussion:
- [x] Remove unused `beastName` field from language
- [x] Make single language form usable without requiring all fields
- [x] Introduce `ascii_name` field to the languages table as `Beast name`
- [x] Make `utf8_name` field editable in the languages table as `Display name`
- [x] Check to make sure `utf8_name` is used over `ascii_name` for displaying language names everywhere

-----

Language names should be editable directly from the Languages Reference table (at least for people with full editor rights).

Currently, one can in theory edit them by clicking on the magnifying glass icon, but that leads to a page where many fields are demanded as required fields, when they should not be:  see image below.

Language names with spaces are also not allowed (see also below), but the whole point of the new field BeastName is to be able to have BeastNames as the spaceless, underscore versions that are used in exports and URLs (e.g. for 1 language view), but also allow a more normal looking name on the actual database pages.

![screenshot - 17_05_2016 14_43_30](https://cloud.githubusercontent.com/assets/8819910/15322589/005bbdb8-1c3e-11e6-8bd9-88e2fad64aae.png)

**Comment by runjak** [comment]
There is currently a constraint on language names that makes sure that language names may only contain the symbols `a…z,A…Z,0…9,-_`.
This is code by Michael, and the motivation here was to have one name, the `ascii_name` entry of a language, that can always be part of URLs without further encoding.
There is an additional field, the `utf8_name`, which allows everything up to `128` symbols, but isn't used throughout most parts of the page. See [models.py](https://github.com/lingdb/CoBL/blob/master/ielex/lexicon/models.py#L339-L341) for technical details.
I would suggest using the `ascii_name` as the beast name where possible and making more use of the `utf8_name`. This would have the upside of delivering the same functionality as was expected of the beast name while requiring less adjustments.

**Comment by PaulHeggarty** [comment]
In this case, yes let's use the `ascii_name` as our `Beast Name`.  And let's use the `utf8_name` as our `Display Name`.  You can keep the original names for those fields, but please actually put my preferred names as the column headers for them.
We also need both of them to be editable in the Languages Reference table itself.
This should mean that all the current names showing on that table should actually appear under `Beast Name`.  For now you could copy all these into the field for `Display Name` too, and then we'll edit them as we wish.

**Comment by PaulHeggarty** [comment]
Another related issue/bug is that the clade labels are only working for level Cl 0, not for Cl 1 to 3, even though there is column space assigned for them.  Perhaps a problem with the search for 'abbreviations' rather than just the label itself?
But in any case, the system seems erratic.  Note how Shugni is given as Iranic in level 0, but that should be level 1 after Indo-Iranic in level 0.  Indeed, all entries that are level 6-3 should appear as Indo-Iranic then Iranic, but only Shugni does.  Some bug in the lookup.
![screenshot - 19_05_2016 15_49_22](https://cloud.githubusercontent.com/assets/8819910/15395997/63654350-1dda-11e6-8f3a-4b2f045b6ffa.png)

**Comment by runjak** [comment]
Can we have a separate issue for the clade situation?
The lookup system for clades has different shortcomings, some of them likely stemming from the fact that I currently cannot figure out the language-clade relations in a useful manner when clades are changed as opposed to languages, others stemming from the fact that I still need to essentially redo the clade filter on the client side.
But all of this has nothing to do with the language names.

**Comment by runjak** [comment]
I've implemented the todo points for this issue and will deploy them soon.

**Comment by PaulHeggarty** [comment]
Misunderstandings here.  We now have *three* fields in the http://www.cobl.info/language/Mycenaean_Greek/edit/ page.  
`Ascii name`
`Utf8 name`
`BeastName`
We should only have two.  Basically, Ascii and Utf8 can be kept as the system names, but they won’t mean much reliably to many people.  As header labels for them we should change them:
`Ascii name` should be labelled as `URL Name`   (= Beast Name, but a better term more people will get)
`Utf8 name` should be labelled as `Display Name`
Both fields should be editable.  The Ascii name should retain the same restrictions as currently.  It just needs to be called `URL Name`.
Also, they both need to be editable directly in the languages reference table itself, not just when clicking on the magnifying glass link.  That is, `Display Name` needs to be an editable field, not an underlined link that goes straight to the corresponding 1 Language all meanings view for that language.  We should retain that function, but as a separate link icon immediately in front of the language name, not as the name itself (I constantly annoy myself by clicking on language names and expecting to be able to edit the language's reference data, and getting the lexeme list instead, so I'd like this changed).  So I'll now write out the list of points to fix still.

**Comment by PaulHeggarty** [comment]
In the Languages Reference table:
- [ ]  remove link from the language name (use code for next point instead). 
- [ ]  make the link a link icon instead, immediately before the language Name.  
- [ ]  make the language Name field editable.
- [ ]  change the label from `Name` to `Display Name`.  
- [ ]  change the label from `BeastName` to `URL Name`.  

In the one language reference data editing form:
e.g. http://www.cobl.info/language/Mycenaean_Greek/edit/
- [ ]  change the label from `Ascii Name` to `URL Name`.  
- [ ]  change the label from `Utf8 Name` to `Display Name`.  
- [ ]  delete the label and field `BeastName`.

**Comment by runjak** [comment]
The todo lists are only displayed as progress bars in the issue list if the list is in the topmost entry of the individual issue.
Please compare the current checkboxes to the [changes](http://www.cobl.info/languagelist/2016-04-18_129/) I've just deployed a minute ago:
![screenshot_2016-05-26_10-11-16](https://cloud.githubusercontent.com/assets/5417642/15568072/404d5a42-232a-11e6-8a70-8803aa7d2f62.png)

**Comment by runjak** [comment]
The main difference I'm spotting is that I've currently labeled the fields `Beast name` rather than `URL name`. I'll change this and close this issue again.

**Comment by PaulHeggarty** [comment]
Ouch, another waste of our time because I didn’t get that closing an issue does not mean that it's deployed yet.  Sorry.  Hmmm.  Nonetheless, perhaps, to pander to my brain on this, it would be best for the rest of us if you did not close an issue until it has actually been deployed?  For anyone but you, it doesn’t feel 'closed' until it's fixed on the website ...

**Comment by runjak** [comment]
Yes, I agree. I'll try to keep this in mind.

**Comment by runjak** [comment]
I've deployed the missing parts for this issue.
