### ISSUE TITLE
Format/Spacing tweaks to header bar

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#190]
- [x] Logged in user name (e.g. heggarty in screenshot below) should appear immediately before the final logout icon.
- [x] Reduce spacing/padding between icons and text labels, it's far too wide still.  On smaller screens/bigger zooms, the header runs to two lines because of this.

![screenshot - 26_05_2016 10_11_52](https://cloud.githubusercontent.com/assets/8819910/15568083/481287a2-232a-11e6-914e-8bf9f7b039a5.png)

Once the above are completed, keep this issue open for other tweaks later, but downrate its priority to 2nd.

**Comment by runjak** [comment]
I've deployed the changes form this issue.
It appears that the spacing may still linger in browser caches - so if it doesn't appear adjusted please refresh the cache.
