### ISSUE TITLE
Standardise and improve language names

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#192]
Now that the new features to do this are available, this should be done throughout the language reference table.  I’ve made a start, but could you continue, Cormac?

**Comment by m-scarborough** [comment]
Can I suggest the change of the name of Vedic_Sanskrit to either Vedic or Vedic (Sanskrit)?  The lumping together of Vedic and Sanskrit as one and the same thing in the database has been bothering me for awhile.

**Comment by leszekjocz** [comment]
An idea (forgive me if it was already proposed anywhere): I would be nice to add the vernacular language names. It would be maybe superfluous to add a special field to the database but we certainly should always give the vernacular names in the "Chapters" for the single languages.

**Comment by cormacanderson** [comment]
Sure, I can do this today. I will change Vedic_Sanskrit to just Vedic maybe @m-scarborough ? I think adding endonyms is a good idea, although that is something that the language experts themselves should do of course.

**Comment by m-scarborough** [comment]
Simply 'Vedic' would be best, in my opinion.

**Comment by PaulHeggarty** [comment]
I'm not so sure.  It's fine for those in the know, but for a broader public …  What is Sanskrit, if Vedic is not part of it?
How about we have two varieties:  Sanskrit: Classical  and Sanskrit: Vedic
That is the plan in any case. And I think that's how they should be named.  Wikipedia usage is clearly 
https://en.wikipedia.org/wiki/Vedic_Sanskrit
And that indicates a general degree of agreement on the terminology.

**Comment by m-scarborough** [comment]
Ok.  I still believe the proper usage is Vedic for the language of the Vedas, Brāhmaṇas, and other early liturgical texts that were composed while it was still a living language, and Sanskrit for is the artificial literary form of the language as codified by Pāṇini, but if we are setting up separate Vedic and Classical varieties that sounds like an acceptable compromise for the nomenclature.

**Comment by PaulHeggarty** [comment]
In the end, you got your wish, Matthew.  The language is now split into two, called Vedic: Early and Vedic: Late.  Cormac, is the revision of language names complete, so that this issue can now be closed?

**Comment by PaulHeggarty** [comment]
Just testing something:  @PaulHeggarty

**Comment by cormacanderson** [comment]
Yes, we have renamed them. As agreed, modern languages are generally of the form Language: variety, e.g. Tsakonian: Propontis, Gaelic: Irish, etc., and similarly for Vedic: Early and Vedic: Late, as above. Older languages are named Old French, Old English, etc., as they are usually found, apart from Greek: Ancient. Should I change this too, or can it stand like that? Closing for now anyway.
