### ISSUE TITLE
Clade labels not working properly in Languages Reference table

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#193]
(This used to be part of issue #186, but Jakob correctly asked for a separate issue, so here it is.)

Clade labels are wrong, getting combinations of values between the different Cl levels wrong.  Perhaps a problem with the search for 'abbreviations' rather than just the label itself?

Note how Shugni is given as Iranic in level 0, but that should be level 1 after Indo-Iranic in level 0.  Indeed, all entries that are level 6-3 should appear as Indo-Iranic then Iranic, but only Shugni does.  Some bug in the lookup.

Similar problems in the Italic and Celtic entries, as per the second screenshot, which I hope will help diagnose.

![screenshot - 19_05_2016 15_49_22](https://cloud.githubusercontent.com/assets/8819910/15395997/63654350-1dda-11e6-8f3a-4b2f045b6ffa.png)

![screenshot - 26_05_2016 15_20_35](https://cloud.githubusercontent.com/assets/8819910/15576163/deb9e23c-2356-11e6-8b5b-3b7a64eb8d72.png)

**Comment by PaulHeggarty** [comment]
Jakob's earlier comment was:

The lookup system for clades has different shortcomings, some of them likely stemming from the fact that I currently cannot figure out the language-clade relations in a useful manner when clades are changed as opposed to languages, others stemming from the fact that I still need to essentially redo the clade filter on the client side.

**Comment by PaulHeggarty** [comment]
Basically, the logic is this.
For each language …

Level Cl 0:
look up that language's value in the Cl 0 field, let's say it's 6
take that value and look up in the clades table the clade name that corresponds to the clade defined as Cl 0 = 6, and all other Cl levels = 0
Use that clade name as the clade name in the 'abbreviation column alongside the Cl 0 field for that language.

Level Cl 1
Look up the language's value in Cl 0 and Cl 1
If Cl 1 = 0, then leave the Cl 1 abbreviation column blank, and for all following Cl levels
If Cl 1 > 0, let's say it's 3, then take the Cl 0 and Cl 1 values and look up in the clades table the clade name that corresponds to the clade defined as Cl 0 = 6, Cl 1 = 3, and all other Cl levels = 0

And so on.

**Comment by runjak** [comment]
Thanks for putting the logic in here in detail.
The main problem in connecting languages to their clades is currently time:
If a single clade is changed this could potentially change for each language whether it is connected to that clade. Figuring out these relations takes about 10 minutes at the moment which is unacceptably slow. I'm trying to find a faster approach for this, but am not entirely sure if I can manage to do this.

**Comment by PaulHeggarty** [comment]
Clades will not change now.  Perhaps one or two may be added, but the numbers of the current ones will not change.  As an example, the code for the Cl 0 name column on the Languages Reference Table might be something like this (in the SQL version used in Visual Basic):

DLOOKUP [Clade Name] FROM [Clades Table] WHERE [Clades Table].[Cl 0]=[Languages Table].[Cl 0] AND [Clades Table].[Cl 1]=0 AND [Clades Table].[Cl 2]=0 AND [Clades Table].[Cl 3]=0 

Then the code for the Cl 1 name column would be:
DLOOKUP [Clade Name] FROM [Clades Table] WHERE [Clades Table].[Cl 0]=[Languages Table].[Cl 0] AND [Clades Table].[Cl 1]=[Languages Table].[Cl 1]  AND [Clades Table].[Cl 2]=0 AND [Clades Table].[Cl 3]=0 

And the code for the Cl 2 name column would be:
DLOOKUP [Clade Name] FROM [Clades Table] WHERE [Clades Table].[Cl 0]=[Languages Table].[Cl 0] AND [Clades Table].[Cl 1]=[Languages Table].[Cl 1]  AND [Clades Table].[Cl 2]=[Languages Table].[Cl 2]  AND [Clades Table].[Cl 3]=0 

And the code for the Cl 3 name column would be:
DLOOKUP [Clade Name] FROM [Clades Table] WHERE [Clades Table].[Cl 0]=[Languages Table].[Cl 0] AND [Clades Table].[Cl 1]=[Languages Table].[Cl 1]  AND [Clades Table].[Cl 2]=[Languages Table].[Cl 2]  AND [Clades Table].[Cl 3]=[Languages Table].[Cl 3] 

You’d probably need some additional bit of code to handle cases where there is no record in the Clades Table that has the values for a particular language.  This should never happen in principle, because there are clades for all languages, but someone might enter an erroneous value in one of the Cl fields for a particular language, I suppose.  If so, display something like 'error!' in place of the looked up clade name.

**Comment by runjak** [comment]
Thanks for the effort in writing down the queries for me, but the actual code in [ielex/languageCladeLogic.py](https://github.com/lingdb/CoBL/commit/52fd391f651d0d7091fccd44439347ccd228694d) looks quite different. I'm testing a new approach with this and think that it should be possible to get this task done with good speed. But first I'll now need a look at the SndComp issue.

**Comment by runjak** [comment]
I've put the code to update clade-language relations trough a bit of testing and it appears to be quite fast for the anticipated changes.
I'll now verify that it solves the current problem correctly and than aim towards deployment.

**Comment by PaulHeggarty** [comment]
Excellent!  Seems to work, and fast enough … except … for one misunderstanding.  :)  
Various ways of seeing this:
- Labels should not necessarily appear for every level for every language.  
- Whenever the value on any Cl level is zero, there should be no text label at all for that Cl level.  
- That is, no label should be repeated on multiple levels.  
- One label only ever applies to a single level.  The label for the next level should be different, or none.

I hope the solution is simple:  *if in any Cl level the value is 0, then no label for that Cl level*, just the number 0.

Below are some screenshots of what it should look like.
![screenshot - 30_05_2016 18_10_44](https://cloud.githubusercontent.com/assets/8819910/15654191/4913ef4a-2692-11e6-85ed-9b40d9615b9d.png)
![screenshot - 30_05_2016 18_11_46](https://cloud.githubusercontent.com/assets/8819910/15654193/4b844fae-2692-11e6-817f-b11f9279da3d.png)
![screenshot - 30_05_2016 18_05_48](https://cloud.githubusercontent.com/assets/8819910/15654196/4fa3c506-2692-11e6-84bb-8507c7695542.png)
![screenshot - 30_05_2016 18_06_12](https://cloud.githubusercontent.com/assets/8819910/15654200/53b71c42-2692-11e6-9142-4b9b7f905da3.png)

**Comment by PaulHeggarty** [comment]
One other thing.  The label colours should remain the same for the same label, whatever the lower levels might be.  Note how at Cl 0, the Balto-Slavic and Indo-Iranic labels each change colour depending on the Cl 1 value  They shouldn't, only the Cl 1 labels should have those different colours.

**Comment by runjak** [comment]
I've implemented the requested changes and will soon deploy them.

**Comment by runjak** [comment]
I've deployed the changes from this issue.

**Comment by PaulHeggarty** [comment]
I’m afraid this is not working properly for me now (on Firefox).  Only two labels are showing for the entire table, the level 0 labels for Tocharian.
![screenshot - 02_06_2016 20_32_44](https://cloud.githubusercontent.com/assets/8819910/15756388/6d715a8c-2901-11e6-9d15-ce8f3f36d508.png)

**Comment by runjak** [comment]
Yes, this doesn't look right.

**Comment by runjak** [comment]
Turns out that this was a thing I overlooked in the code that generates the clade - language relations. I've got a fix for this that I'll soon deploy.
