### ISSUE TITLE
Fix sort order in 1 meaning all languages table

### ISSUE THREAD

**Issue by CasFre** [lingdb/CoBL#198]
Hi guys,
Propontis Tsakonian is always showing up almost at the end of the language list, although it should appear among the other forms of Hellenic above.
Who is taking care of such things and would move it in the right place?

**Comment by CasFre** [comment]
Same goes for Latgalian, I guess.

**Comment by cormacanderson** [comment]
Okay, I thought this problem was mine, but it's not, in that I have categorised these languages correctly on the `languages references` html form. The problem is that the sort ordering on the `one meaning all languages` view does not correspond to that on the languages references table.
