### ISSUE TITLE
Fix broken language reference list

### ISSUE THREAD

**Issue by runjak** [lingdb/CoBL#199]
@cormacanderson discovered that language reference lists appear to be broken for [some](http://www.cobl.info/languagelist/all/) language lists on the server while still working for [others](http://www.cobl.info/languagelist/01_Albanian/).

**Comment by m-scarborough** [comment]
The meanings pages appear to be currently offline too.  They were working earlier today so I assumed it was because you're doing an update.

**Comment by runjak** [comment]
Yes, except that I didn't do an update on cobl today.

**Comment by m-scarborough** [comment]
Sorry, I meant 'I assumed it was because…' in the sense of 'It broke while I was working on it today.  I assumed there was an update to the code going on.  I didn't know whether or not there was an update actually happening.'

**Comment by PaulHeggarty** [comment]
Strange, I can't see anything wrong. Can somebody tell me an example URL of a page that doesn’t work?

**Comment by PaulHeggarty** [comment]
Are things still working nonetheless for the lists that we actually need for the next few days? Because we have a big priority to work on the Sound Comparisons project for Russell leaving on Saturday. If this issue is not critical, i.e. if people can still work on the lists they need to for CoBL, it would be better to fix it after the weekend.

**Comment by runjak** [comment]
Screenshot of the error message:
![screenshot_2016-06-22_10-23-47](https://cloud.githubusercontent.com/assets/5417642/16259543/711f2b52-3863-11e6-893e-8e8a006253c2.png)
I think this is a problem with the name of a language list containing unexpected characters.
It should be possible to solve this in short time.

**Comment by PaulHeggarty** [comment]
Perhaps we should ultimately move to the same system as for language names: a `display name` separate from the `url name`.
Also, would special characters explain why this doesn’t work?
http://www.cobl.info/languagelist/all/

**Comment by runjak** [comment]
Yes - the issue here appears to be that I didn't check the `ascii_name` field of a language to be valid for urls. The `utf8_name` is currently used as display name whereas the `ascii_name` should not contain special characters and be usable for URLs.
The quick fix will be to remove the offending entries and add a check for the `ascii_name` to the forms on the server side.
The offending entries are:
![screenshot_2016-06-22_10-29-55](https://cloud.githubusercontent.com/assets/5417642/16259807/a1e5d76c-3864-11e6-9bb6-e59e86f56708.png)
I believe these are the ones Cormac tried to add yesterday which resulted in the site being broken.

**Comment by PaulHeggarty** [comment]
Is the problem the colon in 'Greek: Cappadocian', when that is a `display name` but presumably the code should be looking for a `url name`.  That should be Greek_Cappadocian or something. But has it been correctly entered at all?  This is a new language, which presumably caused the problem.

**Comment by PaulHeggarty** [comment]
I was just writing my above comment when yours came in.  It looks like the adding a new language system has allowed a language to be added with an `url name` that is not valid.  So the system for adding a new language should be amended not to work until the `url name` is valid.

**Comment by PaulHeggarty** [comment]
Presumably this needs cross-checking also with the 'clone this language' function.

**Comment by runjak** [comment]
I've implemented/fixed the input validation both for a languages `ascii_name` and for cloning languages. In the database I didn't like the idea of just deleting entries that don't fit the pattern. So I've cleared them up by removing invalid symbols from the `ascii_name`.
For this reason we have 2 entries like `GreekCappadocian` - this is probably interesting for @cormacanderson to look at.

**Comment by runjak** [comment]
@m-scarborough no offense taken btw.

**Comment by cormacanderson** [comment]
Thanks @runjak . Have sorted out the duplicates now.

**Comment by m-scarborough** [comment]
@runjak It's okay, I didn't think there was actually an offense made—just clarifying my English.  Anyway, I'll shut up now and get back to the cognacy. :)
