### ISSUE TITLE
The 1 meaning all cognate sets page still includes excluded lexemes

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#200]
The idea of the cognate sets page is that it should not show sets that only include lexemes that are not marked to be excluded (not Swadesh). Interesting, in the screenshot below, there is a cognate set with no language clade assigned to it (5289). That is because it has been correctly identified as an excluded lexeme, but the cognate set still appears.

![screenshot - 2016-06-22 00_44_00](https://cloud.githubusercontent.com/assets/8819910/16248893/7b2083d6-3812-11e6-822e-50c09ba7f662.png)

![screenshot - 2016-06-22 00_32_31](https://cloud.githubusercontent.com/assets/8819910/16248707/1769a224-3811-11e6-90ec-f267d7d1ba1f.png)

![screenshot - 2016-06-22 00_33_11](https://cloud.githubusercontent.com/assets/8819910/16248709/192aa554-3811-11e6-8c15-a617d65ba21d.png)

**Comment by CasFre** [comment]
Maybe we should bring the status of excluded lexemes to the plate, then, more generally...
What I mean is that I thought the main reason to keep a lexeme which is not exactly the Swadesh term was if it is nevertheless a fine cognate with lexemes from other languages that are Swadesh terms for the meaning in question or maybe even other meanings in the database.
From this perspective the cognate sets table and the individual cognate set page would be the places where they should appear, or at least should be optionally shown.
Whether the excluded lexemes are shown on the cognate sets pages or not does not influence whether they go into the export or not, right?

**Comment by PaulHeggarty** [comment]
OK, in principle, but it's not really about whether they go into the export. It's about whether they take efforts away from what we've got to focus on, which is the current project and deadline.  For those purposes, excluded lexemes are **out**, end of story.  The other possibilities of what we might want to do with them at some hypothetical future stage are not something to be thinking of now. With the current funding arrangement, it may be that nothing will ever happen with these, so we can’t put any time into these unless we have a separate project funded independently. That is at least a year down the line, probably more.

We should not divert one second of anyone's time at the moment to any data entry whatsoever about excluded lexemes.  We have a very tight schedule to make the end of August deadline, and have to focus exclusively on that. 

Jakob, if you can easily do a feature that allows us to toggle whether excluded lexemes are or are not taken into account in all the results on the 1 Meaning all Cognate Sets form, then that would be nice.  If not easy, then just set the default to **not** taking them into account.

**Comment by runjak** [comment]
A filter for this shouldn't be too hard to build, and may already get completed today.

**Comment by runjak** [comment]
I'm adding a filter column to the cognate classes table that allows to filter for cognate classes that have all lexemes checked as `not Swadesh`.
This filter will per default exclude all cognate classes that don't have a lexeme that is not marked.
![screenshot_2016-07-05_12-35-22](https://cloud.githubusercontent.com/assets/5417642/16582099/1bc8c006-42ad-11e6-8547-652a1001c541.png)
