### ISSUE TITLE
Progress Bars to show language completion stage

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#215]
- [x] Corresponding to the progress column in the languages reference table, alongside it should be a visual, coloured progress bar looking something like this for the progress stages 1 to 5.  I presume stage zero should be just a blank.

![screenshot - 2016-07-11 14_14_22](https://cloud.githubusercontent.com/assets/8819910/16730190/cbe94050-4771-11e6-96b9-914c94dbfe63.png)

I wonder if there's something like this already out there, for which you could take the images and code from.  
This should be visible in administrator view only, perhaps -- thoughts, @cormacanderson ?

I’ve put this as urgency 0 because we really do need to be looking at this very often precisely over the next few weeks, when the biggest amount of data entry should be happening.

- [x] What would also be nice is an average progress score, to two decimal places, for all of the languages shown on the page, as filtered… Somewhere in the header.

**Comment by runjak** [comment]
Bootstrap already provides some [progress bars](https://getbootstrap.com/components/#progress-alternatives) in colors `green, blue, orange, red`.
I expect it wouldn't be too hard to change the colors and adapt these bars to our needs.

**Comment by PaulHeggarty** [comment]
I’ve just made slight changes to the colours in the image above, you can now just pick those and use them as is.  I don’t see a bootsrap version that looks like easily countable 'building blocks', which is ideally what we would like, but if it's a lot simpler to use theirs, rather than just one of five tiny images based on the one above, then OK.

**Comment by runjak** [comment]
Where in the table should these progress bars be displayed?
Do you want them between `Progress` and `Entered` in each row?

The additional one in the header should be doable as well, I think I can combine this with some code for #214.

**Comment by PaulHeggarty** [comment]
Actually, I think we need yet another re-ordering, sorry.  My preferred order would be...
- Keep all existing fields up to and includeing Glotto
- Then Author, Time Frame (sic), Reviewer, Progress, NEW Progress Bar image
- Then the six columns from Entered to Check, kepts as a block 
- Then the eight columnouns from Mean TD to Web Path (i.e. moved from where they were originally)

**Comment by cormacanderson** [comment]
For practical purposes, that reordering is probably a good idea - we don't really use the time depth or weblink fields very often and the page already has a lot of info. I very much like the idea of an average progress score. It doesn't really bother me whether the progress bar is visible to everyone or just admins, but I think at a minimum only admins should be able to edit it.

**Comment by runjak** [comment]
Ok - I'll see to implement this :+1:

**Comment by runjak** [comment]
I've got an implementation for this.
After spending a few hours getting frustrated by putting the images in correctly I decided to stick with the bootstrap defaults for progress bars.
The coloring may need adjustment but the basic functionality is there and works.
This issue will be closed on deployment.

**Comment by PaulHeggarty** [comment]
This is nice, but there's a problem in Firefox, where this goes onto a second row, and all records take up twice as much vertical space.  It may be relevant that in Chrome I see the progress bar vertically aligned to top, rather than centred for all the other fields.  See images.
![screenshot - 2016-09-23 17_22_09](https://cloud.githubusercontent.com/assets/8819910/18791381/c2d53d9a-81b2-11e6-86f5-e17d263795b8.png)
![screenshot - 2016-09-23 17_25_29](https://cloud.githubusercontent.com/assets/8819910/18791382/c2db9456-81b2-11e6-8f8d-26978691419d.png)
