### ISSUE TITLE
Authors page is broken

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#216]
http://www.cobl.info/authors/
gives the error page.

**Comment by cormacanderson** [comment]
Interestingly, it is visible (although obviously cannot be modified) if you are not logged in, but once you log in, it gives the error message.

**Comment by runjak** [comment]
Interesting! The authors page appears to behave differently on my machine and on the server.

**Comment by m-scarborough** [comment]
It is viewable both logged-in and logged-out to me using both Google Chrome and Firefox (on a Mac).  Of course, I don't have the permissions to edit the authors page so it could be an issue in the editing view.

**Comment by runjak** [comment]
It appears that this a problem with handling encodings:
![screenshot_2016-07-12_10-33-22](https://cloud.githubusercontent.com/assets/5417642/16760452/163879f0-481c-11e6-916a-82dca9154908.png)
I could produce a fix for this that will soon be deployed.
Apparently it was a problem with the contributor images and non ascii symbols.
