### ISSUE TITLE
Add fields to Language Data

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#218]
To ensure a smooth interface with Remco's pre-existing calibration texts, we actually do need to preserve the old Ascii language names, it turns out.  We need to have that data saved for legacy purposes, in other words. So, please … 
- [x] Create a 'new' field called `Ascii name` in the language data _table_, but not on the language reference _form_ (it would only take up unnecessary space). It should appear in the language meta-data table, after the URL name, but should not be editable, as these values will never change, and never be added to (this field should be blank for all new languages). The data should be pre-filled with just a straight copy of the data currently in the URL name field -- before we start changing them, as we soon will.

- [x] Another new field, Boolean, called 'Historical', to appear in the Language Reference form immediately before `Display Name`. The data in this field can be pre-set so that all languages for which the field `Mean TD` > 0 should be set to `Historical` = TRUE . This is to be a cross-check quality control field, in fact -- see next check box.  

- [x] Logical constraints: any field marked true for `Historical` must have `Mean TD` set to a number greater than 0. Any field marked false for `Historical` should have the block of four fields `Mean TD`, `Std. Dev`, `Earliest` and `Latest` all locked and uneditable.

**Comment by runjak** [comment]
The original field has always been called `Ascii name` in the database.
It's just labeled `Url name` on the website.
I will add a column `Originial Ascii Name` to the table and label it as `Ascii name` on the metadata page.
This column will not be editable and will be filled initially by copying.

**Comment by PaulHeggarty** [comment]
OK, though I presume you don’t literally mean column, because it is not to appear on the languages reference table, only on the metadata page, where it's not a 'column'.

**Comment by runjak** [comment]
Yes, I meant column only in the sense of tables in the database (SQL) not on the website (HTML).

**Comment by runjak** [comment]
I've added the `Historical` field on my machine.
![screenshot_2016-07-12_14-10-34](https://cloud.githubusercontent.com/assets/5417642/16766450/78c624e6-483a-11e6-9a2a-7e173bbd40ee.png)
The next step will be implementing the constraints.
