### ISSUE TITLE
New System to Assign Cognate Set by Drop-Down Box

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#219]
-----
New note as of 2016-08-02, and deployment of main solution.

Again, a few more tweaks, please, now that we can see the main solution.
- [x] Reorder the columns slightly.  It should be:  `nCog`, `Select`, `Cog. ID` [sic], `Cog Alias`, `Edit`, green icon, `Root form`
- [x] Add tooltip for green icon:  Switch page to view all cognate sets for this meaning.
- [x] Add tooltip for `Cog. ID`:  New tab to view details of this cognate set and all member lexemes.
- [x] Add the same tooltip for the `Cog. Alias` letter.
- [x] Rename `Edit` to `Assign`.
- [x] The `Cog. Alias` letter should take over the function of the edit/assign button, and have the tooltip "Click to re-assign this lexeme to a different cognate class."  Clicking on it should open the dialogue box with the drop-down list.
- [x] The edit/assign button and its column can then be deleted.
- [x] Where a lexeme is **not** yet assigned to any cognate class, then _in place of_ the Cog. Alias letter there should be the + icon, with the tooltip "Click to assign this lexeme to a cognate class.".  But clicking on it should also simply the normal dialogue box with the drop-down list.
- [x] The existing + button and its column can then be deleted.

- [x] Within the drop-down box, there should not be separate options for Add and Save.  The Add button should appear only for admin users.  For others, there's not even much need for a Save button, simply clicking on the term in the list should be enough to save.  

- [x] The sort order for cognate sets should be by `CladeCount` (**de**scending) followed by Lexeme Count (**de**scending).  This should also be the default sort order for the `1-Meaning, All Cognate Sets` form.

- [x] Within the drop-down box itself, things are not so easy to read, because of the commas. It would be much better to use columns where each field is aligned with the ones above and below. See the following image of such a 'multi-column' drop-(up) box in Access. (closed by @runjak 2016-09-26 because impossible)

![screenshot - 2016-08-01 13_58_12](https://cloud.githubusercontent.com/assets/8819910/17293402/60b597cc-57f0-11e6-87ff-fb40e2ae941a.png)

- [x] When all is finished, working and checked, include the same system in the `1-Language, All Meanings` form. 

-----
New note as of 2016-07-27.

Most check box points here have already been solved.  There is also the new system for assigining a cognate set to multiple lexemes in one go, using the new brown links at the top of the `1-Meaning, All Languages` form.  That is already great, but needs some improvements.  It also needs to be possible to launch this function from individual lexeme record rows, certainly in `1-Meaning, All Languages` view, but preferably also from `1-Language, All Meanings`, using the same drop-down system. 

I will now move the main outstanding check up here, and leave the remaining 'legacy' ones, already implemented, below it.

- [x] As soon as possible, turn the (combined, always linked) `Cog. Alias` + `Cognate Set ID` field into a drop-down box to **select** a value from a drop-down list of all cognate sets for this meaning.  Typing a `Cog. Alias` letter should move to that position in the drop-down list. This is #51. This drop-down list should show at least the fields `Cognate Set ID`, `Cog. Alias`, `Root Form` and `Root Language`. It should be effectively a slimmed-down version of the [1-Meaning, All Cognate Sets] form for this meaning.  This was also formerly part of #222, where the same drop-down structure had also been requested, saying:  In the drop-down box, the alias letter alone is much less helpful than if it were followed by the cognate set ID, and especially the root form and root language, and preferably the 'loanword event?' boolean value too, and the loan source language. Basically, all of those fields are really needed to easily identify a cognate set, so they should really almost always appear together anywhere where cognate sets are listed so that one can be selected. 

- [x] The same 'multi-column' drop down box should also be implemented within the box that
 appears when clicking on the brown icons at the top right of this page.  In effect, these two functions could be merged into one.

----
ORIGINAL ISSUE CHECK BOX POINTS...

In the [1-Language, All Meanings] form, one cannot get, easily in one click, from the lexeme entered to the cognate set that it belongs to, or indeed to the selection of cognate sets for that same meaning. This needs to be possible. Effectively, it needs to be possible to enter those data directly from this form, by a **drop-down box of cognate sets** for this meaning, as we have always wanted for the [1-Meaning, All Languages] form too.

Without this function on the [1-Language, All Meanings] form too, we have a crazy inefficiency.  Does one really have to go through the 1-meaning all languages view, page by page, 200 pages for each single language?  We need to avoid this. The first steps are:

In the [1-Language, All Meanings] form ...
- [x] Add a column `Cognate Set ID`, immediately in front of `Root Form`. It should be clickable, and open a new tab at the page for that cognate set.
- [x] Add a column `Cog. Alias` form, immediately in front of `Cognate Set ID`.  I **know** that these letters are only valid per meaning, but I want them there anyway. This should be clickable, and in the first instance should behave as it does on the [1-Meaning, All Languages] page, but should as soon as possible be changed to do as per the next check-box point...

- [x] This point is important for cases where the drop-down list does not show enough detail. There should also be a link direct to the [1-Meaning, All Cognate Sets] page for each meaning. This should use the same coloured [1] icon as in the header, but of course link to the meaning that corresponds to this row in the [1-Language, All Meanings] form. I.e. the icon in each row will link to the [1-Meaning, All Cognate Sets] page for a different meaning.
- [x] Make **uneditable**  in this form the columns `Root Form`, `Root Language` and the others up to `Cog. Excl.`. These values should only be looked up on the basis of the selected `Cognate Set ID` or `Cog. Alias` value. 

Also in the [1-Meaning, All Languages] form ...
- [x] Add a column `Cognate Set ID`, immediately in front of `Root Form`.  It should be clickable, and open a new tab at the page for that cognate set.

We *must* have this. This is a big lacuna in the whole CoBL system, which is absolutely top priority to fix.

**Comment by PaulHeggarty** [comment]
As far as I understand it, currently we cannot change the assignment of a cognate set directly from one to another, it has to be deleted and another one added.  It's only the + button that opens the drop-down list to assign a cognate set.  We should perhaps have an 'edit' button instead, which launches the drop-down list.  One (very rare) option at the end of that list could be a + to add a second cognate set assignment.  But I don’t think a + icon is the most appropriate for this, and it must allow a single operation to change the letter assigned, without needing a delete plus an add.

**Comment by PaulHeggarty** [comment]
We discussed this yesterday 2016-07-26, so @runjak has more details to go on for this issue, which is now the big remaining one for this week. As discussed, implementing this as desired will effectively also close #52.

**Comment by runjak** [comment]
I've been working on code to change cognate class assignments and got the client side part almost completed.
When viewing the `1 meaning all languages table`, the selection will soon look like this:
![screenshot_2016-07-28_16-04-35](https://cloud.githubusercontent.com/assets/5417642/17215449/2e122652-54dd-11e6-9184-b4f5f0d4ee44.png)

Hitting the orange/brownish edit button will automatically be counted as including that row's entry as well. On clicking the button a modal like this will open:

![screenshot_2016-07-28_16-04-45](https://cloud.githubusercontent.com/assets/5417642/17215489/4dccdabe-54dd-11e6-9a3a-67035c97450c.png)

By selecting different choices for current classes it will be possible to assign a new cognate class instead of a specific one as well as removing a specific class from the selection.
![screenshot_2016-07-28_16-04-57](https://cloud.githubusercontent.com/assets/5417642/17215492/50619d00-54dd-11e6-99a5-271f67e14761.png)

I'll add the option to add a completely new cognate class as well for (rare) cases where it will be useful. Afterwards I'll implement the server side processing of such data.

**Comment by PaulHeggarty** [comment]
Good to see, looks like you’re nearly there.  A few things to comment on, though.
* I don’t get why in your demo image there are three drop-down boxes lines, two of them preset to the same cognate class A.  Is it just that you are presuming a case where a lexeme has -- spectacularly unusually! -- been assigned to three cognate sets?  Or is one to change, another to add, or what?
* Within the drop-down box itself, things are not so easy to read, because of the commas.  It would be much better to use columns where each field is aligned with the ones above and below.  I presume you may be planning that in any case, and just wanted to get this showing quickly for now.

**Comment by PaulHeggarty** [comment]
I now wonder if you've done this also so that multiple lexemes can be selected even if they currently are assigned to different cognate sets.  I hadn’t even thought about this possibility.  I actually think it's a bit too risky to allow this.  I would only allow cognate set (re)assignments to selections of lexemes that are all currently assigned to the same cognate class, or none (or a combination of those two).  
So clicking on the assign cognacy button would first run a check, and when necessary return a warning saying "Please select only lexemes assigned to a single cognate set (your selection includes more than one cognate set)." It would then close, and not allow any assignment, but take the user back to the form to correct their selection.

**Comment by runjak** [comment]
* The double appearance of class `A` is a bug during development that I have not adressed jet, but that will be fixed before deployment.
* I'll add code to prevent selection of lexemes across distinct sets of cognate classes as you've suggested.

**Comment by runjak** [comment]
I've finished the main code part of this issue and will deploy now.

**Comment by runjak** [comment]
Deployed.

**Comment by PaulHeggarty** [comment]
Could you also now remove from each row the + button that currently has a tooltip 'add another cognate alias'?

**Comment by runjak** [comment]
The `+` button that is to be removed is also used when assigning a cognate class from the lexeme report:
![screenshot_2016-08-03_13-27-08](https://cloud.githubusercontent.com/assets/5417642/17364152/e449b9bc-597e-11e6-9b83-1d6a428fbc08.png)

This implies that I'll need to either build some new code for cognate class assignments from viewing a single lexeme or that I can remove this functionality from the lexeme report.
@PaulHeggarty is the assignment from the lexeme report view any good?

**Comment by PaulHeggarty** [comment]
Are we talking about the same thing?  I mean ththe round + button in this:
![screenshot - 2016-08-03 16_09_53](https://cloud.githubusercontent.com/assets/8819910/17368540/c7f031fe-5994-11e6-8219-a180876c3a2d.png)

**Comment by PaulHeggarty** [comment]
That should just be removed from the display as a column in the `1-Meaning, All Languages` form, that's all.  If the code for it is needed elsewhere, keep it.

**Comment by PaulHeggarty** [comment]
In any case, you’re right that the lexeme report page currently offers a long way round to what we're trying to stop people doing anyway.  Moreover, the texts on that page seem wrong.  They need correcting as follows:

[Add link to cognate class] should say [Assign this lexeme to an *additional* cognate class] 
And the note underneath should say:  Only to be used in *exceptional* cases -- usually only if the lexeme is a compound of two full roots, e.g. 'stone + head' for the meaning head in Irish.  Users do not normally have rights to add multiple cognate assignments;  to so so, please contact the CoBL administrators with your justification.

The header [Add link to new cognate class] should say:  [Create a new cognate class and assign this lexeme to it]
The note underneath should be deleted, and replaced with:
Please check carefully all existing cognate classes in this meaning, to be sure that the lexeme in your language does not belong to any of them.
Creating this will automatically assign your lexeme to this class, and delete any existing assignment to another cognate class.

The second function is OK, and should be left, so long as it is set to *replace* the existing assignment, not add a second assignment.

The first function should be locked/disabled for non-admin users, though the text can be left to explain that.

**Comment by runjak** [comment]
Yes, we are talking about the same thing.
When assigning cognate classes from the lexeme report it just navigates the browser to the same selection via drop-down list that is opened in 1 meaning all languages view as the `+` button does. I'll keep the code for this then - for now - but I think the code becomes more messy from this approach and would be cleaner if I just redid or removed the cognate class assignments from the lexeme report.

**Comment by runjak** [comment]
The drop-down list in this screenshot will be kept because it is used for assigning cognate classes when using the method via the lexeme report:
![screenshot_2016-08-04_09-47-30](https://cloud.githubusercontent.com/assets/5417642/17394267/7a5ccec2-5a28-11e6-8bbd-7720145fbd28.png)

**Comment by runjak** [comment]
I have an implementation of the cognate set assignment code for the `1 language all meanings` view. It looks like this:
![screenshot_2016-08-12_14-26-03](https://cloud.githubusercontent.com/assets/5417642/17622144/d7388b1a-6098-11e6-9d2e-36d6078b65d8.png)
![screenshot_2016-08-12_14-26-19](https://cloud.githubusercontent.com/assets/5417642/17622143/d73880d4-6098-11e6-9bce-044182af2751.png)

Notice that the `alias` letters are repeated in the second screenshot several times.
This is because they are currently computed on a per meaning basis.

**Comment by PaulHeggarty** [comment]
Looks like big progress, but not sure I get why the `alias` letters are repeated.  On the `1-Language, All Meanings` form, the ability to make assignments (by the drop-down box) should absolutely, necessarily be limited to a single lexeme (=record row) at a time.  No selection of multiple lexemes here, to apply the same cognate set (alias) to them!  That's only relevant for a single meaning at a time.  In short, for `1-Language, All Meanings` this may be a simpler thing to programme, because it is absolutely limited to one lexeme (record row) at a time.  If you need further clarification, just ask.

**Comment by PaulHeggarty** [comment]
There seems to be no + button for adding an assignment where none yet exists, this is a crucial part of what's needed, I’m afraid...  Similarly, the same as on the `1-Meaning, All Languages` view.

**Comment by PaulHeggarty** [comment]
I've seen this is deployed, but it's not really working as is, because of the problem I signal a couple of comments higher up.  For English, in `1-Language, All Meanings` view, filtered down to meaning TRUE, if I try to change the assignment I get this drop-down box:  
![screenshot - 2016-08-12 15_23_03](https://cloud.githubusercontent.com/assets/8819910/17623587/0747b80a-60a1-11e6-88bb-44b25b6d1993.png)

There are cognate sets there that have nothing to do with 'true'.  The first A in Indo-European is for the meaning FATHER, the second for FIVE, the third for FOUR, the fourth for HEART, and so on.  The choice in the drop-down box should be restricted only to cognate sets that exist for the meaning of the lexeme that the user clicks on, i.e. TRUE.  In other words, it should be composed only and exactly of the content of cognate sets at:

http://www.cobl.info/meaning/true/cognateclasslist/

**Comment by runjak** [comment]
I'm trying to figure something out for this.
I'll essentially need to load almost all cognate sets from the database for this.
Because:
* For each meaning on the current meaning list
  * I need all cognate classes in that meaning that are also connected to at least one language from the current language list.

This may boil down to how fast I can get this fetched from the database.

**Comment by PaulHeggarty** [comment]
Hmmm, ouch.  That is indeed correct, yes.  But …
* You'll never have to do that for two meanings at once.  If this could be done, and requested only on the click on the `alias` letter or the + symbol...
* Doesn’t the `1-Language, All Meanings` page load already do something like this, because it calculates (?) the correct `alias` letter for each meaning and displays it in that row.

**Comment by runjak** [comment]
Yes, that's correct - the thing is:
At the moment the whole assignment code is written with the assumption that the cognate sets that can be assigned are known the moment that the page is generated.
Fetching the possible choices later on is of course possible but something that needs more work than I will accomplish today.

At the moment the current code for `1-Language, All meanings` doesn't consider languages other than the current one. But this is something that we need in order to offer cognate set choices outside the current ones.

**Comment by PaulHeggarty** [comment]
You write:  

> at the moment the current code for `1-Language, All meanings` doesn't consider languages other than the current one.  

So where do the alias letters that that page displays come from, then?   Would it be possible simply to allow an alias or even just the cognate set ID number to be typed in, without looking up anything about the cognate sets in the other languages?  That might be the simplest:  just allow the cognate set ID number field on the `1-Language, All Meanings` to be editable, and to accept 1 to 4 digits.  That at least would give us the functionality we need, for copying from one language to a related one, and should be workable for comparing two languages with each other in different browser windows side by side.

**Comment by runjak** [comment]
OK - that should be achievable.
I'll work on that either this evening or tomorrow morning.
I may even be able to do this with alias letters as they are saved per cognate set.
So if I restrict the cognate sets to ones relating to the language and meaning of the edited lexeme I should be able to figure out the alias of a cognate set unambiguously.

**Comment by PaulHeggarty** [comment]
Sounds good.  Just to confirm I understand correctly:  you’ll prepare a system where the user can just type in the `Cog. ID` number into that field, and/or just type in the `Alias` letter into that (pseudo-)field.  (Doing either one would presumably allow the other to get filled in automatically?)

I have to say I don’t quite understand this:

> So if I restrict the cognate sets to ones relating to the language and meaning of the edited lexeme I should be able to figure out the alias of a cognate set unambiguously.

… because cognate sets are always, in all circumstances, restricted to the meaning of the edited lexeme (so that should go without saying), but I’m not sure how you could figure out an alias only from one language ("the language … of the edited lexeme").  But I presume I’m just not understanding what you mean exactly here.

**Comment by PaulHeggarty** [comment]
By the way, thanks a lot for the changes to the export function earlier today -- that should at least make things quicker when we do try to get to that.  (Which should be immediately once you’re back from your break?)

**Comment by PaulHeggarty** [comment]
**PERFECT** would be a button to simply copy the `Cog ID` from the one assigned for that meaning in the reference language in the clade to which the current language in the `1-Language, All Meanings` form belongs.

**Comment by PaulHeggarty** [comment]
Another clarification then:  don’t bother with the drop-down box if you can get working the `cog id` or alias letter working as just editable cells, and especially the `copy from ref language` button.

**Comment by PaulHeggarty** [comment]
To calculate the ref language corresponding to the current language…
1. Take the Cl 0 value for the current language.
2. Filter languages table to those with `ref language` field set to true, and Cl 0 = Cl 0 of current language.
3. If only 1 language meets those criteria [Clades 1,2,3,4,5], take that as the reference language corresponding to the current language.
4. If more than one language meets those criteria, refine the search to Cl 1 = Cl 1 of current language.  If that now leaves only 1 language meeting those more refined criteria, select that remaining language.
5. If still more than one language meets the refined criteria (only in the case of Germanic), refine further to Cl 2 = Cl 2 of current language.  That will do it

Indo-European will fail at Cl 0 = 0 (the search will return 0 reference languages), likewise some languages will fail at level Cl 1 (no Nuristani ref language, no East Germanic ref language, etc.).  In this cases, the copy from ref language button should just do nothing.

**Comment by runjak** [comment]
This is your Sunday morning progress report - from an IC in Magdeburg:

* Copy-over from the reference language is something I haven't achieved yet.
* But I have a functionality that allows the cognate sets to be entered in a text field either by alias or by id. Different sets must be separated by a ','. It is also possible to create a new cognate set by using the keyword `new` instead of an alias or id.
* The input looks like this:
![screenshot_2016-08-14_10-25-07](https://cloud.githubusercontent.com/assets/5417642/17648261/edbfcb92-620e-11e6-9fcd-0c3f8e7c1fb9.png)
![screenshot_2016-08-14_10-58-55](https://cloud.githubusercontent.com/assets/5417642/17648262/edc1c640-620e-11e6-897a-3d6b5e065b5d.png)
* I added a check to this input that prevents non staff users to increase the number of cognate sets for each entry if there isn't at least one cognate set assigned.
This means:
  * If no cognate set is assigned: all users can assign a single cognate set
  * If some cognate sets are assigned: all users can change the assigned sets, and also delete some so decreasing the number of sets.
  * If the user is part of staff: it is possible to add an arbitrary amount of cognate sets to a lexeme.

I'm aiming to deploy this soon.

**Comment by runjak** [comment]
So for 22 days now we have this feature that makes it possible to assign cognate sets directly by entering their `alias` or `id` into an input field. This is demonstrated in `1 language all meanings` view. In contrast `1 meaning all languages` view still uses the system that opens a modal with a selection box for the user to choose from to assign cognate sets. @PaulHeggarty would it make sense to convert both of these approaches to the same input which would be just the input field currently used for `1 language all meanings` view, or is it desirable to have both of the current methods?

**Comment by PaulHeggarty** [comment]
Best would certainly be to be able to enter the alias or ID directly also in `1-Meaning, All Languages` view, yes.  However, the older system with the selection box can still be useful in some cases, so please keep it, but move it onto a separate button (repeated on each row), and make the alias and ID directly editable and so on on the `1-Language, All Meanings` view, yes.

**Comment by runjak** [comment]
The last two comments before this one shall be taken into account for #51, which needs to deal with improving the means to assign cognate set membership.

Since the rest of the tasks for this issues is done I'm closing it now.
