### ISSUE TITLE
Enable sorting by cognate set on [1Mng, All Lgs] html forms

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#222]
Currently, the entries on the `1 Mng, All Lgs` html form are sorted according to the default ordering also found on the `Languages References` page. This change would enable the user also to sort by cognate alias, i.e. listing all the entries belonging to cog. alias A, then all those belonging to B, etc., with unassigned cognate classes at the bottom of the page.

- [x] Enable sorting by cog. alias on the `1 Mng, All Lgs` html form

- [x] DIVERTED INTO ISSUE #239. Preserve the sort for this view even when switching to a new meaning (by the next or previous meaning links, or by typing in the meaning name header, or indeed when swtiching between views).

-----

Formerly a comment:

A further improvement would be to have selection boxes for each lexeme on the `1Mg, All Lgs` page, as are found on the `1Mg, All Cog Sets` html form, under the label `Merge`. Here the selection boxes would be labelled just `Select`.

- [x] Selection boxes for entries on `1 Mng, All Lgs` table
- [x] Move the selection boxes next to the other columns that relate to cognacy.  The column order should actually be: `nCog`, `Select`, green link icon, `Cog Alias`, `Cog ID` (sic), `Root Form`. 

After that, we need two buttons at the top of the page (again similar to the `Merge` function on the `1Mg, All Cog Sets` html form. One button would create a new cognate set for all selected entries, while another would allow the user to add the selected entries to an existing cognate set:

- [x] Create `New Cog Set` and `Add to Cog Set` buttons for selected entries

The `Add to Cog Set` button would allow all selected entries to be added to an existing cognate set. The obvious way to do this would be to allow that cognate set to be chosen from a dropdown menu.

- [x] Create dropdown menu allowing Cognate Set to be chosen for selected entries.

- [x] DIVERTED INTO ISSUE #219.  In the drop-down box, the alias letter alone is much less helpful than if it were followed by the cognate set ID, and especially the root form and root language, and preferably the 'loanword event?' boolean value too, and the loan source language.  Basically, all of those fields are really needed to easily identify a cognate set, so they should really almost always appear together anywhere where cognate sets are listed so that one can be selected. See also #219 on this, a similar drop-down structure is requested there.

**Comment by cormacanderson** [comment]
A further improvement would be to have selection boxes for each lexeme on the `1Mg, All Lgs` page, as are found on the `1Mg, All Cog Sets` html form, under the label `Merge`. Here the selection boxes would be labelled just `Select`.

- [ ] Selection boxes for entries on `1 Mng, All Lgs` table

After that, we need two buttons at the top of the page (again similar to the `Merge` function on the `1Mg, All Cog Sets` html form. One button would create a new cognate set for all selected entries, while another would allow the user to add the selected entries to an existing cognate set:

- [ ] Create `New Cog Set` and `Add to Cog Set` buttons for selected entries

The `Add to Cog Set` button would allow all selected entries to be added to an existing cognate set. The obvious way to do this would be to allow that cognate set to be chosen from a dropdown menu.

- [ ] Create dropdown menu allowing entries to be added to an existing cognate set

**Comment by cormacanderson** [comment]
https://github.com/lingdb/CoBL/issues/51 https://github.com/lingdb/CoBL/issues/52  https://github.com/lingdb/CoBL/issues/197

**Comment by runjak** [comment]
Notes I took on creating cognate sets:

* on the one language all meanings view:
  * Ability to add a lexeme to an existing cognate set
    * but not to a new cognate set.
* on the on meaning all languages view:
  * Ability to add a lexeme to an existing cognate set
  * Ability to add a lexeme to a new cognate set
  * Ability to select several lexemes and add them
    into a new cognate set.
  * Ability to select several lexemes and add them to an existing cognate set.

**Comment by runjak** [comment]
To distinguish the new buttons from the one currently acting as a link to the new lexeme form I've opted to color them in the same color chosen for the `1 meaning all cognate sets` view:
![screenshot_2016-07-18_16-51-22](https://cloud.githubusercontent.com/assets/5417642/16918946/04ac23da-4d08-11e6-8b52-8928ffd5f3d9.png)
I've also added tooltips to the buttons to make it easier to figure out their functionality.

**Comment by PaulHeggarty** [comment]
Great new function, brilliant!  Just one minor new tweak now requested.
When clicking on the edit icon in the header to select a cognate class from the drop-down box, the alias letter alone is much less helpful than if it were followed by the cognate set ID, and especially the root form and root language, and preferably the 'loanword event?' boolean value too, and the loan source language.  Basically, all of those fields are really needed to easily identify a cognate set, so they should really almost always appear together anywhere where cognate sets are listed so that one can be selected.

**Comment by PaulHeggarty** [comment]
We discussed this yesterday [2016 07 26], so Jabok has more details to go on for this issue, which is now the big remaining one for this week. As discussed, implementing this as desired will effectively also close #52

**Comment by PaulHeggarty** [comment]
Both of the outstanding check boxes on this issue really seem to relate to other issues now, namely #219, #239 and #52.  I think this one can be closed, certainly because the request in the title is implemented.  I will copy the corresponding bits of text from here into the new issues, and close this one.
