### ISSUE TITLE
sources linking cleanup

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#223]
Working on the sources table (cf. #195) I stumble across several occurences of identical sources, for example these two:

> 94|Makins, M., Isaacs, A. & Adams, D. 1994 [1979]. Collins English Dictionary, Glasgow: HarperCollins.|P|""|2011-04-11 08:13:22+00
> 93|Makins, M., Issacs, A. & Adams, D. 1994 [1979]. Collins English Dictionary, Glasgow: HarperCollins.|P|""|2011-04-11 08:13:15+00

In my edited version of the sources table I just keep the one with the lower id, so id=94 is deleted in this case. For the linking to work properly Jakob has to change existing links with e.g. id=94 to id=93 after I finished working through the whole list.
I'm opening this issue just to keep track of these specific entries:

| change | to | new one deprecated? |
| --- | --- | --- |
| 39 | 78 |  |
| 45 | 44 | yes |
| 71 | 33 |  |
| 94 | 93 |  |
| 272 | 157 |  |
| 298 | 236 |  |
| 366 | 365 |  |
| 370 | 368 |  |
| 400 | 84 |  |
| 424, 425, 461 and 465 | 423 |  |

| delete |
| --- |
| 21 |

**Comment by PaulHeggarty** [comment]
It looks like the difference was Is**a**acs vs. Is**s**acs.  
One of those will be right, so the surviving record should reflect that.  In any case, what you’ve done is right, of course, thanks.

**Comment by nitsnatsnok** [comment]
#327

**Comment by nitsnatsnok** [comment]
#327

**Comment by nitsnatsnok** [comment]
see also #327

**Comment by nitsnatsnok** [comment]
We decided to delete all wikipedia sources, I'm keeping track of them here so that we can check the corresponding IDs in the database and avoid creating deadlinks.

ID | Link
------------ | -------------
42 | http://en.wiktionary.org/wiki/Appendix:Celtic_Swadesh_lists
43 | http://en.wiktionary.org/wiki/Appendix:Latvian_Swadesh_list
44 | http://en.wiktionary.org/wiki/Appendix:Swadesh_lists_for_Slavic_languages
58 | http://en.wiktionary.org/wiki/Appendix:Proto-Indo-European_Swadesh_list
61 | http://en.wiktionary.org/wiki/Appendix:Scottish_Gaelic_Swadesh_list
64 | http://en.wiktionary.org/wiki/Appendix:Indo-Iranian_Swadesh_lists
87 | http://en.wiktionary.org/wiki/Appendix:Albanian_Swadesh_list
88 | http://en.wiktionary.org/wiki/Appendix:Friulian_Swadesh_list
89 | http://en.wiktionary.org/wiki/Appendix:Swadesh_lists_for_further_Romance_languages
106 | http://en.wiktionary.org/wiki/Appendix:Armenian_Swadesh_list
107 | http://en.wiktionary.org/wiki/Appendix:Polish_Swadesh_list
108 | http://en.wiktionary.org/wiki/Appendix:Portuguese_Swadesh_list
109 | http://en.wiktionary.org/wiki/Appendix:Ossetian_Swadesh_list
110 | http://en.wikipedia.org/wiki/Swadesh_list_of_Slavic_languages
111 | http://en.wiktionary.org/wiki/Appendix:Greek_Swadesh_list
112 | http://en.wiktionary.org/wiki/Appendix:Romanian_Swadesh_list
113 | http://en.wiktionary.org/wiki/Appendix:Swadesh_lists_for_Celtic_languages
114 | http://en.wiktionary.org/wiki/Appendix:Indo-Iranian_Swadesh_lists_%28extended%29
115 | http://en.wiktionary.org/wiki/Appendix:Swadesh_list_for_Baltic_languages
117 | http://en.wiktionary.org/wiki/Appendix:Serbian_Swadesh_list
118 | http://en.wiktionary.org/wiki/Appendix:Ancient_Greek_Swadesh_list
119 | http://en.wiktionary.org/wiki/Appendix:Swadesh_lists_for_Germanic_languages
120 | http://en.wiktionary.org/wiki/Appendix:Spanish_Swadesh_list
123 | http://en.wiktionary.org/wiki/Appendix:Swadesh_lists_for_Iberian_languages
139 | http://is.wiktionary.org/wiki

**Comment by nitsnatsnok** [comment]
List of online sources with dead links:

ID | Link
------------ | -------------
35 | http://www.freewebs.com/hanvant/rajasthani_dictionary.htm

**Comment by nitsnatsnok** [comment]
List of dubious or not self-explanatory sources, we need to check which information is backed up by these and decide what to do with them. They remain in the sources list for now.

ID | Link
--- | ---
233 | http://www.mannin.info/Mannin/fockleyr

**Comment by PaulHeggarty** [comment]
They should have been marked as 'deprecated' first, as we discussed yesterday, rather than outright deleted already…

**Comment by nitsnatsnok** [comment]
@PaulHeggarty You mean the wikipedia sources, right? Sorry, apparently I misunderstood this – I'm restoring them, that's just a minute's work.

**Comment by PaulHeggarty** [comment]
Yes, I meant the wikipedia sources, though also in general we should for now be using the 'deprecated' field rather than deleting anything.

**Comment by nitsnatsnok** [comment]
@khoidt Please clean up the database from the IDs mentioned here, I assume this will help to get rid of blank entries in the sources list.

**Comment by khoidt** [comment]
A generic script for merging, deleting and/or deprecating sources is now `context_processors.py`. The changes listed here is are stored for now in a pythonic dictionary in `manage.py` and applied to the database with `python manage.py updsources`.

**Comment by nitsnatsnok** [comment]
I added:272	157

**Comment by khoidt** [comment]
Updated!

**Comment by runjak** [comment]
@khoidt is there any specific reason to implement this functionality as a command rather than a migration? Using migrations for this would have some benefits:

* Migrations are already a way to alter database content and schema
* Current deployment applies migrations automagically - custom commands need manual intervention.
* We can check whether migrations are applied and which ones. This cannot be done for commands.

There are already some migrations that alter database content in the [ielex/lexicon/migrations](https://github.com/lingdb/CoBL/tree/1f6103bb722c581fde523a0ea3036f4d42c6798d/ielex/lexicon/migrations) folder.
An example would be [0021_fix_jena200.py](https://github.com/lingdb/CoBL/blob/1f6103bb722c581fde523a0ea3036f4d42c6798d/ielex/lexicon/migrations/0021_fix_jena200.py).

**Comment by khoidt** [comment]
@runjak You're right, I'll implement the changes in a migration.

**Comment by PaulHeggarty** [comment]
Just as a general comment:  this issue was closed before it was deployed.  That is not our policy.  An issue should be closed only when it has been deployed (and checked to be working online).  And when the deployment has been announced on the changelog at #260 .  
The reason is obvious:   for everyone else waiting for the issue to be solved, nothing has changed and nothing is yet solved or 'closed' until deployed.  ;)

**Comment by khoidt** [comment]
@PaulHeggarty, sorry, my fault. @runjak I have made this a migration `306_0127_fix_issue_223.py`.

**Comment by runjak** [comment]
@khoidt splendid :+1:

**Comment by khoidt** [comment]
@nitsnatsnok done @runjak note update in devel.

**Comment by runjak** [comment]
Ah, @khoidt sorry for the delay. I'll investigate `devel` today and aim for deployment.

**Comment by khoidt** [comment]
@runjak thank you!
