### ISSUE TITLE
Minor but urgent changes to the [Languages Reference] form.

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#224]
### Priority Level 0
- [x] The Search/Filter box for the `Display Name` is not working. Type any letter, and all languages disappear from the list.  Is it searching in a different (old) field?
- [x] Here and in all forms that have it, make the clade filters part of the header section that stays visible on scrolling down. The 'Save' button especially must remain visible at all times -- this is very urgent. But so should the whole header bar, so do it that way.

### Priority Level 1
- [x] Add the clade colour sidebar as on the [1-Meaning, All Languages] form, which is very useful here too, so that people not logged in as admin can differentiate levels Cl 0 -- e.g. Nuristani vs. Iranic vs. Indic.

### Already Done:
- [x] Hide the column `URL name` for all users.  Now that we have made our corrections, this too will not ever change much, and is taking up unnecessary horizontal space on this form.

**Comment by runjak** [comment]
It appears that the filter for `Display Name` was broken in ec7add566c2d15b1b12ba1e53c9c26fd8cef187d during a mobbing session.
I've developed a fix for it that will be deployed soon.
