### ISSUE TITLE
Eliminate loanwords from all cognate sets

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#228]
We now have data for lexemes which are still marked as loanwords in the database, `Jena 200` meaning list, `Current` language list, and there are an awful lot of them [Loanwords.txt](https://github.com/lingdb/CoBL/files/367592/Loanwords.txt).

The dating problem https://github.com/lingdb/CoBL/issues/202 is now solved, so it is a fairly urgent priority to eliminate these, according to our established policy.

I suggest first working through the outstanding cases that you have identified, and then checking meaning by meaning with the tools on the `1lg, all cog sets` html form. When you think you have got them all, we can ask @runjak to compute the statistics again to see if they have all been eliminated.

**Comment by nitsnatsnok** [comment]
As we have now no loanwords in the database any more, the columns “Lex. Loans” and “Lex. Loan %” in the /cognateclasslist/ and “Lex. loan” in /language/ and /meaning/  became useless and should be removed, @runjak.
