### ISSUE TITLE
Fill in missing web dictionary links in some languages

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#235]
Languages that should be fully entered are nonetheless missing about 10% of links to the corresponding web dictionaries.  These need to be completed (by Laura Wägerle, for example?) -- **using the >> copy othographic entry button** wherever possible, rather than just typing again.

Languages that have this problem include:
- [x] Ancient Greek
- [x] Persian: Tehran
- [x] Lithuanian
- [x] Bulgarian
- [x] Slovenian
- [x] Gothic
- [x] Old Norse
- [x] Danish
- [x] Dutch
- [x] English
- [x] Latin
- [x] Friulian
- [x] French
- [x] Spanish
- [x] Old Irish
- [x] Gaelic: Irish

All languages that have an entry for the Web Path need to be checked for this:  these languages are:
![screenshot - 2016-07-22 10_56_31](https://cloud.githubusercontent.com/assets/8819910/17051844/00c999b4-4ffb-11e6-9226-8e0b89492b6d.png)

We also need Jakob to programme …
- [ ] A broken link checker for all entries for a given language.  Perhaps a clickable icon together with the header for this column?

**Comment by runjak** [comment]
As far as I understand this issue is about linking individual languages/lexemes to some entries in online dictionaries. It is not about our source/citing system -> therefore I'll remove that label.

**Comment by nitsnatsnok** [comment]
It's my task to add dictionary links to the database, so I'm keeping track of my work here.

- [ ] [Danish](http://www.cobl.info/language/Danish/wordlist/Jena200/): finished and tested, except for YOU_PL., where the link is more complicated: [http://ordnet.dk/ddo/ordbog?**select=I,4&**query=I](http://ordnet.dk/ddo/ordbog?select=I,4&query=I) – @cormacanderson: Is there already a way to enter this?
- [ ] [Greek: Ancient](http://www.cobl.info/language/AncientGreek/wordlist/Jena200/): finished and tested, except for FEAR δείδω, which has no entry in the LSJ (see [here](http://www.perseus.tufts.edu/hopper/morph?l=dei%2Fdw))

**Comment by nitsnatsnok** [comment]
Other languages I work(ed) on:


- [Persian](http://www.cobl.info/language/Persian/wordlist/Jena200/) should rather be done by anybody who's able to read the Arabic script
- [Lithuanian](http://www.cobl.info/language/Lithuanian/wordlist/Jena200/):
 - [x] completed except for the following lemmata, which I couldn't find in the dictionary:
   - COUNT (su)skaičiúoti, DIRTY pur̃vinas, HERE čià, LOUSE utėlė̃, NOT ne-, ROTTEN supùvęs, THINK galvóti
 - [x] tested & corrected
- [Bulgarian](http://www.cobl.info/language/Bulgarian/wordlist/Jena200/): I corrected the (obsolete?) dictionary link.
 - [x] completed except for the numerous lemmata which seem to have no entry in this dictionary (or I'm not able to find it) – as this is nearly a fifth of the lexemes it could be worth trying another dictionary and/or have the unlinked lexemes checked by an expert
 - [x] tested & corrected
- [Slovenian](http://www.cobl.info/language/Slovenian/wordlist/Jena200/): I corrected the broken dictionary link (404). The dictionary works with unique IDs for every lexeme, which makes it very time-consuming.
 - [ ] completed
 - [ ] tested & corrected

**Comment by leszekjocz** [comment]
@nitsnatsnok 
As to Bulgarian the reason is trivial. Your 'non-obsolete' dictionary is just not finished yet, so every word beginning from the letter 'r' (from somewhere in the middle of this letter) can not be found there because the further volumes don't exist in our universe.
I was worth to check or to consult it with me before you started changing 'obsolete' links...

**Comment by nitsnatsnok** [comment]
@leszekjocz I'm really sorry, unfortunately I don't know who the language/branch experts are, but the old link seemed totally(!) broken to me, so having at least four fifth of the lexemes linked correctly is an improvement by any means, isn't it?

**Comment by CasFre** [comment]
As for the question of language experts:
The best overview is provided by http://cobl.info/languageprogress/Current/.

**Comment by leszekjocz** [comment]
The Bulgarian dictionary you found would be really a perfect solution if it would be finished.
Links to a dictionary, as far as I can understand, are just a useful, utilitarian feature for end-users who are not specialists. How much useful it is if the fifth of the links are missing? Further, it can just look strange and cause 'stupid' question or unjustified doubts in the case of a modern language.
The only full online dictionary I know is https://rechnik.chitanka.info/. It is full and works fine. A disadvantage is that it is not entirely clear what the sources of the dictionary are (however, the definitions etc. look professional, it looks like it is based on credible sources).

**Comment by nitsnatsnok** [comment]
Thank you, I take this one then and adapt the links where necessary.

If anybody knows reliable online dictionaries for other languages as well this would be a good moment to enter or communicate them.

**Comment by nitsnatsnok** [comment]
Further languages checked today:
- [Gothic](http://www.cobl.info/language/Gothic/wordlist/Jena200/): I optimised the dictionary link.
 - [x] completed except for the following lemmata, which have no entry in the dictionary:
    - EGG ada (isn't this just Crimean Gothic?), FOREST waldus, FREEZE *friusan (but the corresponding noun _friusa_ on page [039.html](http://www.wulfila.be/lib/streitberg/1910/html/B039.html)), ICE *ei-s, SWELL *swilan
 - [x] tested & corrected
- [Old Norse](http://www.cobl.info/language/OldNorse/wordlist/Jena200/): running discussion on the dictionary in #338
 - [ ] completed
 - [ ] tested & corrected
- [Dutch](http://www.cobl.info/language/Dutch/wordlist/Jena200/):
 - [x] completed except for:
    - VOMIT overgeven, which has no entry in the dictionary – it doesn't seem reasonable to me to add a link to _geven_ ‘to give’ because of the semantic difference
 - [x] tested & corrected
- [Latin](http://www.cobl.info/language/Latin/wordlist/Jena200/):
 - [x] completed
 - [x] tested & corrected

**Comment by tonyakdewey** [comment]
For Gothic, I would prefer to avoid Crimean Gothic, since its date of attestation is centuries after Biblical Gothic, and the data is very suspect.

**Comment by nitsnatsnok** [comment]
That's exactly what I think about it, but as a student assistent it is neither my decision nor my task to edit or even delete lexemes – Cassandra Freiberg [seems to be](https://github.com/lingdb/CoBL/issues/337#issuecomment-257142630) working through the data currently and will certainly correct things like that.

**Comment by nitsnatsnok** [comment]
Four languages remain:

- [Old Norse](http://www.cobl.info/language/OldNorse/wordlist/Jena200/): [discussion on the dictionary](https://github.com/lingdb/CoBL/issues/338)
 - [x] completed
 - [x] tested & corrected
- [Friulian](http://www.cobl.info/language/Friulian/wordlist/Jena200/): 
 - [ ] completed
 - [ ] tested & corrected
- [Old Irish](http://www.cobl.info/language/OldIrish/wordlist/Jena200/): 
 - [ ] completed
 - [ ] tested & corrected
- [Gaelic Irish](http://www.cobl.info/language/GaelicIrish/wordlist/Jena200/): 
 - [ ] completed
 - [ ] tested & corrected

**Comment by nitsnatsnok** [comment]
I got in contact with the experts for Friulian, Old Irish and Gaelic Irish and made sure the dictionaries we have are the best possible.

**Comment by nitsnatsnok** [comment]
As to the broken link checker proposed in the first comment I don't think this would be very helpful, as most of the online dictionaries I worked with here actually show a page when the link ist not correct – mostly something like “nothing found”. A broken link checker as far as I know would not detect those cases, and the dictionaries in general vary a lot in the treatment of wrongly entered search terms.

**Comment by nitsnatsnok** [comment]
Most of the links for Persian: Tehran were set up by somebody else, so I close here. #341 deals with links for further languages.
