### ISSUE TITLE
Let filters survive

### ISSUE THREAD

**Issue by runjak** [lingdb/CoBL#239]
When filtering the tables except for the clades all filtering and sorting is forgotten once a user navigates. It would be good for these filters/sorts to be remembered for the session so that a user doesn't have to reenter the same filter several times.

**Comment by PaulHeggarty** [comment]
Diverted from #222 (so that could be closed), since it's a part of this issue now.
- Preserve the sort for `1-Meaning, All Languages` view even when switching to a new meaning (by the next or previous meaning links, or by typing in the meaning name header, or indeed when swtiching between views).
