### ISSUE TITLE
Check clade inference for cognate classes

### ISSUE THREAD

**Issue by runjak** [lingdb/CoBL#240]
@CasFre mentioned to me that cognate class `2444` shouldn't have a connection to `Celtic` any longer but it appears to have one.
See
* http://www.cobl.info/cognateclasslist/ for `round`
* http://www.cobl.info/cognate/2444/

**Comment by CasFre** [comment]
Hello @runjak,
Maybe this second instance can provide some cue for solving this issue:
In the statistics that you generated for me cognate set 347 is registered as one that contains lexemes from Italic/Romance, Germanic and Albanian:

> Cognate set id: 347 meanings: "forest" branches: "Albanian", "Italic, Roman", "Germanic, North-West, West"

And this is also what the colour coding displays, but curiously not what the new clade count and the lexemes count display:
![clade inference_cogcl 347_i](https://cloud.githubusercontent.com/assets/17431124/17170099/f301f7f6-53ea-11e6-9c8f-1855149c6e48.png)

And if one accesses the cognate set page for 347, there are only 10 lexemes in it and these are all Romance, so the two counts seem to give the correct reflection of what's in there.
As for the clade inferences with the colour boxes and the underlying code which was apparently also used for the statistics, I don't know how the Albanian came in, but for the Germanic lexemes, an explanation might be that they have been moved into new loan word cognate set 5795 for which 347 is the source set:

![clade inference_cogcl 347_ii](https://cloud.githubusercontent.com/assets/17431124/17170235/710c5bbe-53eb-11e6-93d0-7a59a1c5f372.png)

**Comment by runjak** [comment]
Thanks, @CasFre I think I found the bug for this.
When computing whether a cognate class connects to a given clade the computation looked at all languages that related to a clade instead of only considering the languages for the current language list.
