### ISSUE TITLE
New field needed in cognate sets table, and [1-Meaning, All Cognate Sets] form

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#247]
This is something discussed months ago, but I’ve only just 2016-07-29 realised has not yet been (fully?) implemented, it seems.
- [x] Cognate sets need a new field:  `Loan Source Cognate Set ID`. It is to have the same format as the number that is the Cognate Set ID field, because it will be used for cross-referencing between such fields.
This will only be used in cognate sets that are defined by a loanword event (i.e. with that Boolean variable set to true).  So it too should be one of the fields whose editability is to be set by #210. (But this editability restriction is not so urgent.)
- [x] This field needs to appear as a column in the `1-Meaning, All Cognate Sets` form.  It should appear immediately after 
- [x] The entry in this column should also work as a live hyperlink to the cognate set page for the number entered here.
- [x] Hovering over the link should display the basic cognate set reference fields for the cognate set ID that it offers a link to.  These reference fields are the same as those now being implemented in the drop-down box for assigning a lexeme to a cognate set.  As a minimum, the `Alias letter`, `Root Form` and `Root Language`.

Note:  only one such field and entry is needed per cognate set, because this will only be used for loan events from a clearly identified single source cognate set.  
This field will only be used if the source happens to be within our data set, of course.

**Comment by runjak** [comment]
The field `Loan Source Cognate Set ID` already exists in the `1 meaning all cognate classes` table. It was renamed to `Source ID`, but still has the right hover text. It is also used to save either the ID of a cognate class or an empty string. Because of this I'll mark the first two items as solved.

**Comment by PaulHeggarty** [comment]
Good, I thought we had done this, I was just being blind and couldn’t see it!  But there is no hover text for me, neither in Firefox nor in Chrome.
In fact, often (but not always) the link will be to another of the cognate sets on the current view, so it would be worth showing also the alias letter, if possible, as another column immediately before this one.

**Comment by runjak** [comment]
Yes - I'm working on that - the link to the cognate class and a hover text for it.
I just meant that the title of the column has a hover text that reads `Loan Source Cognate Set ID` :)

**Comment by runjak** [comment]
I've implemented the links and they look like this:
![screenshot_2016-08-01_09-48-00](https://cloud.githubusercontent.com/assets/5417642/17286958/171a0e72-57cd-11e6-8b8f-6d62e4be1ac4.png)

I'll now make sure to deploy the code for this.
