### ISSUE TITLE
A new 'Unassigned' count in the [Languages Reference] form 

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#255]
The `Languages Reference` form needs a new column, for a count of how many lexeme entries in that language are **not** marked as `Not Swh.` and are not assigned to any cognate class (i.e. do not have a Cog. ID number entered), i.e. for which there is no corresponding entry in the cognate judgements table, I presume.  This is the same as the total count of lexemes for which the ``Check`` function returns rows with a 0, provided that does not include meanings marked as `Not Swh.`

**Comment by cormacanderson** [comment]
Related is https://github.com/lingdb/CoBL/issues/214

**Comment by cormacanderson** [comment]
On the languages references table please also reorder the counts from left to right as follows:
`Meanings`
`Lexemes` (rename the current `Entered`)
`Swadesh` (rename the current `Swh lex.`?)
`Not Swh`
`Too many`
