### ISSUE TITLE
Create a new view:  [2 Languages, All Meanings]

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#256]
This will be essentially a clone of `1-Language, All Meanings` view, except that the filter is amended so that instead of filtering lexemes by Lg=x, it's filtered by Lg=x or Lg=y.  

That language y is whichever is the reference language for the clade to which Language x belongs, i.e. the language in that clade that has its `Ref. Lg` boolean set to true in the `Languages Reference` form.

The aim of this form is to massively speed up cognate coding, in the many cases where a language specialist enters just one language for us.  The idea is so that the coder can see all meanings in that single target language, but also, immediately underneath as the next record, the lexeme entry for that same meaning in the reference language for that clade.  In most cases, they will share about 80% of cognate assignments, so those 160 or so lexemes can all have their cognate status assigned without ever having to leave this form, or click to look up the list of cognate classes for that meaning.  

Obviously, this will only work after #219 is finished, particularly copying over the new system for assigning cognate classes from `1-Meaning, All Languages` to `1-Language, All Meanings` too.  Because that new system will then also need to be cloned over into `2-Languages, All Meanings`.  Ideally, there would also be one new button in this `2-Languages, All Meanings` form, only to appear on the records for the Target (not the reference) language, which would just be 'Copy over cognate class assignment from Reference language'.  That would be its tooltip, and it should do what that says.

We might have to adjust the background colour shading system...  One to discuss.

The sort order for this `2-Languages, All Meanings` form would be by meaning name `ascending`, and then (following sort term) by language `Sort  Index` (since the clade values will be the same anyway), but this I’d propose `descending`, because the reference language is almost always first in its clade, but we'd want its to appear underneath, rather than on top of, the target language.

**Comment by CasFre** [comment]
I would opt for more flexibility and not just have a 2 languages - all meanings view but the possibility to split the screen and to have whatever two different views opened in parallel, e.g. also the 1 lang - all mean and the 1 mean - all cognate sets pages.

**Comment by PaulHeggarty** [comment]
Anyone can already just open two webpages in different browser windows to do this.  
I also expect that what you request will be a big reprogramming task, and take too long when we need something as soon as possible.  Jakob, please concentrate on the original request, as discussed yesterday in the car too, and detailed above.

**Comment by runjak** [comment]
@PaulHeggarty the link for `Sort Index` in the issue description is broken.
Could you clear it up so that I know what should be linked?

**Comment by runjak** [comment]
I've got a table with data for two languages present:
![screenshot_2016-09-08_12-17-23](https://cloud.githubusercontent.com/assets/5417642/18346072/c7845222-75be-11e6-86a6-ead753be8bf8.png)
In this table it is possible to edit all data for one language while getting the data for the other displayed as well.
Both languages can be changed via the same ways as in `1 language all meanings` view.

**Comment by PaulHeggarty** [comment]
Looking good!  Most important would be to be able to see which language is which more easily and directly.  Could you put the second (uneditable) language rows with a pale grey background, and the selection header box for it also with that background.  (Forget the other row background shading system, it's not needed in this view.)

**Comment by runjak** [comment]
Good point - I can see that it's useful to distinguish the rows.

**Comment by runjak** [comment]
I think this feature is ready for deployment now.
I will deploy it when I have access to the server again.

**Comment by runjak** [comment]
This feature is now deployed on the server.
