### ISSUE TITLE
Historical Languages

### ISSUE THREAD

**Issue by m-scarborough** [lingdb/CoBL#257]
Two observations: 

1) In the languages list, Palaic should be checked as a historical language.  (Palaic was already a historical language by the time of the Hittites!)

2) Should Tsakonian Propontis not also be checked as a 'historical language', as Dalmatian, Polabian, etc.?  According to Wikipedia it is thought to have died out around 1970: https://en.wikipedia.org/wiki/Tsakonian_language#Geographic_distribution — Nikos please correct us if this is wrong.

**Comment by cormacanderson** [comment]
Well spotted Matthew. It's strange though, because I thought Palaic had already been corrected. I gave it 3500BP SD100 for now, but @MatildeSerangeli could you please advise on a dating (and also check those for the other Anatolian languages)?
@NikosLiosis for Tsakonian Propontis

**Comment by PaulHeggarty** [comment]
The reason Palaic was not checked was simply because we couldn’t check it without having dates to put in.  When we introduced this cross-check system, Matilde was due to be asked to specify the dates, but did not ever respond, as far as I’m aware.

**Comment by NikosLiosis** [comment]
You are absolutely right, Matthew. The Tsakonian dialect of the Propontis is now extinct. Cappadocian Greek will follow soon.

**Comment by PaulHeggarty** [comment]
So our date fields for it need to be entered in the `Languages Reference` form, please.  You need to give us a date for when your lexeme data were valid.  And express it in years Before Present.  In this case, it's so recent that we do not need a standard deviation estimate.

**Comment by PaulHeggarty** [comment]
Matthew, please remember to put our type labels on all issues.  Thanks.

**Comment by NikosLiosis** [comment]
Then 40 years BP is the best estimation

**Comment by PaulHeggarty** [comment]
One of the advantages of using Type labels is that this issue need not have been created separately, but just covered by additions to #226

**Comment by PaulHeggarty** [comment]
Closing this now, as other queries on this theme should be put into #226
