### ISSUE TITLE
Check lexemes assigned to multiple cognate classes

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#259]
I go through the statistics in 4.txt on #225 and revise these lexemes:
Why are they assigned to more than one cognate class?
Are they correctly assigned? If not, I delete the wrong assignment and possibly double/empty cognate classes.
The double assignment should be kept only in special cases where there are good reasons for this.

**Comment by CasFre** [comment]
#227 

Are these the same as those in this other list?

**Comment by cormacanderson** [comment]
Yes. Closing this issue and copying @nitsnatsnok 's comments to there.
