### ISSUE TITLE
Set of new fields for Cognate Sets

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#263]
The mobbing session just before we finished today 2016-08-04 will result in a set of new boolean fields for cognate sets, to appear on the `1-Meaning, All Cognate Sets` form.

The others I referred to but we did not get round to inserting the blanks for are:
- [x] A `Revised Yet?` boolean check box.
- [x] A `Revised By` text of two characters, for the initials of the reviser.  Sorry, 'MJCS', ;), but horizontal character space is at a real premium on this form. (Ultimately this should be merged into the Contributor system, but not a priority for now, let's just do initials.
- [x] The red warning triangle alongside meanings in the `1-Language, All Meanings` form should have the tooltip 'Special care and attention needed with this meaning.  Please click on the i icon to read the full specification of the precise comparison meaning intended, and the exact term required here.'
- [x] The `Exclude?` check box in the 'Meaning Reference' form should also be completely hidden for non-admin users.
- [x] Could you also please put one of the light vertical bars between "Dubious Set" and "Loan Event" in this html form, and another one between "Loan Notes" and "Revised yet?"
- [x] Correct the spelling of "Idiophonic" to "Ideophonic".

**Comment by PaulHeggarty** [comment]
Just to confirm where this fits in:  this should presumably go in with the batch of other new boolean fields that we 'mobbed' with you just now, and go into the same redeployment tomorrow.   
 
The other thing to finish with this batch is the revised 3.md files where the higher clade level versions are with set intersections rather than set unions of the lower clade level components.

**Comment by runjak** [comment]
I've just finished cleaning up the results from yesterdays session with commit ac0c884.
And will now see to add the requested features.

**Comment by runjak** [comment]
I've implemented the warning triangle.
It will appear when the meaning is marked as `Double check`, and looks like this:
![screenshot_2016-08-05_13-43-06](https://cloud.githubusercontent.com/assets/5417642/17435654/9bbc5282-5b12-11e6-9ffc-b7f41fe56a50.png)

**Comment by CasFre** [comment]
Okay, I saw the definitions provided by the hover-buttons which might do for the moment.
Yet I don't get what "parallelDerivation" is intended to mean.
If we say that we mark this checkbox if we have in a cognate set lexemes from one and the same root which however show different derivations in different clades, then we would have to use this checkbox quite often and not only for quirky cases as the pronominal meanings.
I refer back to the root form policy that was established some months ago:
https://github.com/lingdb/CoBL/issues/149

**Comment by PaulHeggarty** [comment]
The two new fields on the `1-Meaning, All Languages` page and `Meanings Reference` page will be handled exclusively by Paul and Cormac.

**Comment by PaulHeggarty** [comment]
Jakob, a new check-box point added above, I’m afraid.

**Comment by cormacanderson** [comment]
@CasFre the two fields on the `Meanings Reference` page are intended 1) to flag potentially problematic or radically changed meaning specifications for the data entry coders, and 2) to mark those meanings we think should perhaps be excluded from export by merit of being too problematic.
As for the new fields on the `1 Meaning, All Cog Sets` form, I will write these descriptions up into the wiki shortly.

**Comment by PaulHeggarty** [comment]
Sorry Jakob, one more tiny new check-box point above that has just occurred to me.  Sorry for messing you about!

**Comment by runjak** [comment]
I've made the requested changes. This issue will be closed on deployment.
