### ISSUE TITLE
Meaning [Hair]

### ISSUE THREAD

**Issue by tonyakdewey** [lingdb/CoBL#276]
If I have one lexeme specifically meaning 'hair on the head of a human being', and another meaning 'hair (in general, not necessarily on the head or on a human)', should I take the more general one? (The cognates of the more specific one refer to horses' manes in the other Germanic languages, which is why I'm leaning towards the more general.)

**Comment by cormacanderson** [comment]
I think normal policy is to take the more general meaning. If it were the situation that there were one term for human hair and one for animal hair, I would take the human hair though.

**Comment by tonyakdewey** [comment]
Cool. Thanks.  Double checking revealed that the 'hair on the head of a human being' only shows up in poetry, anyway, so that's another reason to go with the general one.
