### ISSUE TITLE
Add [root reference form] and [cog. alias] to individual cognate set pages

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#293]
- [x] The `root reference form` as it appears in the `1 Mng, All Cog Sets` form should also appear at the top of the pages for individual cognate sets, beside the `Cog Class No`.
- [x] The `Cog. alias should also appear there.

**Comment by runjak** [comment]
Here's an interesting thing I stumbled upon:
* Cognate sets have a name field that can be used to set a specific name.
Per default this field is left empty, and without some guessing of URLs I don't think it's possible for a user to reach this functionality at the moment.
Statistics on this show that this feature is rarely used:
![screenshot_2016-09-09_14-43-11](https://cloud.githubusercontent.com/assets/5417642/18387276/ffdf2ace-769b-11e6-8cca-e8a315ccd0c9.png)

Why I'm bringing this up here:
* I'll need to adjust the code for editing the notes on a cognate set to add editing for the `root reference form` and make it easier to adapt than the current form. So it would be a good place to add editing for the name as well.
* If we don't want to use the `name` field I suggest that we remove it from the code. I don't think that it's used anywhere else on the site.

**Comment by runjak** [comment]
Oh - you can actually get to the functionality as a user via the `name this cognate class` link. Not sure if we want to keep this though.

**Comment by runjak** [comment]
I've got an implementation for this that will present the cognate set form like this:
For a logged in user:
![screenshot_2016-09-09_15-39-27](https://cloud.githubusercontent.com/assets/5417642/18388892/b90f5076-76a3-11e6-8dca-c2ae76d7963c.png)
For a visitor:
![screenshot_2016-09-09_15-39-37](https://cloud.githubusercontent.com/assets/5417642/18388893/b915a548-76a3-11e6-90a3-4aef6b36e7c8.png)

This issue will be closed on deployment.
