### ISSUE TITLE
[Meaning] PULL

### ISSUE THREAD

**Issue by tonyakdewey** [lingdb/CoBL#295]
The definition and the example sentence here would lead me to two different conclusions for a language like Icelandic. Based on the definition, I would choose _toga_ (which is what is on doors, for example, indicating pull vs. push), but based on the example sentence I would choose _draga_ (what I would use to translate that sentence). Can we clarify?

**Comment by PaulHeggarty** [comment]
See the revised meaning definition at:
https://github.com/lingdb/CoBL/wiki/pull
