### ISSUE TITLE
Problem adding new lexeme

### ISSUE THREAD

**Issue by tonyakdewey** [lingdb/CoBL#297]
I'm trying to add the correct lexeme for Old High German 'turn' (there are two in there now, neither of which is the right one).  I created the lexeme, and got a message at the top of the page that it has been created, but I can't see it, either when I view all meanings for Old High German, or when I view 'turn' in all Germanic languages.  Help?

@runjak, @cormacanderson

**Comment by cormacanderson** [comment]
This has happened to me a couple of times. Generally, if you try again a second (or occasionally even third) time it works. If you really can't get it working, then for now email me the ones you want added and I will try to do it. It was working okay for me yesterday.

**Comment by tonyakdewey** [comment]
Now it's working for me if I add the lexeme from the one meaning all languages page rather than the one language all meanings page.  It's working fine from both pages for @findell. We'll also try and see if it works for me logged in on his machine.

**Comment by tonyakdewey** [comment]
Further update: It works for me now on my machine using Safari rather than Chrome.  So I've got a couple workarounds, and you can get onto other more pressing issues.

**Comment by runjak** [comment]
This could likely be an issue with cached scripts in the browser.
It may be possible that the problem can be solved by [clearing your browser cache](http://www.refreshyourcache.com/en/home/).

**Comment by runjak** [comment]
Please reopen if I'm wrong but it's my understanding that this issue didn't come up again since 2016-08-17.
Closing since the symptoms sound very much like a caching problem and this type of problem was dealt with in #354.
