### ISSUE TITLE
Fix calibration visualisation tool

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#309]
This has not been working recently. This would be worth asking @xrotwang about during Glottobank.

**Comment by PaulHeggarty** [comment]
Please also double the vertical pixels taken up by the vertical y axis -- we always view this in a separate tab in any case, so there's plenty of room, and it would make things much clearer and less cluttered.

**Comment by runjak** [comment]
So far, I've:

* Fixed the Bug where no plot was rendered.
This may need a cache clear to work properly. Also rendering the plots takes some time - like half a minute to complete. During this time the browser tab won't respond. There is a way to improve this, but it's not currently done.
* I've also doubled the height of the chart.
