### ISSUE TITLE
Output CSV file of language iso codes

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#310]
We need (urgently) a very simple CSV file for all languages in the languages reference table, of the format,
utf8name, ISO
I.e. just two fields, separated by a comma.  If the ISO is blank, just leave a blank.
Ultimately we could do with a button to export this, but it is *not* needed now, Remco just needs the CSV file.

**Comment by runjak** [comment]
In case this is necessary again:
I've created the export with this command:
```
COPY (SELECT utf8_name, iso_code FROM lexicon_language
          WHERE iso_code != '' ORDER BY utf8_name)
TO '/tmp/export.csv' WITH CSV DELIMITER ',';
```
The output was sent per mail.
