### ISSUE TITLE
Add new rows to nexus export file for diagnostics

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#314]
We often need to do cross-checks of the export nexus files by wading through seas of 1s, 0s and ?s.  To make it infinitely more efficient and less error-prone, we need a better guide system than the current indications of just character numbers from 1 to 5000+.

Corresponding to the information in this part of the file, which shows which columns of the main 01? block correspond to which meanings ...  

![screenshot - 2016-09-30 10_50_40](https://cloud.githubusercontent.com/assets/8819910/18987597/988902ba-8702-11e6-9287-acfe4b72eb84.png)

… the NEW lines we now need can be seen here:

![screenshot - 2016-09-30 11_22_31](https://cloud.githubusercontent.com/assets/8819910/18987181/bf672ae4-8700-11e6-9ea1-3933bd655595.png)

Also repeated at the bottom of the block (to look upwards too, since the language list is too long for one screen).  

![screenshot - 2016-09-30 11_22_48](https://cloud.githubusercontent.com/assets/8819910/18987184/c2087154-8700-11e6-8dab-9ace1fa563cc.png)

In other words …

- [x] A row indicating the meaning that corresponds to each block of 01? columns, per meaning.  Because each block of columns per meaning is preceded by the `group` column, this allows for a 'leading' space before the meaning name starts.  Usually the meaning name will be a lot shorter than the number of cognate sets for that meaning, so it can be written out in full and padded out with spaces up to the start of the next meaning block.  Unusually, there may be so few cognate sets, as in the meaning 'two', that the meaning name will have to be truncated as necessary.  In the case of the meaning 'two', with just a single cognate set, it will be truncated to Mid$("two",1,1), i.e. just the first letter 't'.

- [x] A row indicating by C or L whether the column corresponds to a cognate set (C) or a singleton lexeme (L).  In due course all cases of L will in fact be eliminated from the database, but we need to keep this as a fail-safe.  Again, thanks to the `group` column, we get a column of blanks between each meaning block, vital for saving our eyes!

- [x] Five rows to give the ID number of the cognate set or singleton lexeme that corresponds to that column.  Five rows are needed because singleton lexeme numbers go up to five digits now, i.e. we have more than 10,000 lexemes in the database.  And rows, because (stupidly, but we have no option) each single column corresponds to a different cognate set, so we have to write out the cognate set ID numbers vertically, not horizontally.  So for example cognate set ID number 1452 becomes ...
   - 
   1
   4
   5
   2
Note the leading dash, corresponding to the leading zero in 01452.  It needs to be done this way, to keep the thousands and hundreds properly aligned.  Please use dashes rather than zeros, it's easier to read.
Again, thanks to the `group` column, we get a column of blanks between each meaning block.

I know, this is a rather silly faff, and I’d probably do it by converting the number 1452 to a string "-1452", and then output as Mid$("-1452", [row number], 1).  BUT it will absolutely transform our ability to read these things, which is critical for our quality control tasks.  

Since this should only be comment blocks, I think it should be fine if it goes out in all versions of the file, including the Beauti version.

**Comment by runjak** [comment]
I've got an implementation of this that I can soon deploy.
It looks similar to this screenshot:
![screenshot_2016-10-05_17-30-09](https://cloud.githubusercontent.com/assets/5417642/19119915/8f987014-8b21-11e6-945e-dc6bb7320d17.png)

If it's not explicitly required I'd hesitate to add the comment text in the comment lines because it complicates calculation of the indentation.

**Comment by PaulHeggarty** [comment]
This looks great.  The comment lines are not needed for our immediate purposes, although when we fully 'go public' (but for the export function that might not be for a long time) we should include them.  

For now, though, one thing would certainly be good, which is to leave blank lines before and after the block of five lines that give the vertical cognate set number.  That will make them much easier to read, especially to distinguish them from the first row of 1s and 0s.  If you can fix that, then you can deploy this.
