### ISSUE TITLE
Add data tables export function (for admin super users only)

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#317]
A few weeks back I asked for a download of all data tables, which Jakob did as a zip.  It turns out that I will need to do this more often than I thought, and sometimes perhaps urgently.  So it would be better if there were part of the admin system where super users can download these zips on demand.  For now, that means just Paul, Cormac and Jakob.

**Comment by runjak** [comment]
I've implemented this feature.
Once it's deployed staff users will see a menu item that allows export of .csv files:
![screenshot_2016-12-19_15-14-40](https://cloud.githubusercontent.com/assets/5417642/21315766/fcfbaff6-c5fd-11e6-8843-c59c167769f5.png)
Clicking this link will trigger a server side request, that will:
1. Check if the user is staff
2. Create .csv exports for most tables
3. Create a .zip from the .csv files
4. Offer that .zip file to the user
