### ISSUE TITLE
Add delete option for nexus export files

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#318]
- [x] Add a button to delete a given export set (ie of the three nexus files output with each export).  Clicking on it should first ask for confirmation by saying:  "Are you sure?  Please delete only if an export was done with erroneous settings.  Otherwise, keep every export as a record of all analyses performed."

**Comment by PaulHeggarty** [comment]
Just added two points that have occurred to me -- a bit late, sorry!

**Comment by runjak** [comment]
I've already marked this issue to be closed when commit e7935e1 is deployed.
For simplicity and because the additional tasks are separate from the delete option I'll split them off into a separate issue.
