### ISSUE TITLE
Allow deletion of last citation for "lexical judgement" and "cognate judgement"

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#322]
Currently, although it is possible to enter a new lexeme without giving a citation, it is not possible to delete the last lexical or cognate judgement citation associated to an existing entry. It should be possible to do this in the database.

**Comment by khoidt** [comment]
I've inspected the issue and discovered a protection against removing the last relation in the template:

```
                {% if lexeme.lexemecitation_set.count == 1 %}
                  <div class="btn btn-danger"
                       title="Can't delink final citation">
                    <span class="glyphicon glyphicon-tag"></span>
                    <span class="glyphicon glyphicon-remove-sign"></span>
                  </div>
                {% else %}
                  <a href="{% url 'lexeme-delink-citation' lexeme.id citation.id %}"
                     title="Delink citation"
                     class="btn btn-danger">
                    <span class="glyphicon glyphicon-tag"></span>
                    <span class="glyphicon glyphicon-remove-sign"></span>
                  </a>
                {% endif %}
```
I can remove this protection, of course, but as it seems to be there for a reason, it makes sense first to get a bigger picture. @runjak (in case it's your code), do you happen to know why it's protected like this?

**Comment by runjak** [comment]
@khoidt good thinking but as far as I can tell this should be leftover code from Michael.
I believe that I touched it to adjust formatting but otherwise I don't know of any reason for keeping the last citation.

From my perspective we could remove this safeguard for the next deployment.

**Comment by runjak** [comment]
@khoidt I've just pushed commit 8724deb to `devel`, which makes removal of the requested LexemeCitation and CognateJudgementCitation entries possible.

**Comment by runjak** [comment]
Commit 8724deb has just been deployed.
