### ISSUE TITLE
Root Ref Language filter box broken

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#323]
On the `1-Meaning, All Cognate Sets` page, the `Root Ref Language` filter box does not seem to work.

**Comment by cormacanderson** [comment]
I wonder is this connected to https://github.com/lingdb/CoBL/issues/324?

**Comment by runjak** [comment]
I've found a problem with this where the page wouldn't render correctly if the user wasn't logged in. For a logged in user everything worked as expected in Firefox and Chromium on `cobl.info`.

**Comment by PaulHeggarty** [comment]
It does now work for me, although one part of the behaviour seems inconsistent.  

On this page, for example:
http://www.cobl.info/meaning/go/cognateclasslist/

… where placeholder texts are filled in, the filter/search works for single language placeholders, such as (Albanian), but does not work on clade placeholders, such as the (CelticGoidelic) branch.  

Indeed the single language placeholders are not greyed out, and can be selected.
Meanwhile, the clade placeholders are greyed out, and cannot be selected.

- [ ] Can the behaviour of clade placeholders be made the same as the current (more powerful) single language placeholders?

**Comment by runjak** [comment]
I think the open problem here is about abilities to filter cognate classes by their clades?
In that case it would be similar to #172 I believe.
From looking at the issue description at the top I get the impression that this issue is already closed.
Please help me understand the missing part otherwise.

**Comment by runjak** [comment]
Closing because I think this is solved and no contrary information came in during the last week.
