### ISSUE TITLE
Cannot make changes to some cognate sets on [1 meaning, all cog sets] form

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#324]
An error message appears when trying to edit information on the `1 meaning, all cog sets` html form. See the screenshot below:
![screen shot 2016-10-13 at 16 16 57](https://cloud.githubusercontent.com/assets/8975419/19352664/ed7b3168-9160-11e6-8f52-5983934df20f.png)
This occured after trying to update set Ab. Trying to update another set on the same page also failed. However, I was able to update cognate set F [here](http://cobl.info/meaning/fish/cognateclasslist/).

**Comment by cormacanderson** [comment]
I already did some testing to try to identify the problem:
1) Unchecking the "Not in export" and "Doublecheck" buttons for "child" on the `Meanings reference` html form made no difference
2) Deleting all the citations from the cognate and lexical judgements and reassigning myself made no difference
3) Deleting the cognate set and reassigning the lexemes to a new cognate set made no difference

**Comment by runjak** [comment]
Investigating.

**Comment by runjak** [comment]
OK, so the page for Fish should render again as of now.
I've performed some changes to the data in the `1 meaning all cognate sets` table on my machine and couldn't reproduce further problems.

@cormacanderson could you try again if this problem still persists and help me with a description of the steps that produce it?

**Comment by cormacanderson** [comment]
This problem persists. Go to the meaning "Child" on the `1 meaning, all cog sets` html form, and try to change something, e.g. mark cognate set Ab as a parallel loan. If I do this, I see the error message.

**Comment by runjak** [comment]
Alright - thanks for pointing out the steps to replicate!

**Comment by runjak** [comment]
The problem here was a bug in the validation of the form data on the server side.
We expect one of the greyish fields after the `Loan Event` to be given in cases that `Loan Event` is checked, but the code didn't implement this check correctly for checkboxes.

I'll now deploy an update for this.

**Comment by cormacanderson** [comment]
Are you sure that is the problem? Try to enter some text in the "root reference lg" or "root reference form" for the same cognate set on the same html form. That didn't work for me either, i.e. I still got the error.

**Comment by cormacanderson** [comment]
Correction, now this does work for me, although it didn't yesterday, strangely.

**Comment by runjak** [comment]
I can confirm it is also working on my machine:
![screenshot_2016-10-14_14-32-27](https://cloud.githubusercontent.com/assets/5417642/19387529/0c42aecc-921b-11e6-8bce-3c7a4b40f67a.png)

I guess the problem here is solved then?
