### ISSUE TITLE
New Form: `All? Meanings, All? Cognate Sets` - Filtered by Multi-Branch(es)

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#329]
We need a form to explore filtered, targeted selections of cognate sets.  This can start out as a clone of `1-Meaning, All Cognate Sets`, but in theory can and will cover all meanings.  The base table will have to be that for all cognate sets (across all meanings), which of course means something like 5000+ entries for now.

That number is impractical, but in fact the list should already be heavily prefiltered:  
- [x] Exclude all cognate sets found only in one branch.  This is a large proportion of the 5000+.
- [x] The form will be filtered by branch, using the branch filter buttons already in the `1-Meaning, All Cognate Sets`.
- [x] The form should default to an empty view, with no records, because all branch filter buttons should be toggled to 'off'.
- [x] Users should then use the branch filter buttons to toggle on individual branches.  
- [x] Toggling on a single branch should show only cognate sets (in any meaning) found _only_ in that branch, and not in any others.
- [x] Toggling one more than one branch should show only cognate sets (in any meaning) found _only_ in all of the branches selected, and not in any others, and not in only one of the selected branches.  I.e. it should return the set intersection of those branches, not the set union ;)

This will be a fantastic and very necessary tool for checking up and working out any odd patterns that appear in the phylogenetic analyses.

**Comment by runjak** [comment]
In the top menu I've added a magnifying glass icon to make the new feature available:
![screenshot_2016-11-01_13-39-14](https://cloud.githubusercontent.com/assets/5417642/19890052/a3ec7804-a038-11e6-88d0-7bedd0531f43.png)

This makes it possible to look at all cognate classes that are related to branches [Germanic,Anatolian](http://www.cobl.info/cladecognatesearch/?clades=Germanic,Anatolian) only - for example.

**Comment by cormacanderson** [comment]
The basic functionality is just what we were looking for - good job! However, there are a number of small improvements which should be made, and for which I am reopening this issue:
- [ ] In the default, the clade buttons should be faded out, and clicking them (to see the cognate sets in that clade) should cause them to become coloured
- [ ] The functionality here seems to be working off the basis of the `all` meaning and language lists. Instead, it should reflect the meaning and language lists selected, i.e. the `Jena 200` meaning list and the `Current` language list by default.
