### ISSUE TITLE
Bug in source-citation dropdown list

### ISSUE THREAD

**Issue by m-scarborough** [lingdb/CoBL#333]
Currently the drop-down list for inputting citations is no longer in any coherent order.  I realise that this is getting replaced with something else that is more efficient very soon, but for now it is very difficult to find a particular source from the drop-down list in the meantime.

<img width="655" alt="screen shot 2016-10-22 at 13 25 47" src="https://cloud.githubusercontent.com/assets/15671787/19619282/5b3f936e-985b-11e6-82fb-a25cd74d1c24.png">

**Comment by nitsnatsnok** [comment]
I have no idea why this is the case and I know nothing about plans to replace it, but as a bad workaround you can type its first letters in the opened dropdown list to get your desired entry marked.
@runjak, @khoidt: I think you should fix this asap.

**Comment by m-scarborough** [comment]
Ah ok, I thought there was a longer-term plan to replace the drop-down citation selection menu, but I may have been mistaken.

**Comment by m-scarborough** [comment]
Is it possible that a fix could come to this issue soon?  Searching through the lists for different references by the same author in the list (if there are multiple, typing the first letters only gives one of them) is becoming very time consuming.

**Comment by khoidt** [comment]
@m-scarborough I'm working on this now. A fix is on it's way.

**Comment by m-scarborough** [comment]
Ok, thank you.

**Comment by khoidt** [comment]
@m-scarborough Sources are now displayed as author-year(-siglum), see my [last comment](https://github.com/lingdb/CoBL/issues/306#issuecomment-256425698) in #306.

**Comment by m-scarborough** [comment]
Reopening this, since with the deployment of the new release this problem is still unfixed.  What is more, with the deployment of the new release the labelling information on some of the entries have disappeared — not just in the dropdown list, but also in the citation headings in other sections of the database.

<img width="1204" alt="screen shot 2016-11-01 at 10 27 27" src="https://cloud.githubusercontent.com/assets/15671787/19887038/17c4370a-a01e-11e6-894e-f194ca473a40.png">

<img width="763" alt="screen shot 2016-11-01 at 10 28 02" src="https://cloud.githubusercontent.com/assets/15671787/19887042/1e6e89a2-a01e-11e6-8f94-6cad3d6ec443.png">

I would like to emphasise that I am very appreciative that the restructuring of the citation system is going to move us to a better system, and I am aware that the programming task for this transition is difficult.  

At this point however, without being able to make citations (or know where the ones which have disappeared have come from) I'm effectively not able to do further work on the cognacy-coding and quality-control of the data in database until this is resolved.

**Comment by runjak** [comment]
@khoidt is it per chance necessary to run the bibtex import command again?

**Comment by khoidt** [comment]
As far as I can see, the new BibTeX file was not imported. @runjak No need to run the command, now it can be done via the web interface:
![image](https://cloud.githubusercontent.com/assets/7487683/19887806/03fc9ad4-a02b-11e6-9c01-d777df703988.png)
My latest version of the BibTeX data is in [this comment](https://github.com/lingdb/CoBL/issues/306#issuecomment-256425698). @nitsnatsnok, do you have a more recent update?

**Comment by runjak** [comment]
I've executed the upload with the given file.

**Comment by khoidt** [comment]
@m-scarborough as for the empty entries, they most probably stand for publications which lack proper BibTeX data (and likely are to be removed from the database; @nitsnatsnok, am I right?). 
I will make a list of such empty entries to see exactly what each of them represents.

**Comment by m-scarborough** [comment]
Ok, I think that looks like it's filled in some of them, but I'm wary about automatically removing those ones that lack BibTeX data, as they may still have valid citation data attached to them.  In http://cobl.info/cognate/5399/ which I screencapped above, the citation to what I believe to be Puhvel's 2001 _Hittite Etymological Dictionary Volume 5: Words Beginning with L_, and that is still useful information to have for in that cognate set.

**Comment by khoidt** [comment]
@m-scarborough All the basic information and the citation-related data is still there, of course. The reason why some of the names appear empty is simply because now the program uses the newly added BibTeX data to automatically generate short names for sources. Thus, when the BibTeX fields are empty, the names are empty as well.

**Comment by m-scarborough** [comment]
Ok, I understand now.  I was concerned we might lose some of the citation data.

**Comment by nitsnatsnok** [comment]
Empty entries should not occur: If #223 is resolved, every ID without a counterpart in the bib file should be removed by now. It is possible that very recently added sources are not present in the file yet, but that should be the case for single ones at most.

> My latest version of the BibTeX data is in this comment. @nitsnatsnok, do you have a more recent update?
I do, and have tried to import it, but it just shows “Page unavailable” and I'm not sure it the upload was successful. Please try to add [the file](https://github.com/lingdb/CoBL/files/563927/lexicon_source05.txt) yourself (after renaming it to .bib of course).

> I'm wary about automatically removing those ones that lack BibTeX data, as they may still have valid citation data attached to them.
Don't worry, we double-check everything before removing anything from the database that could be of slightest importance.

**Comment by khoidt** [comment]
@runjak, did the migrations (especially `306_0127_fix_issue_223.py`) went well? The problem is that I am still seeing a lot of empty names on the server, while there is only a single one in my local copy (namely, the deprecated ID 57).

**Comment by runjak** [comment]
@khoidt when looking at the server logs, I find two things.
First the migrations said this:
```
Running migrations:
  Rendering model states... DONE
  Applying lexicon.306_0125_auto_20161021_0109... OK
  Applying lexicon.306_0126_auto_20161027_0315... OK
  Applying lexicon.306_0127_fix_issue_223...Deleting sources exception: source with id 21 was already deleted
 OK
```
In addition I've found some exceptions like this in the logs:
```
[2016-11-01 13:14:03,085] ERROR Exception found by logExceptions.
Traceback (most recent call last):
  File "/CoBL/ielex/utilities.py", line 25, in f
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/CoBL/ielex/views.py", line 2013, in dispatch
    return super(source_import, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/CoBL/ielex/views.py", line 2045, in post
    result = self.get_bibtex_data(f)
  File "/CoBL/ielex/views.py", line 2075, in get_bibtex_data
    result = self.get_comparison_dict(entry)
  File "/CoBL/ielex/views.py", line 2087, in get_comparison_dict
    return self.get_update_dict(entry, source_obj)
  File "/CoBL/ielex/views.py", line 2098, in get_update_dict
    if getattr(source_obj, key) == entry[key]:
AttributeError: 'Source' object has no attribute '% authortype'
```

**Comment by khoidt** [comment]
@runjak the first one is alright, but the second is really weird. The `authortype` field of `Source `should have been added by `306_0120_auto_20161007_0248.py`. Could you check if it actually exists in the database?

**Comment by runjak** [comment]
Sure thing - on my way.

**Comment by runjak** [comment]
Here's the layout of the `Source` table on the server:
![screenshot_2016-11-01_13-32-47](https://cloud.githubusercontent.com/assets/5417642/19889864/c0a06a2e-a037-11e6-8dd1-c85cf7620df5.png)

I think the problem is not necessarily that the `authortype` column is missing, but to me it looks like the attribute tested was `% authortype` - so the question would be where the leading `'% '` come from.

**Comment by khoidt** [comment]
@runjak I have figured this out. The  `% authortype` came from the `.bib` file. Here is a corrected version that should work (@nitsnatsnok, note this):
[short_citations.txt](https://github.com/lingdb/CoBL/files/564030/short_citations.txt)

**Comment by runjak** [comment]
@khoidt nice! Is there a next step I can help with?

**Comment by khoidt** [comment]
@runjak, hopefully, that's it. Here is another update for the `.bib` file.
[lexicon_source05.txt](https://github.com/lingdb/CoBL/files/564155/lexicon_source05.txt)
I've imported the latest version to the database, so now everything should work fine. @m-scarborough, if it really does, please, close this issue.
@nitsnatsnok, I've renamed the 'date' field back to 'year', so it matches the database field. If you plan to rename BibTeX fields (as well as add new ones or completely remove a certain category), please, let me know what has changed in the format, so I can adjust the code.

**Comment by nitsnatsnok** [comment]
@khoidt Sorry, my bad! Changes noted.

**Comment by m-scarborough** [comment]
Ok, that seems to have restored most of the instances where sources have been coming up as blanks.  Thank you for that, I can now get back to work.  The original issue, that they're not in any filtered or alphabetic order, still remains.

<img width="747" alt="screen shot 2016-11-01 at 13 53 11" src="https://cloud.githubusercontent.com/assets/15671787/19892045/cb226ff8-a03a-11e6-8962-359843542b3d.png">

**Comment by khoidt** [comment]
@m-scarborough, I see the problem. Actually, I did implement an alphabetic sorting in the last deployment, but it is obviously not working. I will do my best to fix in the next couple of days.

**Comment by m-scarborough** [comment]
Ok, thanks :)

**Comment by nitsnatsnok** [comment]
It seems that this is solved in the meantime. The sources appear in alphabetical order…
![2016-11-15-182738_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/20316262/745e7450-ab61-11e6-9931-bcd0f71962e3.png)

… and the formerly broken citation in http://cobl.info/cognate/5399/ shows the correct source.
![2016-11-15-183139_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/20316412/01395cfa-ab62-11e6-8075-2fc1f6115a94.png)

 @m-scarborough, is there anything we missed or can we close this issue?

**Comment by m-scarborough** [comment]
I am satisfied.  Closing the issue.
