### ISSUE TITLE
Bugs on Meanings Reference Form

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#336]
- [x] The search/filter box for meanings does not work properly, it seems set to the meaning number, not the meaning 'name'.  Type 12 in the box, and the meanings filter to meaning number 12 plus numbers 120-129, it seems.  Typing 123 gives one meaning, number 123.
- [x] Please keep this search box, and add the meaning number as a separate column for which this search box already exists.
- [x] The sort button by meaning is also set to meaning number instead of meaning name.  Again, move this to the corresponding new column for meaning number.
- [x] Create a new search box and sort button for the meaning 'name'.
- [x] Also on this table, there is no filter count of records returned -- please add one, like on most other pages.

**Comment by runjak** [comment]
If I'm not mistaken the count of records is there:
![screenshot_2016-11-07_15-53-56](https://cloud.githubusercontent.com/assets/5417642/20062020/6ea9d690-a502-11e6-886f-698de82dfc56.png)
