### ISSUE TITLE
Changing the Online Dictionary Link for Old Norse

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#338]
Currently, clicking on the dictionary link of an Old Norse lexeme yields a whole dictionary page, where one has to scroll down and search for lexeme, e.g. [ASH aska](http://lexicon.ff.cuni.cz/html/oi_cleasbyvigfusson/b0025). I propose to change it to point to the search page of the Germanic Lexicon Project, e.g. [ASH aska](http://web.ff.cuni.cz/cgi-bin/uaa_slovnik/gmc_search_v3?cmd=formquery2&query=aska). This has the following advantages:
- it shows the lemma entry solely rather than a whole dictionary page
- it shows the lemma entries in a number of different helpful dictionaries
- it makes it possible to enter the lemma directly in the “Dict ID 1” field (at least for lemmata without special symbols like þ) rather than a page number

What do you think about this?

**Comment by cormacanderson** [comment]
This is clearly preferable if the information is the same. @tonyakdewey can you give an assessment?

**Comment by tonyakdewey** [comment]
Yes, that's fine.  Caveat:  the OCR has not been 100% checked by humans, so occasionally you get some nonsense characters in the search results, but I believe they are working on this.

**Comment by nitsnatsnok** [comment]
Thank you very much, I'm going to change the dictionary link and adjust the lexemes' links then.

**Comment by nitsnatsnok** [comment]
Thank you very much, I'm going to change the dictionary link and adjust the lexemes' links then.
