### ISSUE TITLE
Fixes to `Add new language` function

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#347]
- [x] The `Add new language` function is causing some bugs, and needs fixing.  When a new language is created, it is added to the ALL languages list, which is OK, but it also automatically needs to be added as a member of the language list currently being viewed by the user, normally ‘Current’.  Otherwise the new language is ‘invisible’ and the user doesn’t know that it has been successfully created.  Indeed in my attempt just now to create Old Czech, I got an error message, and presumed the create had failed, but it in fact hadn’t and now I have two versions of Old Czech.
- [x] The field names and notes on the `Add new language` dialogue are outdated and need changing.  The text on allowed characters should be deleted, and …
`Utf8 name` should be renamed to `Display Name`  (spaces, colons and accented characters allowed, but no underscores.  e.g. Sorbian: Upper)
`Ascii name` should be renamed to `URL Name`   (no spaces, no accented characters, only ascii a-z and A-Z, no underscores.  e.g. SorbianUpper)

(This seems to be a similar problem to #205, although whether they are directly related we don’t know.)

- [x] There seem to be problems with saving changes to the metadata for the newly created languages, too.  Here are some screenshots.
![screenshot - 2016-11-15 12_30_21](https://cloud.githubusercontent.com/assets/8819910/20304318/c4bff176-ab2f-11e6-936a-a7b663b27bae.png)
![screenshot - 2016-11-15 09_06_57](https://cloud.githubusercontent.com/assets/8819910/20304319/c64f4834-ab2f-11e6-926b-cd559614bcef.png)

**Comment by runjak** [comment]
Thanks for expanding the description and adding screenshots - this should make debugging easier.

**Comment by runjak** [comment]
* I've adjusted the labels for the form that adds languages.
* I've also found the bug that broke adding languages to the currently selected languages list.

So it should now be possible to add languages again.

The form for a single language has still problems that need attention.
I've increased the verbosity of the error messages it produces so that
better feedback may happen.

One problem with the form is that it shows the `Historical` checkbox, but doesn't make the `Distribution selection` available. Therefore setting a language to `Historical` here will fail as no `Distribution` is selected along with it.

**Comment by PaulHeggarty** [comment]
I’ve logged out and back in, twice, and added three new languages (all forms of Middle Serbo-Croat).  Each time I got a the Page Unavalable error message (as per the screenshot above), but if I try to add them again it now tells me that the language does already exist (see below).  I cannot see the languages anywhere, however, since they appear neither in the `Current` nor in the `all` language list.  
![screenshot - 2016-11-15 16_52_31](https://cloud.githubusercontent.com/assets/8819910/20312576/46efe678-ab54-11e6-8143-28adc5332ee6.png)

**Comment by runjak** [comment]
Like I just described in #348 I think that some of the problems here result from unexpected data in the database. The broken code for language creation apparently let 3 languages exist that are not linked to any language list:
![screenshot_2016-11-16_13-40-12](https://cloud.githubusercontent.com/assets/5417642/20347622/5ac4f04a-ac02-11e6-9d6d-fc131b240ce7.png)
I will drop these 3 entries and add additional safeguards to the language creation code to ensure that languages belong to a language list.

Afterwards I'll investigate which problems remain and deploy.

**Comment by runjak** [comment]
I've removed the faulty entries and deployed a fix for #348.
More functionality should now work again, including I believe the creation of new languages.
The edit form for single languages still needs my attention so I will not close this issue yet.

**Comment by runjak** [comment]
Deployed fixes to single language form.
