### ISSUE TITLE
Unable to save any information in Language List

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#348]
Since at least yesterday I'm not able to add a Web Path (or anything else) in the Language List, the website just aswers „Sorry, the server had problems saving at least one language entry.“:
![2016-11-16-092630_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/20339995/9f9df7ac-abdf-11e6-8d63-356c68dc3d07.png)
I'm logged in and tried cleaning my cache and using Chromium as well as Firefox without any avail.

**Comment by runjak** [comment]
I could reproduce this after downloading a copy of the database from the server.
I think the problem here is an unexpected database situation resulting from #347.
Cleaning this up should aid the problems found in both issues.

**Comment by runjak** [comment]
I've deployed code that should fix this problem (or at least did so on my machine).
Please reopen if it persists.
