### ISSUE TITLE
new citation comment field appears too wide

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#357]
When adding a new citation, the comment field appears too wide so that it's overlapped on the right side:
![2016-11-23-212037_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/20577509/f7a89cc0-b1c2-11e6-94f2-6f039bafeb76.png)

**Comment by khoidt** [comment]
Can be closed when the [last update](https://github.com/lingdb/CoBL/issues/344#issuecomment-263339290) is deployed and successfully tested on the server.

**Comment by runjak** [comment]
I've just deployed this. Sorry for the delay.
