### ISSUE TITLE
citations are stored twice in the tables

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#358]
Correct my if I'm wrong here, but to me it seems like citations are stored twice in the tables, cf. lexicon_cognateclasscitation:
![2016-11-24-144150_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/20600714/415721c4-b255-11e6-90dc-3613a1681b53.png)
The same applies to lexicon_cognatejudgementcitation and lexicon_lexemecitation as well, and this seems to yield strange behaviour and orphan entries as described in [this comment](https://github.com/lingdb/CoBL/issues/332#issuecomment-262776327).

**Comment by khoidt** [comment]
Very strange. I'd even say impossible, as Django doesn't allow DB entries to share the same ID.

**Comment by nitsnatsnok** [comment]
Well, it's not a problem of pgAdmin III, which I use to display the data:
`SELECT id FROM public.lexicon_cognateclasscitation WHERE source_id = 70;` directly in a terminal also outputs every id twice.

**Comment by khoidt** [comment]
I'll look into this.

**Comment by khoidt** [comment]
Might be related to [this](https://code.djangoproject.com/ticket/25544) Django issue. If true, I'll make a migration to remove the duplicates.

**Comment by nitsnatsnok** [comment]
Oh, it's totally my own fault, I seem to have accidentally restored two dumps in the same database here – Nevermind!
However, the problem in the mentioned comment still remains.

**Comment by khoidt** [comment]
If so, please, close this one.
