### ISSUE TITLE
Sources Import doesn't work

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#368]
Uploading a bib file like [this](https://github.com/lingdb/CoBL/files/584012/corrected_names_01.txt) on http://cobl.info/sources/import/ yields “Page unavailable” without the data being imported. I tried it with several other, smaller files with just one entry with and without an ID, but neither worked.

**Comment by khoidt** [comment]
@nitsnatsnok, thanks for opening this issue, this is very important! 
Just to exclude permissions causes, do I understand right that you do have the rights needed to modify sources on the server?

**Comment by nitsnatsnok** [comment]
Good question, I can just say that I _should_ have the rights (cf. [this](https://github.com/lingdb/CoBL/issues/344#issuecomment-258851912)), but I have no idea where and how these rights are set and how I can check whether I have certain rights. Sorry for being no help here. :disappointed:

**Comment by nitsnatsnok** [comment]
I'm also not able to add a source via http://cobl.info/source/add/, this yields “Page unavailable” exactly like [for Matthew](https://github.com/lingdb/CoBL/issues/344#issuecomment-263251485), but for me there is actually nothing added, regardless to what I enter in the fields.
Even if it's just a rights problem, the website should at least throw out an error message that informs about that. This would really facilitate future debugging… Besides a proper rights system based on groups, needless to say.

**Comment by khoidt** [comment]
Can see the 'add', 'import' and 'edit' buttons in /sources/? If yes, you do have permissions.

**Comment by nitsnatsnok** [comment]
I do have those buttons!

**Comment by khoidt** [comment]
So this likely excludes permissions. Good, I'll investigate further.
As for rights based on groups (probably needs an issue of its own, if no such exists yet), I'm totally in favor of such a policy, but it's not my place to decide. It actually even requires no programming, just a superuser status.

**Comment by nitsnatsnok** [comment]
This issue for that is #325.

**Comment by khoidt** [comment]
Fixed in the [last update](https://github.com/lingdb/CoBL/issues/344#issuecomment-264850822). Close when deployed and tested.
