### ISSUE TITLE
Bibliography Fields appear too wide

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#369]
When the button “Add” or one of the “Edit” buttons is clicked, some of the bibliography fields contained in the appearing window are overlapping on the right:
![2016-11-29-164757_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/20717096/afdab7ac-b654-11e6-857f-8b2cd8929fd9.png)

**Comment by nitsnatsnok** [comment]
This can be easily solved by changing the size of the (anyway completely oversized!) fields. I think the fields in this window should all be of the same size, `ENTRYTYPE` seems to be a good measure. It's a good solution that fields can be enlarged with a click in the corner, they doesn't need to be so wide and long additionally. It would be perfect if one would not need to scroll down inside the window any more.

**Comment by khoidt** [comment]
Fixed in the [last update](https://github.com/lingdb/CoBL/issues/344#issuecomment-264850822). Close when deployed and tested.
