### ISSUE TITLE
Make ENTRYTYPE field mandatory and inform about valid input

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#374]
It's currently possible to add a source without specifying the `ENTRYTYPE`, but this causes problems (#373) and isn't desirable at all. As [requested by Ilya](https://github.com/lingdb/CoBL/issues/373#issuecomment-264849485), I now removed every source without an `ENTRYTYPE` (it was just one I added by accident), so there's no such source in the database anymore.

@khoidt It should now be safe to make the field mandatory, so that things like #373 can't happen again.

**Comment by nitsnatsnok** [comment]
> https://github.com/lingdb/CoBL/issues/373#issuecomment-264887491: the allowed values of ENTRYTYPE are the following:
book, article, journal, expert, online and inbook.

In the add form (http://cobl.info/source/add/), there also needs to be information about the valid input for `ENTRYTYPE` – maybe as a list next to the field. There's plenty of space for this on the right.

**Comment by nitsnatsnok** [comment]
Maybe the best would be to make `ENTRYTYPE` a **dropdown list** with the handful of item types we are using, this way we could prevent users from entering invalid data.

**Comment by khoidt** [comment]
Solved with the last update. Please, close this after the deployment and testing of d4db9f2.

**Comment by runjak** [comment]
:rocket: deployed.

**Comment by nitsnatsnok** [comment]
works like a charm!
