### ISSUE TITLE
On upgrading software dependencies

### ISSUE THREAD

**Issue by runjak** [lingdb/CoBL#379]
At the moment our website uses `Python 2.7` and `Django 1.8.7`.
This is working right now but not optimal for the future.
The current Django version is `1.10.4` and the current Python version is `3.5.2`.
I have prepared an upgrade for both of these that I recommend we take.
![screenshot_2016-12-14_13-58-12](https://cloud.githubusercontent.com/assets/5417642/21182844/6279ec0a-c205-11e6-982f-37ee84c515c5.png)

Staying up to date with our software will bring some benefits:
* We get improvements to security and speed that have been developed for our dependencies.
* It takes longer for our software to become outdated. Even though software appears to be abstract it ages and the cost of continuing development increases the longer we wait with updating.

There is currently one problem with upgrading that blocks deployment for the new code:
The code from Michael does some tracking of changes in the database which are visible under [cobl.info/changes/](http://cobl.info/changes/).
With the update to current Django an update of this tracking data becomes necessary.
This update currently takes about 4 hours:
![screenshot_2016-12-13_20-27-00](https://cloud.githubusercontent.com/assets/5417642/21183215/31ad6578-c207-11e6-90b4-18d9b9f4dea2.png)
…and afterwards the changes page appears to load forever.

I think the possible courses of action here are:
1. Take the time on the weekend to migrate the server. This would require figuring out how to fix the loading time on my machine beforehand. I expect this to be possible but it may not be.
2. Remove the whole tracking code if it isn't used all to much.

**Comment by runjak** [comment]
There is a command that can be used to keep the change history short:
[deleterevisions](https://django-reversion.readthedocs.io/en/stable/commands.html#deleterevisions)

Maybe this can help me here.

**Comment by runjak** [comment]
I think I just found the problem with the changes view.
A query in there took way longer than it should have, and optimizing it makes it possible to display the view again.

**Comment by runjak** [comment]
OK.
So the remaining work to do here is:
* Claim the server database exclusively for a few hours to deploy the upgrade.
* Get a copy of the database pre and post upgrade.
* Make sure to keep branch #379 up to date till deployment.

**Comment by runjak** [comment]
I'm planning to deploy a load of different changes this evening/night including this issue.
The expected duration for the database upgrade will be about 4 hours during which the cobl.info website will not be available.

This may be of potential interest for @PaulHeggarty, @cormacanderson and @khoidt I think.

@khoidt after the upgrade I'll upload a more current database state for you so that you don't have to go trough the migrations yourself. From then on we'll also be using current python and django versions.

While working on things related to this upgrade I also managed to improve performance of the 1L view on my machine:
![screenshot_2016-12-19_10-07-58](https://cloud.githubusercontent.com/assets/5417642/21316175/dab12c8a-c5ff-11e6-9def-2f6090a154d3.png)
![screenshot_2016-12-19_10-08-08](https://cloud.githubusercontent.com/assets/5417642/21316174/daaf0964-c5ff-11e6-9b8c-55733082b950.png)
The relating commits are 82b27473ae613ad273a1fbfe5958f2244279e896 and 4e020b5a1d1df3e98d47955a132e573b32fd1e8b.

**Comment by khoidt** [comment]
This really looks great!! Just that you know, I have some recent changes that I plan to commit to #306 in the next couple of hours. Would you prefer me to merge with `devel` before the big upgrade or after?

**Comment by runjak** [comment]
I'll likely go ahead before the merge - but if you push into #306 I'll also see to merge with devel and deploy at once .)

**Comment by runjak** [comment]
I've made the recent database dump available.
The migrations went trough without problems and we're now on current django and python versions.
