### ISSUE TITLE
Add a BLANK language list

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#43]
This should have one lexeme entry for each of the 200 meanings, but with all fields left blank

**Comment by cormacanderson** [comment]
This is related to, and possibly can be merged with https://github.com/lingdb/ielex2/issues/41

**Comment by cormacanderson** [comment]
If implemented, we have to be careful as to the implementation of https://github.com/lingdb/ielex2/issues/35

**Comment by runjak** [comment]
I'll keep this closed as it essentially duplicates the content of #41 and the title misled me earlier.
