### ISSUE TITLE
Export Clade Membership (which languages in which clades)

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#50]

**Comment by PaulHeggarty** [comment]
= #161

**Comment by PaulHeggarty** [comment]
These are the instructions from Remco on the syntax for the nexus export.

The first part defines the taxon sets, which are all kept monophyletic, and the second part contains age constraints — partly referring to tips, partly referring to clades defined in the first part. Ages are in millennia. The list is generated from the XML.


begin sets;
taxset Old_Irish_Irish_Scots =  Irish Old_Irish Scottish_Gaelic;
taxset Old_Norse_Icelandic_Faroese =  Icelandic Faroese Old_Norse;
taxset AllEnglish =  English Old_English;
taxset High_German =  German Luxembourgish Old_High_German;
taxset Eastern_Iranian =  Wakhi Avestan Ossetic_Digor Ossetic_Iron Khotanese Sarikoli Shughni Sogdian;
taxset Western_Iranian =  Pashto Waziri Persian Tajik Baluchi Kurdish Old_Persian Middle_Persian Parthian;
taxset South_Slavic =  Macedonian Bulgarian Serbo-Croatian Old_Church_Slavonic;
taxset Celtic =  Irish Welsh Breton Middle_Cornish Old_Irish Scottish_Gaelic Middle_Breton Old_Breton Old_Welsh Gaulish;
taxset Brythonic =  Welsh Breton Middle_Breton Middle_Cornish Old_Breton Old_Welsh;
taxset French/Iberian =  Provencal French Walloon Spanish Portuguese Catalan;
taxset Italic =  Provencal French Walloon Sardinian_Nuoro Sardinian_Logudoro Sardinian_Cagliari Spanish Portuguese Catalan Romanian Vlach Italian Ladin Friulian Latin Romansh Umbrian Oscan;
taxset Latin_Romance =  Provencal French Walloon Sardinian_Nuoro Sardinian_Logudoro Sardinian_Cagliari Spanish Portuguese Catalan Romanian Vlach Italian Ladin Friulian Latin Romansh;
taxset WestGermanic =  German Dutch Flemish Frisian English Luxembourgish Old_English Old_High_German;
taxset NorthGermanic =  Swedish Danish Norwegian_Riksmal Icelandic Faroese Old_Norse Old_Swedish;
taxset Northwest-Germanic =  German Dutch Flemish Frisian English Swedish Danish Norwegian_Riksmal Icelandic Faroese Luxembourgish Old_English Old_High_German Old_Norse Old_Swedish;
taxset Germanic =  German Dutch Flemish Frisian English Swedish Danish Norwegian_Riksmal Icelandic Faroese Gothic Luxembourgish Old_English Old_High_German Old_Norse Old_Swedish;
taxset Baltic =  Lithuanian Latvian Old_Prussian;
taxset Lithuanian/Latvian =  Lithuanian Latvian;
taxset Slavic =  Slovenian Sorbian_Lower Sorbian_Upper Czech Slovak Ukrainian Belarusian Polish Russian Macedonian Bulgarian Serbo-Croatian Old_Church_Slavonic Kashubian Polabian;
taxset Balto-Slavic =  Lithuanian Latvian Slovenian Sorbian_Lower Sorbian_Upper Czech Slovak Ukrainian Belarusian Polish Russian Macedonian Bulgarian Serbo-Croatian Old_Church_Slavonic Old_Prussian Kashubian Polabian;
taxset West-Slavic =  Kashubian Polabian;
taxset Indic =  Sinhalese Kashmiri Marathi Gujarati Lahnda Hindi Bengali Nepali Assamese Bihari Oriya Sindhi Urdu Vedic_Sanskrit Pali;
taxset Iranian =  Pashto Waziri Persian Tajik Baluchi Wakhi Avestan Ossetic_Digor Ossetic_Iron Kurdish Old_Persian Khotanese Sarikoli Shughni Middle_Persian Parthian Sogdian;
taxset Indo-Iranian =  Sinhalese Kashmiri Marathi Gujarati Lahnda Hindi Bengali Nepali Pashto Waziri Persian Tajik Baluchi Wakhi Assamese Avestan Bihari Ossetic_Digor Ossetic_Iron Kurdish Oriya Sindhi Urdu Vedic_Sanskrit Old_Persian Pali Khotanese Sarikoli Shughni Middle_Persian Parthian Sogdian;
taxset AllGreek =  Mycenaean_Greek NT_Greek Greek Ancient_Greek;
taxset AllArmenian =  Armenian_Eastern Armenian_Western Classical_Armenian;
taxset Tocharian =  Tocharian_A Tocharian_B;
taxset Anatolian =  Hittite Luvian Lycian;
end;


begin assumptions
calibrate Ancient_Greek = normal(2.45,0.1)
calibrate Avestan = normal(2.5,0.05)
calibrate Classical_Armenian = normal(1.45,0.075)
calibrate Gaulish = normal(1.9,0.2)
calibrate Gothic = normal(1.65,0.025)
calibrate Hittite = normal(3.45,0.125)
calibrate Khotanese = normal(1.5,0.2)
calibrate Latin = normal(2.05,0.075)
calibrate Luvian = normal(3.35,0.075)
calibrate Lycian = normal(2.4,0.05)
calibrate Middle_Breton = normal(0.7,0.15)
calibrate Middle_Cornish = normal(0.7,0.1)
calibrate Middle_Persian = normal(1.6,0.15)
calibrate Mycenaean_Greek = normal(3.35,0.075)
calibrate Old_Breton = normal(1.1,0.1)
calibrate Old_Church_Slavonic = normal(1.0,0.05)
calibrate Old_English = normal(1.0,0.05)
calibrate Old_High_German = normal(1.05,0.05)
calibrate Old_Irish = normal(1.25,0.075)
calibrate Old_Norse = normal(0.775,0.04)
calibrate Old_Persian = normal(2.45,0.075)
calibrate Old_Prussian = normal(0.5,0.05)
calibrate Old_Swedish = normal(0.65,0.1)
calibrate Old_Welsh = normal(1.05,0.05)
calibrate Oscan = normal(2.2,0.1)
calibrate Pali = normal(2.5,0.1)
calibrate Parthian = normal(2.1,0.15)
calibrate Polabian = normal(1.68,0.02)
calibrate Sogdian = normal(1.35,0.15)
calibrate Tocharian_A = normal(1.375,0.075)
calibrate Tocharian_B = normal(1.35,0.075)
calibrate Umbrian = normal(2.2,0.1)
calibrate Vedic_Sanskrit = normal(3.0,0.1)


calibrate Celtic = uniform(1.7,10.0)
calibrate Brythonic = normal(1.55,0.025)
calibrate French/Iberian = normal(1.4,0.01)
calibrate Latin_Romance = normal(2.0,0.135)
calibrate WestGermanic = normal(1.55,0.025)
calibrate Northwest-Germanic = normal(1.875,0.067)
calibrate Lithuanian/Latvian = normal(1.35,0.025)
calibrate Slavic = offsetlognormal(1.2,0.3,0.6)
calibrate Balto-Slavic = normal(3.1,0.6)
calibrate Balto-Slavic = uniform(2.0,3.4)
calibrate Iranian = offsetlognormal(2.6,0.4,0.8)
calibrate Indo-Iranian = uniform(3.0,10.0)
calibrate Tocharian = offsetlognormal(1.65,0.2,0.9)
end;

**Comment by PaulHeggarty** [comment]
Remco warns about this individual calibration, which Cormac and I need to think through.

Note that Latin_Romance is calibrated at normal(2.0,0.135), but that should probably a bit older, since Latin = normal(2.05,0.075), so that forces Latin to be ancestral to Romance.
