### ISSUE TITLE
Allow cognate sets to be assigned by writing the alias letter

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#51]
This should be in the box that shows the alias letter on, e.g. the 1 meaning/ all languages, or 1 meaning all cognate sets, html forms

**Comment by PaulHeggarty** [comment]
Deleting the current letter should remove the link from this lexeme to this cognate set.
If the cell is blank, typing + should add a new cognate set.

**Comment by PaulHeggarty** [comment]
This is moved up the urgency rank, because efficiency in this is much more urgent now that Cassandra is having to spend a lot of time reassigning cognacy by the bad old system.

**Comment by runjak** [comment]
It may be helpful to consider this together with #52.

**Comment by runjak** [comment]
It appears that #118 and #141 should be solved before this one.

**Comment by PaulHeggarty** [comment]
This has now merged into #219, so could in theory be closed, provided the drop-down box accepts typing a letter as a way of selecting the alias of the cognate set to be assigned.

**Comment by runjak** [comment]
Closing this as the fine tuning of the drop-down box solution happens in #219 and basic functionality to assign cognate classes is provided now.

**Comment by PaulHeggarty** [comment]
Interestingly, the ability to assign just by typing the letter is actually still a desideratum -- as a way to make a selection in the drop-down list -- does it work like that?  To save on clicks.  ;)

**Comment by runjak** [comment]
Good point - I may be able to use something similar to the code for putting in a meaning or language name directly to navigate to that page just that it would be combined with a drop-down list still so that it's also possible to discover the possible choices via the list.

I'll reopen this so that I'll remember it better.
