### ISSUE TITLE
One click button for new cognate set

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#52]
This will instantly assign a lexeme to a new cognate set

**Comment by PaulHeggarty** [comment]
This issue is now merged into #219, so could in theory be closed, provided the drop-down box system also has a 'assign to new cognate set' button.

**Comment by runjak** [comment]
Closing this as the fine tuning of the drop-down box solution happens in #219 and basic functionality to assign cognate classes is provided now.
