### ISSUE TITLE
Add a button on the header bar to view authors

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#58]

**Comment by runjak** [comment]
From this I infer that the `author`/`reviewer` fields mentioned in #59 should not be displayed by default, but instead only when requested?

**Comment by cormacanderson** [comment]
No, I think they should be there as default in the languages html form., just that by pressing a button on the right sidebar you get a list of all the authors and languages, much as currently occurs with sources. A model for what is meant by this is here http://wold.clld.org/contributor

**Comment by runjak** [comment]
Ah! Thanks for clarifying this :)

**Comment by cormacanderson** [comment]
Now implemented
