### ISSUE TITLE
Reassign defaults for lg list, mng list etc.

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#76]
The default language list should be "". The default meaning list should be "Jena 200". The default should be "Not-Swadesh terms filtered out". The filter Swadesh terms button should be renamed "unhide/hide".

**Comment by cormacanderson** [comment]
The latter = https://github.com/lingdb/IELex2-CognaC/issues/78

**Comment by cormacanderson** [comment]
The default language list should be "2016-02-17_144"

**Comment by cormacanderson** [comment]
View also https://github.com/lingdb/IELex2-CognaC/issues/91 for problems with the new default meaning list

**Comment by runjak** [comment]
I've just fixed the `Jena200` meaning list, so that the only outstanding problem for this issue should be to make `2016-02-17_144` the default language list. Using the experience from setting `Jena200` as the default meaning list this task should be easy enough to solve.
