### ISSUE TITLE
Add ability to set default lists

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#83]
In the Lgs Rfc form, add a drop-down list to select the default language list.
In the Mgs Rfc form, add a drop-down list to select the default meaning list.
Ideally, in fact, this setting should be saved per user, because different users should be working on different default lists.

**Comment by runjak** [comment]
We can track defaults for a bit of time now on a per session basis.
That is we track the selection of default lists of meanings and languages for one browser until it is closed.
It would be possible to also save this in the database for every user that logged in, if we want to. If the current implementation is enough we could close this issue.

**Comment by runjak** [comment]
Nothing left to do here, I believe.
