### ISSUE TITLE
Default meaning list fixed to "all"?

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#91]
An interesting one here. If I switch to the "Jena100" list, it works perfectly, but the Jena200 has the correct "Jena200" meanings first, and then the excluded meanings, also on the "all" list at the bottom. In other words, the change of default to "Jena200" only succeeded in changing the sort order. That being the case, I am changing the expected time on the reopened https://github.com/lingdb/IELex2-CognaC/issues/76 ;)

**Comment by runjak** [comment]
I think I came across the code guilty of this problem in [lexicon/models.py:1288-1311](https://github.com/lingdb/CoBL/blob/master/ielex/lexicon/models.py#L1288-L1311).
The pattern in that code is present two more times for Cognate Class Lists and Language Lists, and also makes use of a `sequentialize` method that looks ill-conceived to me and is also present three times.

**Comment by runjak** [comment]
Note to myself:
I've removed the `jitter` subfunctions from the `sequentialize` methods.
Now these methods only carry redundant code to an extent that is a bit uneasy to remove.
