### ISSUE TITLE
Very thin side bar to show language branch, in intense colours 

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#92]
This should appear at the very left-hand edge of the 1Mg-All Lgs form, immediately in front of the language name.  (I think the language ID number can simply be dropped, to save space.)  This will give a bar showing which languages fit which major branch, constant in all views, and users would soon learn to recognise the branches visually.  This is not a pale pastel background, but a strong colour bar.  Similar to the horizontal version used by Le Monde for their various news sections, for example....

![screenshot - 24_02_2016 22_26_38](https://cloud.githubusercontent.com/assets/8819910/13301541/b80de826-db45-11e5-92dc-dae183da1fa0.png)

But ours should be vertical, of course, the same colour would span several languages sequentially down the page (because they are listed grouped by branch in the default order of languages).  And the colour band should be thicker and more noticeable than in the Le Monde version.  

Cormac, we'd just need to choose ten nice colours for our ten branches.  Perhaps by climate?  ;)  Indic red, Iranic pink, Germanic grey, Celtic ... rain coloured?  ;)
Anatolian brown.  Any other nice associations come to mind?!  ;)

**Comment by cormacanderson** [comment]
I like it :). Climate is a nice start but only goes so far. I would suggest (also a little with how they seem to fit together in mind):
Indic - bright red
Iranic - pink
Anatolian - brown
Tocharian - beige (like the Tarim basin)
Slavic - yellow
Baltic - orange
Armenian - purple
Albanian - dark red
Greek - bright blue (like the Aegean)
Germanic - dark blue
Italic - bright green
Celtic - dark green

**Comment by PaulHeggarty** [comment]
I generally like these, with minor alterations.  General trend, then, is reddish = east, blueish = west.  So ...
Albanian is the one that doesn't seem right.  Maybe grey for that one.  And Indo-European itself ... black.
The other consideration is that we may want to use these colours eventually for the map, when it's in 'branch mode' rather than 'cognate set' mode.  And greens/blues can be harder to distinguish against the map background colours.  But I think we should worry about that later.  It can be made to work, as with Sound Comparisons already.

Next step, then, is to add a field to the Branches Table, where we can specify the six-character RGB code in HEX that we want for each branch/subbranch combination.  Jakob can probably be left to do this and pick the colours for now, from some standard palette?

**Comment by runjak** [comment]
Sure, I imagine using some defaults for the described colors and adding the field to the Branches Table should be simple enough.

**Comment by cormacanderson** [comment]
These colours should also be added to the 1 meaning/ all cognate sets table beside each individual cognate set, representing in a bar, languages from what family are associated to that cognate set.

**Comment by runjak** [comment]
I've picked some colors for this, but will also soon make this available online for editing.
The current colors look like this:
![colors](https://cloud.githubusercontent.com/assets/5417642/13677721/7da6e424-e6eb-11e5-898f-8ccc9689d19b.png)
The data used looks like this:

Category  |  Color  | Description
----------|---------|------------------------------
Indic     | #E11D21 | bright red
Iranic    | #EEA2BE | pink
Anatolian | #654321 | brown
Tocharian | #C9BA9D | beige (like the Tarim basin)
Slavic    | #FFFF00 | yellow
Baltic    | #FF6701 | orange
Armenian  | #7E0B80 | purple
Albanian  | #8B0000 | dark red
Greek     | #1DA6CF | bright blue (like the Aegean)
Germanic  | #002146 | dark blue
Italic    | #66FF00 | bright green
Celtic    | #006301 | dark green

Current oddities with this are:

* I had trouble finding `Armenian` in the branches table
* The lookup for the color to be used for a language may need to traverse the branch tree upwards if a branch doesn't have a color. The alternative for this would be to save a color for all subbranches that don't have a color. Since the latter perspective is more clever performance wise, I'll do just that.

**Comment by cormacanderson** [comment]
Several comments here. One, better grey for Albanian as Paul said. Two, I would go for maybe an even brighter blue for Greek. Three, what are the labels to the left of the colours? Surely Baltic is represented twice by those groups.
Armenian should include Western Armenian, Eastern Armenian and Classical Armenian. It's strange you can't find it.
Under what circumstances would a branch not have colour?

**Comment by runjak** [comment]
I've filled the language branches table from the data provided, which is:
```
INSERT INTO lexicon_languagebranches (level1_branch_ix, family_ix, level1_branch_name) VALUES
(0, 1, 'ALL Germanic'),
(1, 1, 'West Germanic'),
(2, 1, 'North Germanic'),
(3, 1, 'East Germanic'),
(0, 2, 'ALL Romance'),
(1, 2, 'Iberia'),
(2, 2, 'France'),
(3, 2, 'Alpine'),
(4, 2, 'Italy'),
(5, 2, 'Balkans'),
(0, 3, 'ALL Balto-Slavic'),
(1, 3, 'East Slavic'),
(2, 3, 'West Slavic'),
(3, 3, 'South Slavic'),
(8, 3, 'Baltic'),
(0, 4, 'ALL Celtic'),
(1, 4, 'Goidelic'),
(2, 4, 'Brythonic'),
(3, 4, 'Gaulish'),
(4, 4, 'Lepontic'),
(5, 4, 'Celtiberian'),
(0, 5, 'ALL Greek'),
(0, 6, 'ALL Anatolian'),
(0, 7, 'ALL Iranic'),
(0, 8, 'ALL Indic'),
(1, 8, 'Indic Proper'),
(7, 8, 'Dardic'),
(8, 8, 'Nuristani'),
(0, 9, 'ALL Other'),
(1, 9, 'Albanian'),
(5, 9, 'Tocharian');
```
As far as I can see neither Armenian nor any of the sub branches have been provided so far.

**Comment by runjak** [comment]
If you set the color for say `ALL Balto-Slavic`, but no color is set for say `West Slavic`.
How to color the lexeme entry for such a case?
My current method is this:
* Take the language for the lexeme, and try to get it's branch.
* If a branch is found:
  * If the branch has a color: use that color
  * If the branch doesn't have a color see if it's a sub branch.
  * If we have a sub branch use the color of the top branch.

**Comment by PaulHeggarty** [comment]
Armenian was missing, sorry.  It should be;
family_ix = 9
level1_branch_ix = 3
No sub-branches will be provided for Armenian.

The logic here, to be used for the colours, is:
One dedicated colour per 'family_ix value.
Sub-branches at level1_branch_ix do not get their own colour.
The exception is that there are more than 9 main lineages within Indo-European, so family_ix = 9 has to be used to bring together the remaining minor branches.  So we do need separate colours for the combinations 9-1, 9-3 and 9-5.  

Note that when listing the fields, it makes much more sense to list family_ix before  level1_branch_ix.  That is also the sort order.

**Comment by runjak** [comment]
Alright. I think I'll have this ready soon.

**Comment by cormacanderson** [comment]
Good, I think that sorts it out. Two things though. One, I would replace "Indic Proper" by "ALL Indic" for now at least. The only other thing is that "Baltic" (3-8) is a subbranch of "ALL Balto-Slavic". My understanding of the logic of 'If the branch has a colour: use that colour' would be that Baltic would then get the same colour as Balto-Slavic, but I'm sure you can figure that one out :)

**Comment by PaulHeggarty** [comment]
The simplest is surely to have a branches table that we can edit directly, and which includes a field for the colour ID for each entry in the table. Then we can set them and change them as we wish.  
Ultimately, we could move to using slightly different shades to distinguish, say, North Germanic from West Germanic, but Jakob doesn’t need to waste time hunting for colours.  
In effect, just set it up so that every combination of Family Ix and Level 1 Branch Ix may display a different colour, which we can set.  And just leave it to us to fill in the actual colours in the branches table.

**Comment by runjak** [comment]
I already have such a table and will roll it out soon.

**Comment by runjak** [comment]
I've deployed this but it appears that this change may introduce timeout issues.
If you see a message saying `Gateway Timeout` this hints that page loading times have gotten so slow that the nginx instance decides that the page would likely not be loaded.
![timeout](https://cloud.githubusercontent.com/assets/5417642/13702591/fbe031d4-e78f-11e5-96fa-00c2862f2a1f.png)
I'll try to fix this in the nginx container, and let the instance of the site from before this be the one running on the server.
All in all this may make #84 more pressing - I'll have to investigate.

**Comment by runjak** [comment]
I'm currently testing this with an [increased timeout time](https://stackoverflow.com/questions/10806928/increasing-504-timeout-error),
but if it fails I'll revert the change on the server and test further locally.

**Comment by runjak** [comment]
OK, so I've rolled back this change because it broke the view for 1 meaning across all languages completely. I'll see if and how I can reproduce this on my side and how to fix it.

**Comment by runjak** [comment]
I've tried the exact same setup on my machine and could not observe the same problem.
I will try some different configuration settings for nginx on Sunday when downtime doesn't hurt too much. I think it should be possible to mitigate the timeout problem.

**Comment by runjak** [comment]
The last working commit in the container repo appears to be [f7460f5](https://github.com/lingdb/container/commit/f7460f5662bd1b8fe605cd1b37a4f1ebca3fa674).
The CoBL log reads like this:
```
[12/Mar/2016 13:53:24] "GET /meaning/ HTTP/1.0" 200 918808
- Broken pipe from ('*.*.*.*', 60626)
[12/Mar/2016 13:54:30] "GET /meaning/ HTTP/1.0" 200 918808
- Broken pipe from ('*.*.*.*', 60632)
```
The nginx log yields:
```
2016/03/12 12:53:30 [error] 8#8: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: *.*.*.*, server: cobl.info, request: "GET /meaning/ HTTP/1.1", upstream: "http://*.*.*.*:5000/meaning/", host: "cobl.info", referrer: "http://cobl.info/languageBranches/"
*.*.*.* - user [12/Mar/2016:12:53:30 +0000] "GET /meaning/ HTTP/1.1" 504 182 "http://cobl.info/languageBranches/" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
```
Since I've already raised the nginx timeout to `600` I think that a minute may well be the time that the browser uses to assume a timeout and that therefore the pipe is reported broken.

I think I found a way to deliver at least some partial content already so that the timeout won't be as problematic. But before I can implement that I'll just disable the coloring till I give it another try tomorrow.

**Comment by runjak** [comment]
Memo for myself:
The currently disabled portion of code looks like this:
```
diff --git a/ielex/views.py b/ielex/views.py
index 8c26a8a..fc7f2d0 100644
--- a/ielex/views.py
+++ b/ielex/views.py
@@ -1074,9 +1074,9 @@ def view_meaning(request, meaning, language_list, lexeme_id=None):
             lex_row_form.number_cognate_coded = lex.number_cognate_coded
 
             # Branch color for #92
-            b = lex.language.getLanguageBranch()
-            if b:
-                lex_row_form.languageBranchColor = b.getColor()
+#           b = lex.language.getLanguageBranch()
+#           if b:
+#               lex_row_form.languageBranchColor = b.getColor()
 
             lex_row_form.is_excluded = lex.is_excluded()
             lex_row_form.is_loan = lex.is_loan()
```

**Comment by CasFre** [comment]
There still is an inconsistency with the language list: The bright green now stands for "ALL Romance". Which languages are referred to by that label in this case: Only the descendants of Latin or all the Italic languages, including the old ones like Latin itself, Oscan, Umbrian, Faliscan, etc.? - For our purposes the latter should be the correct option and the label should be "Italic", as in the table from your comment four days ago.

**Comment by PaulHeggarty** [comment]
Please do not worry about the exact terms in the table, it was just done as a very quick thing to get this started, taken over form Sound Comparisons.  It is *nothing* to take literally for now, all of this will be sorted out later.  The point was to try to get the programming done.  It is a pain that these things cannot be easily edited, but that is why they are not updated.  ALL Romance will be renamed Italic.  No more discussion of this list for now, please!

**Comment by CasFre** [comment]
ok
