### ISSUE TITLE
New system for adding and showing citations within basic table view forms

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#95]
There can be citations for various different judgements:
- A lexeme entry in a given language, just to provide further info on that lexeme in that language.  (We already have the Web Dictionary links, but for some languages will need to cite written publications only.)
- A lexeme entry as (the Swadesh term for) a given language.
- A lexeme as a member of a given cognate set.
- A cognate set as a coherent set of cognates in Indo-European.

We need to have a meeting to discuss how best to manage all of those different forms.

The basic system will probably have to be clicking on a citation icon, in its own narrow column within all three basic forms.  In fact, the different types of judgement will mean more than one such icon in some forms.  We should use our normal colour system, as in the main three view icons, to distinguish a citation of a lexeme (green), from a citation of a cognate set (brown).

When clicked, the Citation icon should show a 'bubble' box for viewing any current citations to this lexeme or cognate set., and also allows the user to add a new citation.  Both without having to leave the main form.

The citation bubble box  should contain columns for `Author`, `Date`, `Page Nr` and `Comments`.

The `Author` and `Date` should be taken together as uniquely identifying a publication. (It may even be necessary to add additional letters, e.g. Smith 2001a, Smith 2001b, but we may not yet have any such cases).

As an example of one of the types of citation, see:  
http://134.76.24.144/cognate/citation/1180/edit/

**Comment by runjak** [comment]
As far as I can see the fields for `citation`,`page` and `comments` in the example are taken from the `lexicon_cognateclasscitation` table. It is therefore possible that a cognateclass could have more than one citation. Indeed this happens as can be seen by the following queries:
![multiples](https://cloud.githubusercontent.com/assets/5417642/13493315/b1cbc1b0-e13d-11e5-8611-9fcbca0d95c4.png)
With the `1 meaning all cognate classes` table looking like this:
![1mcc](https://cloud.githubusercontent.com/assets/5417642/13493326/c28251b8-e13d-11e5-82e6-cd3244690750.png)
The question becomes what to do in cases where there is a number `>1` of citations available.
In the `1 meaning all languages` table the question becomes a bit more intricate even as the same cognate class shows up in several rows.
![1mls](https://cloud.githubusercontent.com/assets/5417642/13493418/44478574-e13e-11e5-865a-e68680408f64.png)
I could use the same solution as for the `1 meaning all cognate classes` table here, but would need to keep changes synchronized between several rows to make sure that conflicting changes between different rows don't end up discarding the wrong data.

**Comment by runjak** [comment]
Also: I expect this change to make the loading times problem #84 even more dire since I will need to introduce lookups trough two more tables.

**Comment by cormacanderson** [comment]
Okay, we really don't want to exacerbate #84. It seems to me that this falls under the wider sources issue. For now, I would suggest only implementing this only in the 1 meaning all cognate sets html form, with two fields to accommodate two potential citations. That way, Cassandra, or whoever else, can clean them up, deciding whether or not to keep them, transferring some of the information to notes in some cases. Ultimately, these fields will become reference fields for (usually dictionary) sources. That means we need "citation1", "page1", "citation2" and "page2" as well as "comments" in the 1 meaning/ all cognate sets html form, but not in the 1 meaning/ all languages one. Would that solution work?

**Comment by PaulHeggarty** [comment]
For more clarification on this, see also:
https://github.com/lingdb/CoBL/issues/53

**Comment by runjak** [comment]
This could be done for lexemes as well.
Being able to change the sources/citations from one of the table views could speed up some of the tasks that need to be done.

**Comment by PaulHeggarty** [comment]
Across all bibliographical citations, we should use the same system and fields.  Note how three different tables (Cognate Judgement, Cognate Set and Lexeme) all relate to the Citation table, and through it to the Sources table) in the relational structure: 
![michael dunn s ielex database map relational structure](https://cloud.githubusercontent.com/assets/8819910/15006287/65ee40c0-11cf-11e6-9104-ae30feddeb58.png)

**Comment by PaulHeggarty** [comment]
More generally, we need to move to a 'standard' CLLD (?) system for citations, as for example on pages like http://wals.info/refdb/record/Abbott-2000, so that all our citation sources are recognisable to standard bibliographical management programmes like Zotero and BibTex.  Ask Hans-Jörg and Robert Forkel about this, and I hope you can just copy chunks of their code.

**Comment by khoidt** [comment]
Citations (`Source`) appear now as table data with the following columns in the given order:

1. Details (technical: button to toggle the appearance of BibTeX data that is not included in this list)
2. Title (BibTeX data)
3. Year (BibTeX data)
4. Author (BibTeX data)
5. ENTRYTYPE (BibTeX data)
6. Cognacy (relations: number of relations to `CognateJudgement`)
7. Cogset (relations: should be number of relations to `CognateSet`, s. below)
8. Lexeme (relations: number of relations to `Lexeme`)
9. ☓ (technical: deprecated status checkbox)
10. Edit (technical: edit form button)

To do (@khoidt): 
- [ ] Relate `CognateSet` to `Source` (not related in the database, as seems).
- [ ] Add views to display QuerySets for relations.

**Comment by khoidt** [comment]
Closed. See now #344.
