### ISSUE TITLE
Realign 'show languages' and the respective links.

### ISSUE THREAD

**Issue by CasFre** [lingdb/CoBL#99]
On the main meaning-page  http://www.cobl.info/meanings/, the heading 'show languages' is now too far to the left and figures above the meaning descriptions.

**Comment by runjak** [comment]
Ah, I see that I have to be logged out to get this view at the moment, but I can verify that the heading is placed incorrectly.
![screenshot_2016-04-04_12-25-38](https://cloud.githubusercontent.com/assets/5417642/14245272/5d1b61f2-fa60-11e5-8c42-30c68f4b5704.png)
I'll make sure to change this.

**Comment by runjak** [comment]
If I remember correctly, the descriptions aren't displayed when logged in,
because it was decided that we'd rather link people to the meaning definitions in the GitHub wiki. I will fix this issue by removing the incorrectly displayed descriptions and linking to the wiki in the logged out version.
